CREATE TABLE t1(id int, c text);
INSERT INTO t1 VALUES (1, 'a'), (2, 'b'), (null, 'c');

SELECT * FROM t1 ORDER BY id;
SELECT * FROM t1 ORDER BY id NULLS FIRST;
SELECT * FROM t1 ORDER BY id NULLS LAST;
SELECT * FROM t1 ORDER BY id DESC;
SELECT * FROM t1 ORDER BY id DESC NULLS FIRST;
SELECT * FROM t1 ORDER BY id DESC NULLS LAST;

DROP TABLE t1;
