SET duckdb.force_execution = true;

CREATE TABLE t (a INT);
INSERT INTO t SELECT i FROM generate_series(1, 10) AS i;

SELECT * FROM t TABLESAMPLE SYSTEM (100);

SELECT * FROM t TABLESAMPLE BERNOULLI (100);
SELECT * FROM t TABLESAMPLE BERNOULLI (50) REPEATABLE(42);

DROP TABLE t;
