Vagrant.configure(2) do |config|
    config.vm.provider :virtualbox do |vb|
        vb.memory = 1024
        vb.cpus = 4
        vb.name = "pgaudit-centos7"
    end

    config.vm.define "co7" do |co7|
        co7.vm.box = "bento/centos-7.1"

        # Provision the VM
        co7.vm.provision "shell", inline: <<-SHELL
            yum -y install perl
            wget http://dl.fedoraproject.org/pub/epel/7/x86_64/p/perl-IPC-System-Simple-1.25-1.el7.noarch.rpm
            yum -y localinstall perl-IPC-System-Simple-1.25-1.el7.noarch.rpm

            yum -y install git
            yum -y install gcc
            yum -y install readline-devel
            yum -y install zlib-devel
            yum -y install bison
            yum -y install flex
            yum -y install perl-DBD-Pg
            sudo -u vagrant git clone https://github.com/postgres/postgres.git -b REL9_5_STABLE postgres

            cd postgres
            sudo -u vagrant ./configure
            sudo -u vagrant make -j 4 -s install
            make -s install

            cd contrib
            sudo -u vagrant git clone https://github.com/pgaudit/pgaudit.git pgaudit

            cd pgaudit
            sudo -u vagrant make -s check
            make -s install

            echo 'PATH=/usr/local/pgsql/bin:$PATH' >> /etc/profile
            echo 'export PATH' >> /etc/profile
        SHELL
    end

    # Don't share the default vagrant folder
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # Mount pgaudit path for testing
    config.vm.synced_folder "../..", "/pgaudit"
end
