#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/ybgin
#
# IDENTIFICATION
#    src/backend/access/ybgin/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/ybgin
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = ybgin.o

include $(top_srcdir)/src/backend/common.mk
