/*
 *
 * errcodes.txt
 *      PostgreSQL error codes
 *
 * Copyright (c) 2003-2015, PostgreSQL Global Development Group
 *
 * This list serves as the basis for generating source files containing error
 * codes. It is kept in a common format to make sure all these source files have
 * the same contents.
 * The files generated from this one are:
 *
 *   src/include/utils/errcodes.h
 *      macros defining errcode constants to be used in the rest of the source
 *
 *   src/pl/plpgsql/src/plerrcodes.h
 *      a list of PL/pgSQL condition names and their SQLSTATE codes
 *
 *   doc/src/sgml/errcodes-list.sgml
 *      a SGML table of error codes for inclusion in the documentation
 *
 * The format of this file is one error code per line, with the following
 * whitespace-separated fields:
 *
 *      sqlstate    E/W/S    errcode_macro_name    spec_name
 *
 * where sqlstate is a five-character string following the SQLSTATE conventions,
 * the second field indicates if the code means an error, a warning or success,
 * errcode_macro_name is the C macro name starting with ERRCODE that will be put
 * in errcodes.h, and spec_name is a lowercase, underscore-separated name that
 * will be used as the PL/pgSQL condition name and will also be included in the
 * SGML list. The last field is optional, if not present the PL/pgSQL condition
 * and the SGML entry will not be generated.
 *
 * Empty lines and lines starting with a hash are comments.
 *
 * There are also special lines in the format of:
 *
 *      Section: section description
 *
 * that is, lines starting with the string "Section:". They are used to delimit
 * error classes as defined in the SQL spec, and are necessary for SGML output.
 *
 *
 *      SQLSTATE codes for errors.
 *
 * The SQL99 code set is rather impoverished, especially in the area of
 * syntactical and semantic errors.  We have borrowed codes from IBM's DB2
 * and invented our own codes to develop a useful code set.
 *
 * When adding a new code, make sure it is placed in the most appropriate
 * class (the first two characters of the code value identify the class).
 * The listing is organized by class to make this prominent.
 *
 * Each class should have a generic '000' subclass.  However,
 * the generic '000' subclass code should be used for an error only
 * when there is not a more-specific subclass code defined.
 *
 * The SQL spec requires that all the elements of a SQLSTATE code be
 * either digits or upper-case ASCII characters.
 *
 * Classes that begin with 0-4 or A-H are defined by the
 * standard. Within such a class, subclass values defined by the
 * standard must begin with 0-4 or A-H. To define a new error code,
 * ensure that it is either in an "implementation-defined class" (it
 * begins with 5-9 or I-Z), or its subclass falls outside the range of
 * error codes that could be present in future versions of the
 * standard (i.e. the subclass value begins with 5-9 or I-Z).
 *
 * The convention is that new error codes defined by PostgreSQL in a
 * class defined by the standard have a subclass value that begins
 * with 'P'. In addition, error codes defined by PostgreSQL clients
 * (such as ecpg) have a class value that begins with 'Y'.
 */
#ifndef YB_SQL_ERRCODES_H
#define YB_SQL_ERRCODES_H

enum {
  ERRCODE_SUCCESSFUL_COMPLETION,
  ERRCODE_WARNING,
  ERRCODE_WARNING_DYNAMIC_RESULT_SETS_RETURNED,
  ERRCODE_WARNING_IMPLICIT_ZERO_BIT_PADDING,
  ERRCODE_WARNING_NULL_VALUE_ELIMINATED_IN_SET_FUNCTION,
  ERRCODE_WARNING_PRIVILEGE_NOT_GRANTED,
  ERRCODE_WARNING_PRIVILEGE_NOT_REVOKED,
  ERRCODE_WARNING_STRING_DATA_RIGHT_TRUNCATION,
  ERRCODE_WARNING_DEPRECATED_FEATURE,
  ERRCODE_NO_DATA,
  ERRCODE_NO_ADDITIONAL_DYNAMIC_RESULT_SETS_RETURNED,
  ERRCODE_SQL_STATEMENT_NOT_YET_COMPLETE,
  ERRCODE_CONNECTION_EXCEPTION,
  ERRCODE_CONNECTION_DOES_NOT_EXIST,
  ERRCODE_CONNECTION_FAILURE,
  ERRCODE_SQLCLIENT_UNABLE_TO_ESTABLISH_SQLCONNECTION,
  ERRCODE_SQLSERVER_REJECTED_ESTABLISHMENT_OF_SQLCONNECTION,
  ERRCODE_TRANSACTION_RESOLUTION_UNKNOWN,
  ERRCODE_PROTOCOL_VIOLATION,
  ERRCODE_TRIGGERED_ACTION_EXCEPTION,
  ERRCODE_FEATURE_NOT_SUPPORTED,
  ERRCODE_INVALID_TRANSACTION_INITIATION,
  ERRCODE_LOCATOR_EXCEPTION,
  ERRCODE_L_E_INVALID_SPECIFICATION,
  ERRCODE_INVALID_GRANTOR,
  ERRCODE_INVALID_GRANT_OPERATION,
  ERRCODE_INVALID_ROLE_SPECIFICATION,
  ERRCODE_DIAGNOSTICS_EXCEPTION,
  ERRCODE_STACKED_DIAGNOSTICS_ACCESSED_WITHOUT_ACTIVE_HANDLER,
  ERRCODE_CASE_NOT_FOUND,
  ERRCODE_CARDINALITY_VIOLATION,
  ERRCODE_DATA_EXCEPTION,
  ERRCODE_ARRAY_ELEMENT_ERROR,
  ERRCODE_ARRAY_SUBSCRIPT_ERROR,
  ERRCODE_CHARACTER_NOT_IN_REPERTOIRE,
  ERRCODE_DATETIME_FIELD_OVERFLOW,
  ERRCODE_DATETIME_VALUE_OUT_OF_RANGE,
  ERRCODE_DIVISION_BY_ZERO,
  ERRCODE_ERROR_IN_ASSIGNMENT,
  ERRCODE_ESCAPE_CHARACTER_CONFLICT,
  ERRCODE_INDICATOR_OVERFLOW,
  ERRCODE_INTERVAL_FIELD_OVERFLOW,
  ERRCODE_INVALID_ARGUMENT_FOR_LOG,
  ERRCODE_INVALID_ARGUMENT_FOR_NTILE,
  ERRCODE_INVALID_ARGUMENT_FOR_NTH_VALUE,
  ERRCODE_INVALID_ARGUMENT_FOR_POWER_FUNCTION,
  ERRCODE_INVALID_ARGUMENT_FOR_WIDTH_BUCKET_FUNCTION,
  ERRCODE_INVALID_CHARACTER_VALUE_FOR_CAST,
  ERRCODE_INVALID_DATETIME_FORMAT,
  ERRCODE_INVALID_ESCAPE_CHARACTER,
  ERRCODE_INVALID_ESCAPE_OCTET,
  ERRCODE_INVALID_ESCAPE_SEQUENCE,
  ERRCODE_NONSTANDARD_USE_OF_ESCAPE_CHARACTER,
  ERRCODE_INVALID_INDICATOR_PARAMETER_VALUE,
  ERRCODE_INVALID_PARAMETER_VALUE,
  ERRCODE_INVALID_REGULAR_EXPRESSION,
  ERRCODE_INVALID_ROW_COUNT_IN_LIMIT_CLAUSE,
  ERRCODE_INVALID_ROW_COUNT_IN_RESULT_OFFSET_CLAUSE,
  ERRCODE_INVALID_TABLESAMPLE_ARGUMENT,
  ERRCODE_INVALID_TABLESAMPLE_REPEAT,
  ERRCODE_INVALID_TIME_ZONE_DISPLACEMENT_VALUE,
  ERRCODE_INVALID_USE_OF_ESCAPE_CHARACTER,
  ERRCODE_MOST_SPECIFIC_TYPE_MISMATCH,
  ERRCODE_NULL_VALUE_NOT_ALLOWED,
  ERRCODE_NULL_VALUE_NO_INDICATOR_PARAMETER,
  ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE,
  ERRCODE_STRING_DATA_LENGTH_MISMATCH,
  ERRCODE_STRING_DATA_RIGHT_TRUNCATION,
  ERRCODE_SUBSTRING_ERROR,
  ERRCODE_TRIM_ERROR,
  ERRCODE_UNTERMINATED_C_STRING,
  ERRCODE_ZERO_LENGTH_CHARACTER_STRING,
  ERRCODE_FLOATING_POINT_EXCEPTION,
  ERRCODE_INVALID_TEXT_REPRESENTATION,
  ERRCODE_INVALID_BINARY_REPRESENTATION,
  ERRCODE_BAD_COPY_FILE_FORMAT,
  ERRCODE_UNTRANSLATABLE_CHARACTER,
  ERRCODE_NOT_AN_XML_DOCUMENT,
  ERRCODE_INVALID_XML_DOCUMENT,
  ERRCODE_INVALID_XML_CONTENT,
  ERRCODE_INVALID_XML_COMMENT,
  ERRCODE_INVALID_XML_PROCESSING_INSTRUCTION,
  ERRCODE_INTEGRITY_CONSTRAINT_VIOLATION,
  ERRCODE_RESTRICT_VIOLATION,
  ERRCODE_NOT_NULL_VIOLATION,
  ERRCODE_FOREIGN_KEY_VIOLATION,
  ERRCODE_UNIQUE_VIOLATION,
  ERRCODE_CHECK_VIOLATION,
  ERRCODE_EXCLUSION_VIOLATION,
  ERRCODE_INVALID_CURSOR_STATE,
  ERRCODE_INVALID_TRANSACTION_STATE,
  ERRCODE_ACTIVE_SQL_TRANSACTION,
  ERRCODE_BRANCH_TRANSACTION_ALREADY_ACTIVE,
  ERRCODE_HELD_CURSOR_REQUIRES_SAME_ISOLATION_LEVEL,
  ERRCODE_INAPPROPRIATE_ACCESS_MODE_FOR_BRANCH_TRANSACTION,
  ERRCODE_INAPPROPRIATE_ISOLATION_LEVEL_FOR_BRANCH_TRANSACTION,
  ERRCODE_NO_ACTIVE_SQL_TRANSACTION_FOR_BRANCH_TRANSACTION,
  ERRCODE_READ_ONLY_SQL_TRANSACTION,
  ERRCODE_SCHEMA_AND_DATA_STATEMENT_MIXING_NOT_SUPPORTED,
  ERRCODE_NO_ACTIVE_SQL_TRANSACTION,
  ERRCODE_IN_FAILED_SQL_TRANSACTION,
  ERRCODE_INVALID_SQL_STATEMENT_NAME,
  ERRCODE_TRIGGERED_DATA_CHANGE_VIOLATION,
  ERRCODE_INVALID_AUTHORIZATION_SPECIFICATION,
  ERRCODE_INVALID_PASSWORD,
  ERRCODE_DEPENDENT_PRIVILEGE_DESCRIPTORS_STILL_EXIST,
  ERRCODE_DEPENDENT_OBJECTS_STILL_EXIST,
  ERRCODE_INVALID_TRANSACTION_TERMINATION,
  ERRCODE_SQL_ROUTINE_EXCEPTION,
  ERRCODE_S_R_E_FUNCTION_EXECUTED_NO_RETURN_STATEMENT,
  ERRCODE_S_R_E_MODIFYING_SQL_DATA_NOT_PERMITTED,
  ERRCODE_S_R_E_PROHIBITED_SQL_STATEMENT_ATTEMPTED,
  ERRCODE_S_R_E_READING_SQL_DATA_NOT_PERMITTED,
  ERRCODE_INVALID_CURSOR_NAME,
  ERRCODE_EXTERNAL_ROUTINE_EXCEPTION,
  ERRCODE_E_R_E_CONTAINING_SQL_NOT_PERMITTED,
  ERRCODE_E_R_E_MODIFYING_SQL_DATA_NOT_PERMITTED,
  ERRCODE_E_R_E_PROHIBITED_SQL_STATEMENT_ATTEMPTED,
  ERRCODE_E_R_E_READING_SQL_DATA_NOT_PERMITTED,
  ERRCODE_EXTERNAL_ROUTINE_INVOCATION_EXCEPTION,
  ERRCODE_E_R_I_E_INVALID_SQLSTATE_RETURNED,
  ERRCODE_E_R_I_E_NULL_VALUE_NOT_ALLOWED,
  ERRCODE_E_R_I_E_TRIGGER_PROTOCOL_VIOLATED,
  ERRCODE_E_R_I_E_SRF_PROTOCOL_VIOLATED,
  ERRCODE_E_R_I_E_EVENT_TRIGGER_PROTOCOL_VIOLATED,
  ERRCODE_SAVEPOINT_EXCEPTION,
  ERRCODE_S_E_INVALID_SPECIFICATION,
  ERRCODE_INVALID_CATALOG_NAME,
  ERRCODE_INVALID_SCHEMA_NAME,
  ERRCODE_TRANSACTION_ROLLBACK,
  ERRCODE_T_R_INTEGRITY_CONSTRAINT_VIOLATION,
  ERRCODE_T_R_SERIALIZATION_FAILURE,
  ERRCODE_T_R_STATEMENT_COMPLETION_UNKNOWN,
  ERRCODE_T_R_DEADLOCK_DETECTED,
  ERRCODE_SYNTAX_ERROR_OR_ACCESS_RULE_VIOLATION,
  ERRCODE_SYNTAX_ERROR,
  ERRCODE_INSUFFICIENT_PRIVILEGE,
  ERRCODE_CANNOT_COERCE,
  ERRCODE_GROUPING_ERROR,
  ERRCODE_WINDOWING_ERROR,
  ERRCODE_INVALID_RECURSION,
  ERRCODE_INVALID_FOREIGN_KEY,
  ERRCODE_INVALID_NAME,
  ERRCODE_NAME_TOO_LONG,
  ERRCODE_RESERVED_NAME,
  ERRCODE_DATATYPE_MISMATCH,
  ERRCODE_INDETERMINATE_DATATYPE,
  ERRCODE_COLLATION_MISMATCH,
  ERRCODE_INDETERMINATE_COLLATION,
  ERRCODE_WRONG_OBJECT_TYPE,
  ERRCODE_UNDEFINED_COLUMN,
  ERRCODE_UNDEFINED_CURSOR,
  ERRCODE_UNDEFINED_DATABASE,
  ERRCODE_UNDEFINED_FUNCTION,
  ERRCODE_UNDEFINED_PSTATEMENT,
  ERRCODE_UNDEFINED_SCHEMA,
  ERRCODE_UNDEFINED_TABLE,
  ERRCODE_UNDEFINED_PARAMETER,
  ERRCODE_UNDEFINED_OBJECT,
  ERRCODE_DUPLICATE_COLUMN,
  ERRCODE_DUPLICATE_CURSOR,
  ERRCODE_DUPLICATE_DATABASE,
  ERRCODE_DUPLICATE_FUNCTION,
  ERRCODE_DUPLICATE_PSTATEMENT,
  ERRCODE_DUPLICATE_SCHEMA,
  ERRCODE_DUPLICATE_TABLE,
  ERRCODE_DUPLICATE_ALIAS,
  ERRCODE_DUPLICATE_OBJECT,
  ERRCODE_AMBIGUOUS_COLUMN,
  ERRCODE_AMBIGUOUS_FUNCTION,
  ERRCODE_AMBIGUOUS_PARAMETER,
  ERRCODE_AMBIGUOUS_ALIAS,
  ERRCODE_INVALID_COLUMN_REFERENCE,
  ERRCODE_INVALID_COLUMN_DEFINITION,
  ERRCODE_INVALID_CURSOR_DEFINITION,
  ERRCODE_INVALID_DATABASE_DEFINITION,
  ERRCODE_INVALID_FUNCTION_DEFINITION,
  ERRCODE_INVALID_PSTATEMENT_DEFINITION,
  ERRCODE_INVALID_SCHEMA_DEFINITION,
  ERRCODE_INVALID_TABLE_DEFINITION,
  ERRCODE_INVALID_OBJECT_DEFINITION,
  ERRCODE_WITH_CHECK_OPTION_VIOLATION,
  ERRCODE_INSUFFICIENT_RESOURCES,
  ERRCODE_DISK_FULL,
  ERRCODE_OUT_OF_MEMORY,
  ERRCODE_TOO_MANY_CONNECTIONS,
  ERRCODE_CONFIGURATION_LIMIT_EXCEEDED,
  ERRCODE_PROGRAM_LIMIT_EXCEEDED,
  ERRCODE_STATEMENT_TOO_COMPLEX,
  ERRCODE_TOO_MANY_COLUMNS,
  ERRCODE_TOO_MANY_ARGUMENTS,
  ERRCODE_OBJECT_NOT_IN_PREREQUISITE_STATE,
  ERRCODE_OBJECT_IN_USE,
  ERRCODE_CANT_CHANGE_RUNTIME_PARAM,
  ERRCODE_LOCK_NOT_AVAILABLE,
  ERRCODE_OPERATOR_INTERVENTION,
  ERRCODE_QUERY_CANCELED,
  ERRCODE_ADMIN_SHUTDOWN,
  ERRCODE_CRASH_SHUTDOWN,
  ERRCODE_CANNOT_CONNECT_NOW,
  ERRCODE_DATABASE_DROPPED,
  ERRCODE_SYSTEM_ERROR,
  ERRCODE_IO_ERROR,
  ERRCODE_UNDEFINED_FILE,
  ERRCODE_DUPLICATE_FILE,
  ERRCODE_CONFIG_FILE_ERROR,
  ERRCODE_LOCK_FILE_EXISTS,
  ERRCODE_FDW_ERROR,
  ERRCODE_FDW_COLUMN_NAME_NOT_FOUND,
  ERRCODE_FDW_DYNAMIC_PARAMETER_VALUE_NEEDED,
  ERRCODE_FDW_FUNCTION_SEQUENCE_ERROR,
  ERRCODE_FDW_INCONSISTENT_DESCRIPTOR_INFORMATION,
  ERRCODE_FDW_INVALID_ATTRIBUTE_VALUE,
  ERRCODE_FDW_INVALID_COLUMN_NAME,
  ERRCODE_FDW_INVALID_COLUMN_NUMBER,
  ERRCODE_FDW_INVALID_DATA_TYPE,
  ERRCODE_FDW_INVALID_DATA_TYPE_DESCRIPTORS,
  ERRCODE_FDW_INVALID_DESCRIPTOR_FIELD_IDENTIFIER,
  ERRCODE_FDW_INVALID_HANDLE,
  ERRCODE_FDW_INVALID_OPTION_INDEX,
  ERRCODE_FDW_INVALID_OPTION_NAME,
  ERRCODE_FDW_INVALID_STRING_LENGTH_OR_BUFFER_LENGTH,
  ERRCODE_FDW_INVALID_STRING_FORMAT,
  ERRCODE_FDW_INVALID_USE_OF_NULL_POINTER,
  ERRCODE_FDW_TOO_MANY_HANDLES,
  ERRCODE_FDW_OUT_OF_MEMORY,
  ERRCODE_FDW_NO_SCHEMAS,
  ERRCODE_FDW_OPTION_NAME_NOT_FOUND,
  ERRCODE_FDW_REPLY_HANDLE,
  ERRCODE_FDW_SCHEMA_NOT_FOUND,
  ERRCODE_FDW_TABLE_NOT_FOUND,
  ERRCODE_FDW_UNABLE_TO_CREATE_EXECUTION,
  ERRCODE_FDW_UNABLE_TO_CREATE_REPLY,
  ERRCODE_FDW_UNABLE_TO_ESTABLISH_CONNECTION,
  ERRCODE_PLPGSQL_ERROR,
  ERRCODE_RAISE_EXCEPTION,
  ERRCODE_NO_DATA_FOUND,
  ERRCODE_TOO_MANY_ROWS,
  ERRCODE_ASSERT_FAILURE,
  ERRCODE_INTERNAL_ERROR,
  ERRCODE_DATA_CORRUPTED,
  ERRCODE_INDEX_CORRUPTED,
};

#endif // YB_SQL_ERRCODES_H
