// Copyright (c) YugaByte, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"), you may not use this file except
// in compliance with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied.  See the License for the specific language governing permissions and limitations
// under the License.
//
// Portions Copyright (c) 1996-2018, PostgreSQL Global Development Group
// Portions Copyright (c) 1994, Regents of the University of California

#pragma once

#include <stdint.h>

#include <string>

/* These macro definitions have been taken from elog.h */
#define YB_PGSIXBIT(ch) (((ch) - '0') & 0x3F)

#define YB_PG_MAKE_SQLSTATE(ch1, ch2, ch3, ch4, ch5) \
    (YB_PGSIXBIT(ch1) + (YB_PGSIXBIT(ch2) << 6) + (YB_PGSIXBIT(ch3) << 12) + \
    (YB_PGSIXBIT(ch4) << 18) + (YB_PGSIXBIT(ch5) << 24))

/* The actual PostgreSQL error codes have been taken from the generated errcodes.h file. */
namespace yb {

enum class YBPgErrorCode : uint32_t {
  /* Class 00 - Successful Completion */
  YB_PG_SUCCESSFUL_COMPLETION = YB_PG_MAKE_SQLSTATE('0', '0', '0', '0', '0'),

  /* Class 01 - Warning */
  YB_PG_WARNING = YB_PG_MAKE_SQLSTATE('0', '1', '0', '0', '0'),
  YB_PG_WARNING_DYNAMIC_RESULT_SETS_RETURNED = YB_PG_MAKE_SQLSTATE('0', '1', '0', '0', 'C'),
  YB_PG_WARNING_IMPLICIT_ZERO_BIT_PADDING = YB_PG_MAKE_SQLSTATE('0', '1', '0', '0', '8'),
  YB_PG_WARNING_NULL_VALUE_ELIMINATED_IN_SET_FUNCTION =
      YB_PG_MAKE_SQLSTATE('0', '1', '0', '0', '3'),
  YB_PG_WARNING_PRIVILEGE_NOT_GRANTED = YB_PG_MAKE_SQLSTATE('0', '1', '0', '0', '7'),
  YB_PG_WARNING_PRIVILEGE_NOT_REVOKED = YB_PG_MAKE_SQLSTATE('0', '1', '0', '0', '6'),
  YB_PG_WARNING_STRING_DATA_RIGHT_TRUNCATION = YB_PG_MAKE_SQLSTATE('0', '1', '0', '0', '4'),
  YB_PG_WARNING_DEPRECATED_FEATURE = YB_PG_MAKE_SQLSTATE('0', '1', 'P', '0', '1'),

  /* Class 02 - No Data (this is also a warning class per the SQL standard) */
  YB_PG_NO_DATA = YB_PG_MAKE_SQLSTATE('0', '2', '0', '0', '0'),
  YB_PG_NO_ADDITIONAL_DYNAMIC_RESULT_SETS_RETURNED = YB_PG_MAKE_SQLSTATE('0', '2', '0', '0', '1'),

  /* Class 03 - SQL Statement Not Yet Complete */
  YB_PG_SQL_STATEMENT_NOT_YET_COMPLETE = YB_PG_MAKE_SQLSTATE('0', '3', '0', '0', '0'),

  /* Class 08 - Connection Exception */
  YB_PG_CONNECTION_EXCEPTION = YB_PG_MAKE_SQLSTATE('0', '8', '0', '0', '0'),
  YB_PG_CONNECTION_DOES_NOT_EXIST = YB_PG_MAKE_SQLSTATE('0', '8', '0', '0', '3'),
  YB_PG_CONNECTION_FAILURE = YB_PG_MAKE_SQLSTATE('0', '8', '0', '0', '6'),
  YB_PG_SQLCLIENT_UNABLE_TO_ESTABLISH_SQLCONNECTION =
      YB_PG_MAKE_SQLSTATE('0', '8', '0', '0', '1'),
  YB_PG_SQLSERVER_REJECTED_ESTABLISHMENT_OF_SQLCONNECTION =
      YB_PG_MAKE_SQLSTATE('0', '8', '0', '0', '4'),
  YB_PG_TRANSACTION_RESOLUTION_UNKNOWN = YB_PG_MAKE_SQLSTATE('0', '8', '0', '0', '7'),
  YB_PG_PROTOCOL_VIOLATION = YB_PG_MAKE_SQLSTATE('0', '8', 'P', '0', '1'),

  /* Class 09 - Triggered Action Exception */
  YB_PG_TRIGGERED_ACTION_EXCEPTION = YB_PG_MAKE_SQLSTATE('0', '9', '0', '0', '0'),

  /* Class 0A - Feature Not Supported */
  YB_PG_FEATURE_NOT_SUPPORTED = YB_PG_MAKE_SQLSTATE('0', 'A', '0', '0', '0'),

  /* Class 0B - Invalid Transaction Initiation */
  YB_PG_INVALID_TRANSACTION_INITIATION = YB_PG_MAKE_SQLSTATE('0', 'B', '0', '0', '0'),

  /* Class 0F - Locator Exception */
  YB_PG_LOCATOR_EXCEPTION = YB_PG_MAKE_SQLSTATE('0', 'F', '0', '0', '0'),
  YB_PG_L_E_INVALID_SPECIFICATION = YB_PG_MAKE_SQLSTATE('0', 'F', '0', '0', '1'),

  /* Class 0L - Invalid Grantor */
  YB_PG_INVALID_GRANTOR = YB_PG_MAKE_SQLSTATE('0', 'L', '0', '0', '0'),
  YB_PG_INVALID_GRANT_OPERATION = YB_PG_MAKE_SQLSTATE('0', 'L', 'P', '0', '1'),

  /* Class 0P - Invalid Role Specification */
  YB_PG_INVALID_ROLE_SPECIFICATION = YB_PG_MAKE_SQLSTATE('0', 'P', '0', '0', '0'),

  /* Class 0Z - Diagnostics Exception */
  YB_PG_DIAGNOSTICS_EXCEPTION = YB_PG_MAKE_SQLSTATE('0', 'Z', '0', '0', '0'),
  YB_PG_STACKED_DIAGNOSTICS_ACCESSED_WITHOUT_ACTIVE_HANDLER =
      YB_PG_MAKE_SQLSTATE('0', 'Z', '0', '0', '2'),

  /* Class 20 - Case Not Found */
  YB_PG_CASE_NOT_FOUND = YB_PG_MAKE_SQLSTATE('2', '0', '0', '0', '0'),

  /* Class 21 - Cardinality Violation */
  YB_PG_CARDINALITY_VIOLATION = YB_PG_MAKE_SQLSTATE('2', '1', '0', '0', '0'),

  /* Class 22 - Data Exception */
  YB_PG_DATA_EXCEPTION = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', '0'),
  YB_PG_ARRAY_ELEMENT_ERROR = YB_PG_MAKE_SQLSTATE('2', '2', '0', '2', 'E'),
  YB_PG_ARRAY_SUBSCRIPT_ERROR = YB_PG_MAKE_SQLSTATE('2', '2', '0', '2', 'E'),
  YB_PG_CHARACTER_NOT_IN_REPERTOIRE = YB_PG_MAKE_SQLSTATE('2', '2', '0', '2', '1'),
  YB_PG_DATETIME_FIELD_OVERFLOW = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', '8'),
  YB_PG_DATETIME_VALUE_OUT_OF_RANGE = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', '8'),
  YB_PG_DIVISION_BY_ZERO = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', '2'),
  YB_PG_ERROR_IN_ASSIGNMENT = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', '5'),
  YB_PG_ESCAPE_CHARACTER_CONFLICT = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', 'B'),
  YB_PG_INDICATOR_OVERFLOW = YB_PG_MAKE_SQLSTATE('2', '2', '0', '2', '2'),
  YB_PG_INTERVAL_FIELD_OVERFLOW = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', '5'),
  YB_PG_INVALID_ARGUMENT_FOR_LOG = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', 'E'),
  YB_PG_INVALID_ARGUMENT_FOR_NTILE = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', '4'),
  YB_PG_INVALID_ARGUMENT_FOR_NTH_VALUE = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', '6'),
  YB_PG_INVALID_ARGUMENT_FOR_POWER_FUNCTION = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', 'F'),
  YB_PG_INVALID_ARGUMENT_FOR_WIDTH_BUCKET_FUNCTION = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', 'G'),
  YB_PG_INVALID_CHARACTER_VALUE_FOR_CAST = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', '8'),
  YB_PG_INVALID_DATETIME_FORMAT = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', '7'),
  YB_PG_INVALID_ESCAPE_CHARACTER = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', '9'),
  YB_PG_INVALID_ESCAPE_OCTET = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', 'D'),
  YB_PG_INVALID_ESCAPE_SEQUENCE = YB_PG_MAKE_SQLSTATE('2', '2', '0', '2', '5'),
  YB_PG_NONSTANDARD_USE_OF_ESCAPE_CHARACTER = YB_PG_MAKE_SQLSTATE('2', '2', 'P', '0', '6'),
  YB_PG_INVALID_INDICATOR_PARAMETER_VALUE = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', '0'),
  YB_PG_INVALID_PARAMETER_VALUE = YB_PG_MAKE_SQLSTATE('2', '2', '0', '2', '3'),
  YB_PG_INVALID_PRECEDING_OR_FOLLOWING_SIZE = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', '3'),
  YB_PG_INVALID_REGULAR_EXPRESSION = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', 'B'),
  YB_PG_INVALID_ROW_COUNT_IN_LIMIT_CLAUSE = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', 'W'),
  YB_PG_INVALID_ROW_COUNT_IN_RESULT_OFFSET_CLAUSE = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', 'X'),
  YB_PG_INVALID_TABLESAMPLE_ARGUMENT = YB_PG_MAKE_SQLSTATE('2', '2', '0', '2', 'H'),
  YB_PG_INVALID_TABLESAMPLE_REPEAT = YB_PG_MAKE_SQLSTATE('2', '2', '0', '2', 'G'),
  YB_PG_INVALID_TIME_ZONE_DISPLACEMENT_VALUE = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', '9'),
  YB_PG_INVALID_USE_OF_ESCAPE_CHARACTER = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', 'C'),
  YB_PG_MOST_SPECIFIC_TYPE_MISMATCH = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', 'G'),
  YB_PG_NULL_VALUE_NOT_ALLOWED = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', '4'),
  YB_PG_NULL_VALUE_NO_INDICATOR_PARAMETER = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', '2'),
  YB_PG_NUMERIC_VALUE_OUT_OF_RANGE = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', '3'),
  YB_PG_SEQUENCE_GENERATOR_LIMIT_EXCEEDED = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', 'H'),
  YB_PG_STRING_DATA_LENGTH_MISMATCH = YB_PG_MAKE_SQLSTATE('2', '2', '0', '2', '6'),
  YB_PG_STRING_DATA_RIGHT_TRUNCATION = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', '1'),
  YB_PG_SUBSTRING_ERROR = YB_PG_MAKE_SQLSTATE('2', '2', '0', '1', '1'),
  YB_PG_TRIM_ERROR = YB_PG_MAKE_SQLSTATE('2', '2', '0', '2', '7'),
  YB_PG_UNTERMINATED_C_STRING = YB_PG_MAKE_SQLSTATE('2', '2', '0', '2', '4'),
  YB_PG_ZERO_LENGTH_CHARACTER_STRING = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', 'F'),
  YB_PG_FLOATING_POINT_EXCEPTION = YB_PG_MAKE_SQLSTATE('2', '2', 'P', '0', '1'),
  YB_PG_INVALID_TEXT_REPRESENTATION = YB_PG_MAKE_SQLSTATE('2', '2', 'P', '0', '2'),
  YB_PG_INVALID_BINARY_REPRESENTATION = YB_PG_MAKE_SQLSTATE('2', '2', 'P', '0', '3'),
  YB_PG_BAD_COPY_FILE_FORMAT = YB_PG_MAKE_SQLSTATE('2', '2', 'P', '0', '4'),
  YB_PG_UNTRANSLATABLE_CHARACTER = YB_PG_MAKE_SQLSTATE('2', '2', 'P', '0', '5'),
  YB_PG_NOT_AN_XML_DOCUMENT = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', 'L'),
  YB_PG_INVALID_XML_DOCUMENT = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', 'M'),
  YB_PG_INVALID_XML_CONTENT = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', 'N'),
  YB_PG_INVALID_XML_COMMENT = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', 'S'),
  YB_PG_INVALID_XML_PROCESSING_INSTRUCTION = YB_PG_MAKE_SQLSTATE('2', '2', '0', '0', 'T'),

  /* Class 23 - Integrity Constraint Violation */
  YB_PG_INTEGRITY_CONSTRAINT_VIOLATION = YB_PG_MAKE_SQLSTATE('2', '3', '0', '0', '0'),
  YB_PG_RESTRICT_VIOLATION = YB_PG_MAKE_SQLSTATE('2', '3', '0', '0', '1'),
  YB_PG_NOT_NULL_VIOLATION = YB_PG_MAKE_SQLSTATE('2', '3', '5', '0', '2'),
  YB_PG_FOREIGN_KEY_VIOLATION = YB_PG_MAKE_SQLSTATE('2', '3', '5', '0', '3'),
  YB_PG_UNIQUE_VIOLATION = YB_PG_MAKE_SQLSTATE('2', '3', '5', '0', '5'),
  YB_PG_CHECK_VIOLATION = YB_PG_MAKE_SQLSTATE('2', '3', '5', '1', '4'),
  YB_PG_EXCLUSION_VIOLATION = YB_PG_MAKE_SQLSTATE('2', '3', 'P', '0', '1'),

  /* Class 24 - Invalid Cursor State */
  YB_PG_INVALID_CURSOR_STATE = YB_PG_MAKE_SQLSTATE('2', '4', '0', '0', '0'),

  /* Class 25 - Invalid Transaction State */
  YB_PG_INVALID_TRANSACTION_STATE = YB_PG_MAKE_SQLSTATE('2', '5', '0', '0', '0'),
  YB_PG_ACTIVE_SQL_TRANSACTION = YB_PG_MAKE_SQLSTATE('2', '5', '0', '0', '1'),
  YB_PG_BRANCH_TRANSACTION_ALREADY_ACTIVE = YB_PG_MAKE_SQLSTATE('2', '5', '0', '0', '2'),
  YB_PG_HELD_CURSOR_REQUIRES_SAME_ISOLATION_LEVEL =
      YB_PG_MAKE_SQLSTATE('2', '5', '0', '0', '8'),
  YB_PG_INAPPROPRIATE_ACCESS_MODE_FOR_BRANCH_TRANSACTION =
      YB_PG_MAKE_SQLSTATE('2', '5', '0', '0', '3'),
  YB_PG_INAPPROPRIATE_ISOLATION_LEVEL_FOR_BRANCH_TRANSACTION =
      YB_PG_MAKE_SQLSTATE('2', '5', '0', '0', '4'),
  YB_PG_NO_ACTIVE_SQL_TRANSACTION_FOR_BRANCH_TRANSACTION =
      YB_PG_MAKE_SQLSTATE('2', '5', '0', '0', '5'),
  YB_PG_READ_ONLY_SQL_TRANSACTION = YB_PG_MAKE_SQLSTATE('2', '5', '0', '0', '6'),
  YB_PG_SCHEMA_AND_DATA_STATEMENT_MIXING_NOT_SUPPORTED =
      YB_PG_MAKE_SQLSTATE('2', '5', '0', '0', '7'),
  YB_PG_NO_ACTIVE_SQL_TRANSACTION = YB_PG_MAKE_SQLSTATE('2', '5', 'P', '0', '1'),
  YB_PG_IN_FAILED_SQL_TRANSACTION = YB_PG_MAKE_SQLSTATE('2', '5', 'P', '0', '2'),
  YB_PG_IDLE_IN_TRANSACTION_SESSION_TIMEOUT = YB_PG_MAKE_SQLSTATE('2', '5', 'P', '0', '3'),

  /* Class 26 - Invalid SQL Statement Name */
  YB_PG_INVALID_SQL_STATEMENT_NAME = YB_PG_MAKE_SQLSTATE('2', '6', '0', '0', '0'),

  /* Class 27 - Triggered Data Change Violation */
  YB_PG_TRIGGERED_DATA_CHANGE_VIOLATION = YB_PG_MAKE_SQLSTATE('2', '7', '0', '0', '0'),

  /* Class 28 - Invalid Authorization Specification */
  YB_PG_INVALID_AUTHORIZATION_SPECIFICATION = YB_PG_MAKE_SQLSTATE('2', '8', '0', '0', '0'),
  YB_PG_INVALID_PASSWORD = YB_PG_MAKE_SQLSTATE('2', '8', 'P', '0', '1'),

  /* Class 2B - Dependent Privilege Descriptors Still Exist */
  YB_PG_DEPENDENT_PRIVILEGE_DESCRIPTORS_STILL_EXIST =
      YB_PG_MAKE_SQLSTATE('2', 'B', '0', '0', '0'),
  YB_PG_DEPENDENT_OBJECTS_STILL_EXIST = YB_PG_MAKE_SQLSTATE('2', 'B', 'P', '0', '1'),

  /* Class 2D - Invalid Transaction Termination */
  YB_PG_INVALID_TRANSACTION_TERMINATION = YB_PG_MAKE_SQLSTATE('2', 'D', '0', '0', '0'),

  /* Class 2F - SQL Routine Exception */
  YB_PG_SQL_ROUTINE_EXCEPTION = YB_PG_MAKE_SQLSTATE('2', 'F', '0', '0', '0'),
  YB_PG_S_R_E_FUNCTION_EXECUTED_NO_RETURN_STATEMENT =
      YB_PG_MAKE_SQLSTATE('2', 'F', '0', '0', '5'),
  YB_PG_S_R_E_MODIFYING_SQL_DATA_NOT_PERMITTED = YB_PG_MAKE_SQLSTATE('2', 'F', '0', '0', '2'),
  YB_PG_S_R_E_PROHIBITED_SQL_STATEMENT_ATTEMPTED = YB_PG_MAKE_SQLSTATE('2', 'F', '0', '0', '3'),
  YB_PG_S_R_E_READING_SQL_DATA_NOT_PERMITTED = YB_PG_MAKE_SQLSTATE('2', 'F', '0', '0', '4'),

  /* Class 34 - Invalid Cursor Name */
  YB_PG_INVALID_CURSOR_NAME = YB_PG_MAKE_SQLSTATE('3', '4', '0', '0', '0'),

  /* Class 38 - External Routine Exception */
  YB_PG_EXTERNAL_ROUTINE_EXCEPTION = YB_PG_MAKE_SQLSTATE('3', '8', '0', '0', '0'),
  YB_PG_E_R_E_CONTAINING_SQL_NOT_PERMITTED = YB_PG_MAKE_SQLSTATE('3', '8', '0', '0', '1'),
  YB_PG_E_R_E_MODIFYING_SQL_DATA_NOT_PERMITTED = YB_PG_MAKE_SQLSTATE('3', '8', '0', '0', '2'),
  YB_PG_E_R_E_PROHIBITED_SQL_STATEMENT_ATTEMPTED = YB_PG_MAKE_SQLSTATE('3', '8', '0', '0', '3'),
  YB_PG_E_R_E_READING_SQL_DATA_NOT_PERMITTED = YB_PG_MAKE_SQLSTATE('3', '8', '0', '0', '4'),

  /* Class 39 - External Routine Invocation Exception */
  YB_PG_EXTERNAL_ROUTINE_INVOCATION_EXCEPTION = YB_PG_MAKE_SQLSTATE('3', '9', '0', '0', '0'),
  YB_PG_E_R_I_E_INVALID_SQLSTATE_RETURNED = YB_PG_MAKE_SQLSTATE('3', '9', '0', '0', '1'),
  YB_PG_E_R_I_E_NULL_VALUE_NOT_ALLOWED = YB_PG_MAKE_SQLSTATE('3', '9', '0', '0', '4'),
  YB_PG_E_R_I_E_TRIGGER_PROTOCOL_VIOLATED = YB_PG_MAKE_SQLSTATE('3', '9', 'P', '0', '1'),
  YB_PG_E_R_I_E_SRF_PROTOCOL_VIOLATED = YB_PG_MAKE_SQLSTATE('3', '9', 'P', '0', '2'),
  YB_PG_E_R_I_E_EVENT_TRIGGER_PROTOCOL_VIOLATED = YB_PG_MAKE_SQLSTATE('3', '9', 'P', '0', '3'),

  /* Class 3B - Savepoint Exception */
  YB_PG_SAVEPOINT_EXCEPTION = YB_PG_MAKE_SQLSTATE('3', 'B', '0', '0', '0'),
  YB_PG_S_E_INVALID_SPECIFICATION = YB_PG_MAKE_SQLSTATE('3', 'B', '0', '0', '1'),

  /* Class 3D - Invalid Catalog Name */
  YB_PG_INVALID_CATALOG_NAME = YB_PG_MAKE_SQLSTATE('3', 'D', '0', '0', '0'),

  /* Class 3F - Invalid Schema Name */
  YB_PG_INVALID_SCHEMA_NAME = YB_PG_MAKE_SQLSTATE('3', 'F', '0', '0', '0'),

  /* Class 40 - Transaction Rollback */
  YB_PG_TRANSACTION_ROLLBACK = YB_PG_MAKE_SQLSTATE('4', '0', '0', '0', '0'),
  YB_PG_T_R_INTEGRITY_CONSTRAINT_VIOLATION = YB_PG_MAKE_SQLSTATE('4', '0', '0', '0', '2'),
  YB_PG_T_R_SERIALIZATION_FAILURE = YB_PG_MAKE_SQLSTATE('4', '0', '0', '0', '1'),
  YB_PG_T_R_STATEMENT_COMPLETION_UNKNOWN = YB_PG_MAKE_SQLSTATE('4', '0', '0', '0', '3'),
  YB_PG_T_R_DEADLOCK_DETECTED = YB_PG_MAKE_SQLSTATE('4', '0', 'P', '0', '1'),

  /* Class 42 - Syntax Error or Access Rule Violation */
  YB_PG_SYNTAX_ERROR_OR_ACCESS_RULE_VIOLATION = YB_PG_MAKE_SQLSTATE('4', '2', '0', '0', '0'),
  YB_PG_SYNTAX_ERROR = YB_PG_MAKE_SQLSTATE('4', '2', '6', '0', '1'),
  YB_PG_INSUFFICIENT_PRIVILEGE = YB_PG_MAKE_SQLSTATE('4', '2', '5', '0', '1'),
  YB_PG_CANNOT_COERCE = YB_PG_MAKE_SQLSTATE('4', '2', '8', '4', '6'),
  YB_PG_GROUPING_ERROR = YB_PG_MAKE_SQLSTATE('4', '2', '8', '0', '3'),
  YB_PG_WINDOWING_ERROR = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '2', '0'),
  YB_PG_INVALID_RECURSION = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '1', '9'),
  YB_PG_INVALID_FOREIGN_KEY = YB_PG_MAKE_SQLSTATE('4', '2', '8', '3', '0'),
  YB_PG_INVALID_NAME = YB_PG_MAKE_SQLSTATE('4', '2', '6', '0', '2'),
  YB_PG_NAME_TOO_LONG = YB_PG_MAKE_SQLSTATE('4', '2', '6', '2', '2'),
  YB_PG_RESERVED_NAME = YB_PG_MAKE_SQLSTATE('4', '2', '9', '3', '9'),
  YB_PG_DATATYPE_MISMATCH = YB_PG_MAKE_SQLSTATE('4', '2', '8', '0', '4'),
  YB_PG_INDETERMINATE_DATATYPE = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '1', '8'),
  YB_PG_COLLATION_MISMATCH = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '2', '1'),
  YB_PG_INDETERMINATE_COLLATION = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '2', '2'),
  YB_PG_WRONG_OBJECT_TYPE = YB_PG_MAKE_SQLSTATE('4', '2', '8', '0', '9'),
  YB_PG_GENERATED_ALWAYS = YB_PG_MAKE_SQLSTATE('4', '2', '8', 'C', '9'),
  YB_PG_UNDEFINED_COLUMN = YB_PG_MAKE_SQLSTATE('4', '2', '7', '0', '3'),
  YB_PG_UNDEFINED_CURSOR = YB_PG_MAKE_SQLSTATE('3', '4', '0', '0', '0'),
  YB_PG_UNDEFINED_DATABASE = YB_PG_MAKE_SQLSTATE('3', 'D', '0', '0', '0'),
  YB_PG_UNDEFINED_FUNCTION = YB_PG_MAKE_SQLSTATE('4', '2', '8', '8', '3'),
  YB_PG_UNDEFINED_PSTATEMENT = YB_PG_MAKE_SQLSTATE('2', '6', '0', '0', '0'),
  YB_PG_UNDEFINED_SCHEMA = YB_PG_MAKE_SQLSTATE('3', 'F', '0', '0', '0'),
  YB_PG_UNDEFINED_TABLE = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '0', '1'),
  YB_PG_UNDEFINED_PARAMETER = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '0', '2'),
  YB_PG_UNDEFINED_OBJECT = YB_PG_MAKE_SQLSTATE('4', '2', '7', '0', '4'),
  YB_PG_DUPLICATE_COLUMN = YB_PG_MAKE_SQLSTATE('4', '2', '7', '0', '1'),
  YB_PG_DUPLICATE_CURSOR = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '0', '3'),
  YB_PG_DUPLICATE_DATABASE = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '0', '4'),
  YB_PG_DUPLICATE_FUNCTION = YB_PG_MAKE_SQLSTATE('4', '2', '7', '2', '3'),
  YB_PG_DUPLICATE_PSTATEMENT = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '0', '5'),
  YB_PG_DUPLICATE_SCHEMA = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '0', '6'),
  YB_PG_DUPLICATE_TABLE = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '0', '7'),
  YB_PG_DUPLICATE_ALIAS = YB_PG_MAKE_SQLSTATE('4', '2', '7', '1', '2'),
  YB_PG_DUPLICATE_OBJECT = YB_PG_MAKE_SQLSTATE('4', '2', '7', '1', '0'),
  YB_PG_AMBIGUOUS_COLUMN = YB_PG_MAKE_SQLSTATE('4', '2', '7', '0', '2'),
  YB_PG_AMBIGUOUS_FUNCTION = YB_PG_MAKE_SQLSTATE('4', '2', '7', '2', '5'),
  YB_PG_AMBIGUOUS_PARAMETER = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '0', '8'),
  YB_PG_AMBIGUOUS_ALIAS = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '0', '9'),
  YB_PG_INVALID_COLUMN_REFERENCE = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '1', '0'),
  YB_PG_INVALID_COLUMN_DEFINITION = YB_PG_MAKE_SQLSTATE('4', '2', '6', '1', '1'),
  YB_PG_INVALID_CURSOR_DEFINITION = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '1', '1'),
  YB_PG_INVALID_DATABASE_DEFINITION = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '1', '2'),
  YB_PG_INVALID_FUNCTION_DEFINITION = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '1', '3'),
  YB_PG_INVALID_PSTATEMENT_DEFINITION = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '1', '4'),
  YB_PG_INVALID_SCHEMA_DEFINITION = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '1', '5'),
  YB_PG_INVALID_TABLE_DEFINITION = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '1', '6'),
  YB_PG_INVALID_OBJECT_DEFINITION = YB_PG_MAKE_SQLSTATE('4', '2', 'P', '1', '7'),

  /* Class 44 - WITH CHECK OPTION Violation */
  YB_PG_WITH_CHECK_OPTION_VIOLATION = YB_PG_MAKE_SQLSTATE('4', '4', '0', '0', '0'),

  /* Class 53 - Insufficient Resources */
  YB_PG_INSUFFICIENT_RESOURCES = YB_PG_MAKE_SQLSTATE('5', '3', '0', '0', '0'),
  YB_PG_DISK_FULL = YB_PG_MAKE_SQLSTATE('5', '3', '1', '0', '0'),
  YB_PG_OUT_OF_MEMORY = YB_PG_MAKE_SQLSTATE('5', '3', '2', '0', '0'),
  YB_PG_TOO_MANY_CONNECTIONS = YB_PG_MAKE_SQLSTATE('5', '3', '3', '0', '0'),
  YB_PG_CONFIGURATION_LIMIT_EXCEEDED = YB_PG_MAKE_SQLSTATE('5', '3', '4', '0', '0'),

  /* Class 54 - Program Limit Exceeded */
  YB_PG_PROGRAM_LIMIT_EXCEEDED = YB_PG_MAKE_SQLSTATE('5', '4', '0', '0', '0'),
  YB_PG_STATEMENT_TOO_COMPLEX = YB_PG_MAKE_SQLSTATE('5', '4', '0', '0', '1'),
  YB_PG_TOO_MANY_COLUMNS = YB_PG_MAKE_SQLSTATE('5', '4', '0', '1', '1'),
  YB_PG_TOO_MANY_ARGUMENTS = YB_PG_MAKE_SQLSTATE('5', '4', '0', '2', '3'),

  /* Class 55 - Object Not In Prerequisite State */
  YB_PG_OBJECT_NOT_IN_PREREQUISITE_STATE = YB_PG_MAKE_SQLSTATE('5', '5', '0', '0', '0'),
  YB_PG_OBJECT_IN_USE = YB_PG_MAKE_SQLSTATE('5', '5', '0', '0', '6'),
  YB_PG_CANT_CHANGE_RUNTIME_PARAM = YB_PG_MAKE_SQLSTATE('5', '5', 'P', '0', '2'),
  YB_PG_LOCK_NOT_AVAILABLE = YB_PG_MAKE_SQLSTATE('5', '5', 'P', '0', '3'),

  /* Class 57 - Operator Intervention */
  YB_PG_OPERATOR_INTERVENTION = YB_PG_MAKE_SQLSTATE('5', '7', '0', '0', '0'),
  YB_PG_QUERY_CANCELED = YB_PG_MAKE_SQLSTATE('5', '7', '0', '1', '4'),
  YB_PG_ADMIN_SHUTDOWN = YB_PG_MAKE_SQLSTATE('5', '7', 'P', '0', '1'),
  YB_PG_CRASH_SHUTDOWN = YB_PG_MAKE_SQLSTATE('5', '7', 'P', '0', '2'),
  YB_PG_CANNOT_CONNECT_NOW = YB_PG_MAKE_SQLSTATE('5', '7', 'P', '0', '3'),
  YB_PG_DATABASE_DROPPED = YB_PG_MAKE_SQLSTATE('5', '7', 'P', '0', '4'),

  /* Class 58 - System Error (errors external to PostgreSQL itself) */
  YB_PG_SYSTEM_ERROR = YB_PG_MAKE_SQLSTATE('5', '8', '0', '0', '0'),
  YB_PG_IO_ERROR = YB_PG_MAKE_SQLSTATE('5', '8', '0', '3', '0'),
  YB_PG_UNDEFINED_FILE = YB_PG_MAKE_SQLSTATE('5', '8', 'P', '0', '1'),
  YB_PG_DUPLICATE_FILE = YB_PG_MAKE_SQLSTATE('5', '8', 'P', '0', '2'),

  /* Class 72 - Snapshot Failure */
  YB_PG_SNAPSHOT_TOO_OLD = YB_PG_MAKE_SQLSTATE('7', '2', '0', '0', '0'),

  /* Class F0 - Configuration File Error */
  YB_PG_CONFIG_FILE_ERROR = YB_PG_MAKE_SQLSTATE('F', '0', '0', '0', '0'),
  YB_PG_LOCK_FILE_EXISTS = YB_PG_MAKE_SQLSTATE('F', '0', '0', '0', '1'),

  /* Class HV - Foreign Data Wrapper Error (SQL/MED) */
  YB_PG_FDW_ERROR = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', '0'),
  YB_PG_FDW_COLUMN_NAME_NOT_FOUND = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', '5'),
  YB_PG_FDW_DYNAMIC_PARAMETER_VALUE_NEEDED = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', '2'),
  YB_PG_FDW_FUNCTION_SEQUENCE_ERROR = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '1', '0'),
  YB_PG_FDW_INCONSISTENT_DESCRIPTOR_INFORMATION = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '2', '1'),
  YB_PG_FDW_INVALID_ATTRIBUTE_VALUE = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '2', '4'),
  YB_PG_FDW_INVALID_COLUMN_NAME = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', '7'),
  YB_PG_FDW_INVALID_COLUMN_NUMBER = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', '8'),
  YB_PG_FDW_INVALID_DATA_TYPE = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', '4'),
  YB_PG_FDW_INVALID_DATA_TYPE_DESCRIPTORS = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', '6'),
  YB_PG_FDW_INVALID_DESCRIPTOR_FIELD_IDENTIFIER = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '9', '1'),
  YB_PG_FDW_INVALID_HANDLE = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', 'B'),
  YB_PG_FDW_INVALID_OPTION_INDEX = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', 'C'),
  YB_PG_FDW_INVALID_OPTION_NAME = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', 'D'),
  YB_PG_FDW_INVALID_STRING_LENGTH_OR_BUFFER_LENGTH = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '9', '0'),
  YB_PG_FDW_INVALID_STRING_FORMAT = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', 'A'),
  YB_PG_FDW_INVALID_USE_OF_NULL_POINTER = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', '9'),
  YB_PG_FDW_TOO_MANY_HANDLES = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '1', '4'),
  YB_PG_FDW_OUT_OF_MEMORY = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', '1'),
  YB_PG_FDW_NO_SCHEMAS = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', 'P'),
  YB_PG_FDW_OPTION_NAME_NOT_FOUND = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', 'J'),
  YB_PG_FDW_REPLY_HANDLE = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', 'K'),
  YB_PG_FDW_SCHEMA_NOT_FOUND = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', 'Q'),
  YB_PG_FDW_TABLE_NOT_FOUND = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', 'R'),
  YB_PG_FDW_UNABLE_TO_CREATE_EXECUTION = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', 'L'),
  YB_PG_FDW_UNABLE_TO_CREATE_REPLY = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', 'M'),
  YB_PG_FDW_UNABLE_TO_ESTABLISH_CONNECTION = YB_PG_MAKE_SQLSTATE('H', 'V', '0', '0', 'N'),

  /* Class P0 - PL/pgSQL Error */
  YB_PG_PLPGSQL_ERROR = YB_PG_MAKE_SQLSTATE('P', '0', '0', '0', '0'),
  YB_PG_RAISE_EXCEPTION = YB_PG_MAKE_SQLSTATE('P', '0', '0', '0', '1'),
  YB_PG_NO_DATA_FOUND = YB_PG_MAKE_SQLSTATE('P', '0', '0', '0', '2'),
  YB_PG_TOO_MANY_ROWS = YB_PG_MAKE_SQLSTATE('P', '0', '0', '0', '3'),
  YB_PG_ASSERT_FAILURE = YB_PG_MAKE_SQLSTATE('P', '0', '0', '0', '4'),

  /* Class XX - Internal Error */
  YB_PG_INTERNAL_ERROR = YB_PG_MAKE_SQLSTATE('X', 'X', '0', '0', '0'),
  YB_PG_DATA_CORRUPTED = YB_PG_MAKE_SQLSTATE('X', 'X', '0', '0', '1'),
  YB_PG_INDEX_CORRUPTED = YB_PG_MAKE_SQLSTATE('X', 'X', '0', '0', '2'),
};

#undef YB_PG_MAKE_SQLSTATE
#undef YB_PGSIXBIT

inline std::string ToString(YBPgErrorCode code) {
  std::string result;
  result.resize(5);
  uint32_t u32_code = static_cast<uint32_t>(code);
  for (int i = 0; i < 5; ++i) {
    result[i] = '0' + ((u32_code >> (i * 6)) & 0x3f);
  }
  return result;
}

}  // namespace yb
