FROM centos:7

# User and group id
ARG UID=1000
ARG GID=1000

# Setup environment
ENV PGVERSION=14
ENV PGBIN=/usr/pgsql-${PGVERSION}/bin
ENV PGDATA="/var/lib/pgsql/${PGVERSION}/data"
ENV PATH="${PATH}:${PGBIN}"

# Install packages
RUN yum install -y centos-release-scl-rh epel-release
RUN yum install -y sudo

# Create postgres user/group with specific IDs
RUN groupadd -g $GID -o postgres
RUN useradd -m -u $UID -g $GID -o -s /bin/bash postgres

# Install PostgreSQL
RUN rpm --import http://yum.postgresql.org/RPM-GPG-KEY-PGDG
RUN rpm -ivh https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
# Enable PG14 repo (can be removed after the official release)
RUN yum-config-manager --enable pgdg14-updates-testing
RUN yum install -y postgresql${PGVERSION?}-server postgresql${PGVERSION?}-devel postgresql${PGVERSION?}-contrib \
                   make gcc openssl-devel llvm-toolset-7-clang llvm5.0

# Create PostgreSQL cluster
RUN sudo -u postgres ${PGBIN?}/initdb -A trust -k ${PGDATA?}
RUN echo "shared_preload_libraries = 'pgaudit'" >> ${PGDATA?}/postgresql.conf

# Configure sudo
RUN echo 'postgres ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

USER postgres
