#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for catalog/yb_logical_client
#
# IDENTIFICATION
#    src/backend/catalog/yb_logical_client/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/catalog/yb_logical_client
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = yb_logical_client_version.o

include $(top_srcdir)/src/backend/common.mk
