find_path(AWS_CPP_SDK_INCLUDE_DIR aws
  NO_CMAKE_SYSTEM_PATH
  NO_SYSTEM_ENVIRONMENT_PATH)
find_library(AWS_CPP_SDK_ROUTE53_SHARED_LIB aws-cpp-sdk-route53
  NO_CMAKE_SYSTEM_PATH
  NO_SYSTEM_ENVIRONMENT_PATH)
find_library(AWS_CPP_SDK_ROUTE53_STATIC_LIB libaws-cpp-sdk-route53.a
  NO_CMAKE_SYSTEM_PATH
  NO_SYSTEM_ENVIRONMENT_PATH)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(AWS_CPP_SDK REQUIRED_VARS
  AWS_CPP_SDK_ROUTE53_SHARED_LIB
  AWS_CPP_SDK_ROUTE53_STATIC_LIB
  AWS_CPP_SDK_INCLUDE_DIR)
