notifications:
    commits:      commits@age.apache.org
    pullrequests: commits@age.apache.org

github:
  description: "Graph database optimized for fast analysis and real-time data processing. 
     It is provided as an extension to PostgreSQL."
  homepage: https://age.apache.org
  labels:
    - postgresql
    - graph-database
    - analytics
    - postgresql-extension
    - graphdb
    - multi-model-dbms
    - agensgraph
    - age-database
  features:
    wiki: true
    issues: true
    projects: true
    discussions: true

  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  true
