# Copyright (c) Yugabyte, Inc.
#
# To analyze (without uploading to Fossa) -- for local debugging:
# fossa analyze --debug --output
#
# To analyze and upload dependencies:
# fossa analyze --debug

version: 3

project:
  id: yugabyte-db

revision:
  branch: master

paths:
  only:
    - ./src
    - ./java
  exclude:
    - ./src/postgres/src/bin/pg_test_fsync
    - ./src/postgres/src/bin/pg_test_timing
    - ./src/postgres/src/interfaces/ecpg/test
    - ./src/postgres/src/interfaces/libpq/test
    - ./src/postgres/src/test
    - ./src/yb/integration-tests
    - ./src/yb/yql/cql/ql/test
    - ./java/yb-client/src/test
    - ./java/yb-cql-4x/src/test
    - ./java/yb-cql/src/test
    - ./java/yb-jedis-tests
    - ./java/yb-loadtester/src/test
    - ./java/yb-multiapi/src/test
    - ./java/yb-pgsql/src/test
