ALTER FUNCTION oracle.btrim(char) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(char, char) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(char, text) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(char, oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(char, oracle.nvarchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(text) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(text, char) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(text, text) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(text, oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(text, oracle.nvarchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(oracle.varchar2, char) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(oracle.varchar2, text) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(oracle.varchar2, oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(oracle.varchar2, oracle.nvarchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(oracle.nvarchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(oracle.nvarchar2, char) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(oracle.nvarchar2, text) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(oracle.nvarchar2, oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.btrim(oracle.nvarchar2, oracle.nvarchar2) PARALLEL SAFE;

ALTER FUNCTION oracle.ltrim(char, char) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(char, text) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(char, oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(char, oracle.nvarchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(char) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(text, char) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(text, text) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(text, oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(text, oracle.nvarchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(text) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(oracle.varchar2, char) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(oracle.varchar2, text) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(oracle.varchar2, oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(oracle.varchar2, oracle.nvarchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(oracle.nvarchar2, char) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(oracle.nvarchar2, text) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(oracle.nvarchar2, oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(oracle.nvarchar2, oracle.nvarchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.ltrim(oracle.nvarchar2) PARALLEL SAFE;

ALTER FUNCTION oracle.rtrim(char, char) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(char, text) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(char, oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(char, oracle.nvarchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(char) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(text, char) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(text, text) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(text, oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(text, oracle.nvarchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(text) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(oracle.varchar2, char) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(oracle.varchar2, text) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(oracle.varchar2, oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(oracle.varchar2, oracle.nvarchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(oracle.nvarchar2, char) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(oracle.nvarchar2, text) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(oracle.nvarchar2, oracle.varchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(oracle.nvarchar2, oracle.nvarchar2) PARALLEL SAFE;
ALTER FUNCTION oracle.rtrim(oracle.nvarchar2) PARALLEL SAFE;