#!/bin/bash
set -e
if [[ -z "$DEVOPS_HOME" ]]; then
  echo "ERROR: DEVOPS_HOME not set" >&2
  exit 1
fi

if [[ $OSTYPE =~ ^darwin ]]; then
  echo "ERROR: Server tarball is only expected to be built on CentOS7."
  exit 1
fi

. "$DEVOPS_HOME/bin/"/common.sh
activate_virtualenv
"$( dirname "${BASH_SOURCE[0]}" )"/build-support/yb_release.py "$@"
