#!/bin/bash
#
# Copyright (c) YugaByte, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.  See the License for the specific language governing permissions and limitations
# under the License.
#
set -euo pipefail
. ${BASH_SOURCE%/*}/build-support/common-build-env.sh

if [[ -z ${DEVOPS_HOME-} ]]; then
  devops_home_candidate=$YB_SRC_ROOT/../devops
  if [[ -d $devops_home_candidate ]]; then
    DEVOPS_HOME=$devops_home_candidate
  else
    echo "ERROR: DEVOPS_HOME not set, and not found at '$devops_home_candidate'" >&2
    exit 1
  fi
fi

if [[ $OSTYPE =~ ^darwin ]]; then
  echo "ERROR: Server tarball is only expected to be built on CentOS7."
  exit 1
fi

. "$DEVOPS_HOME/bin/common.sh"
activate_virtualenv

export PYTHONPATH=$YB_SRC_ROOT/python:$PYTHONPATH
"$YB_SRC_ROOT"/build-support/yb_release.py "$@"
