#!/usr/bin/env bash
#
# Copyright (c) YugaByte, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.  See the License for the specific language governing permissions and limitations
# under the License.
#
set -euo pipefail
. "${BASH_SOURCE%/*}/common-build-env.sh"
. "${BASH_SOURCE%/*}/common-test-env.sh"

if [[ -z ${YB_BUILD_ROOT:-} ]]; then
  fatal "YB_BUILD_ROOT must be set"
fi
export BUILD_ROOT=$YB_BUILD_ROOT
predefined_build_root=${YB_BUILD_ROOT}
handle_predefined_build_root

activate_virtualenv
set_sanitizer_runtime_options

set_pythonpath
"$YB_SRC_ROOT"/python/yb/build_postgres.py "$@"
