# Copyright (c) YugaByte, Inc.

n1-standard-1:
  numCores: 1
  memSizeGB: 3.75
  volumeCount: 2
  volumeSizeGB: 16
  volumeType: SSD
n1-standard-8:
  numCores: 8
  memSizeGB: 30
  volumeCount: 2
  volumeSizeGB: 16
  volumeType: SSD
n1-standard-16:
  numCores: 16
  memSizeGB: 60
  volumeCount: 2
  volumeSizeGB: 16
  volumeType: SSD
n1-standard-32:
  numCores: 32
  memSizeGB: 120
  volumeCount: 2
  volumeSizeGB: 16
  volumeType: SSD
n1-highmem-4:
  numCores: 4
  memSizeGB: 26
  volumeCount: 2
  volumeSizeGB: 16
  volumeType: SSD
n1-highmem-8:
  numCores: 8
  memSizeGB: 52
  volumeCount: 2
  volumeSizeGB: 16
  volumeType: SSD
n1-highmem-16:
  numCores: 16
  memSizeGB: 104
  volumeCount: 2
  volumeSizeGB: 16
  volumeType: SSD
n1-highmem-32:
  numCores: 32
  memSizeGB: 208
  volumeCount: 2
  volumeSizeGB: 16
  volumeType: SSD
