// Copyright (c) YugabyteDB, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied.  See the License for the specific language governing permissions and limitations
// under the License.
//

#include "yb/gen_yrpc/proxy_generator.h"

#include <google/protobuf/descriptor.h>

#include "yb/gen_yrpc/metric_descriptor.h"
#include "yb/gen_yrpc/model.h"

namespace yb {
namespace gen_yrpc {

namespace {

std::vector<MetricDescriptor> outbound_metrics = {
  {
    .name = "request_bytes",
    .prefix = "proxy_",
    .kind = "counter",
    .extra_args = "",
    .units = "yb::MetricUnit::kBytes",
    .description = "Bytes sent by",
  },
  {
    .name = "response_bytes",
    .prefix = "proxy_",
    .kind = "counter",
    .extra_args = "",
    .units = "yb::MetricUnit::kBytes",
    .description = "Bytes received in response to",
  },
};

void DeclareMethod(YBPrinter printer, const std::string& type_prefix) {
  ScopedIndent indent(printer);
  printer(
      "\n"
      "::yb::Status $rpc_name$(\n"
      "    const $" + type_prefix + "request$ &req,\n"
      "    $" + type_prefix + "response$ *resp,\n"
      "    ::yb::rpc::RpcController *controller) const;\n"
      "void $rpc_name$Async(\n"
      "    const $" + type_prefix + "request$ &req,\n"
      "    $" + type_prefix + "response$ *response,\n"
      "    ::yb::rpc::RpcController *controller,\n"
      "    ::yb::rpc::ResponseCallback callback) const;\n"
  );
}

// Drains the request's trace-tagged fields onto the pending-attr buffer, which the outbound call's
// span consumes when it is created. No-op unless there is an active context to consume them.
const std::string kTraceAttrs =
    "  if (::yb::dist_trace::HasActiveContext()) {\n"
    "    for (auto& p : req.TracingAttributes()) {\n"
    "      ::yb::dist_trace::AddPendingRpcStringAttr(std::move(p.first), std::move(p.second));\n"
    "    }\n"
    "  }\n";

const std::string kPbTraceAttrs =
    "  if (::yb::dist_trace::HasActiveContext()) {\n"
    "    for (auto& p : TracingAttributes(req)) {\n"
    "      ::yb::dist_trace::AddPendingRpcStringAttr(std::move(p.first), std::move(p.second));\n"
    "    }\n"
    "  }\n";

void DefineMethod(YBPrinter printer, const std::string& type_prefix, const std::string& trace) {
  printer(
      "::yb::Status $service_name$Proxy::$rpc_name$(\n"
      "    const $" + type_prefix + "request$ &req, $" + type_prefix +
          "response$ *resp, ::yb::rpc::RpcController *controller) const {\n"
      "  static ::yb::rpc::RemoteMethod method(\"$full_service_name$\", \"$rpc_name$\");\n" +
      trace +
      "  return proxy().SyncRequest(\n"
      "      &method, metrics<$service_method_count$>(static_cast<size_t>("
          "$service_method_enum$::$metric_enum_key$)), req, resp, controller, "
          "$send_metadata$);\n"
      "}\n"
      "\n"
      "void $service_name$Proxy::$rpc_name$Async(\n"
      "    const $" + type_prefix + "request$ &req, $" + type_prefix +
          "response$ *resp, ::yb::rpc::RpcController *controller,\n"
      "    ::yb::rpc::ResponseCallback callback) const {\n"
      "  static ::yb::rpc::RemoteMethod method(\"$full_service_name$\", \"$rpc_name$\");\n" +
      trace +
      "  proxy().AsyncRequest(\n"
      "      &method, metrics<$service_method_count$>(static_cast<size_t>("
          "$service_method_enum$::$metric_enum_key$)), req, resp, controller, "
          "std::move(callback), $send_metadata$);\n"
      "}\n"
      "\n"
  );
}

// The .messages.h carries the lightweight message classes and the pb_ trace free functions. The
// proxy needs it when any proxy method is lightweight, or when any request has trace-tagged fields
// (so the pb_ stub can call the generated TracingAttributes(req) free function).
bool ProxyNeedsMessages(const google::protobuf::FileDescriptor* file) {
  if (HasLightweightMethod(file, rpc::RpcSides::PROXY)) {
    return true;
  }
  for (int s = 0; s < file->service_count(); ++s) {
    const auto* service = file->service(s);
    for (int m = 0; m < service->method_count(); ++m) {
      if (MessageHasTracingAttributes(service->method(m)->input_type())) {
        return true;
      }
    }
  }
  return false;
}

} // namespace

ProxyGenerator::ProxyGenerator(bool need_messages) : need_messages_(need_messages) {}

void ProxyGenerator::Header(YBPrinter printer, const google::protobuf::FileDescriptor *file) {
  printer(
      "// THIS FILE IS AUTOGENERATED FROM $path$\n"
      "\n"
      "#pragma once\n"
      "\n"
      "#include \"$path_no_extension$.pb.h\"\n"
  );

  if (need_messages_ && ProxyNeedsMessages(file)) {
    printer("#include \"$path_no_extension$.messages.h\"\n");
  }

  printer(
    "\n"
      "#include \"yb/rpc/proxy.h\"\n"
      "#include \"yb/util/status.h\"\n"
      "#include \"yb/util/net/net_fwd.h\"\n"
      "\n"
      "namespace yb {\n"
      "namespace rpc {\n"
      "class Proxy;\n"
      "}\n"
      "}\n"
      "\n"
      "$open_namespace$"
      "\n"
      "\n"
  );

  for (int service_idx = 0; service_idx < file->service_count(); ++service_idx) {
    const auto* service = file->service(service_idx);
    ScopedSubstituter service_subs(printer, service);

    printer(
        "class $service_name$Proxy : public ::yb::rpc::ProxyBase {\n"
        " public:\n"
        "  $service_name$Proxy(\n"
        "      ::yb::rpc::ProxyCache* cache, const ::yb::HostPort& remote,\n"
        "      const ::yb::rpc::Protocol* protocol = nullptr,\n"
        "      const ::yb::MonoDelta& resolve_cache_timeout = ::yb::MonoDelta());\n"
    );

    for (int method_idx = 0; method_idx < service->method_count(); ++method_idx) {
      const auto* method = service->method(method_idx);
      ScopedSubstituter method_subs(printer, method, rpc::RpcSides::PROXY);

      DeclareMethod(printer, "pb_");
      if (IsLightweightMethod(method, rpc::RpcSides::PROXY)) {
        DeclareMethod(printer, "lw_");
      }
    }

    printer("};\n\n");
  }

  printer(
      "$close_namespace$"
  );
}

void ProxyGenerator::Source(YBPrinter printer, const google::protobuf::FileDescriptor *file) {
  printer(
      "// THIS FILE IS AUTOGENERATED FROM $path$\n"
      "\n"
      "#include \"$path_no_extension$.proxy.h\"\n"
      "\n"
      "#include \"$path_no_extension$.service.h\"\n\n"
      "#include \"yb/rpc/proxy.h\"\n"
      "#include \"yb/rpc/outbound_call.h\"\n"
      "#include \"yb/util/dist_trace.h\"\n"
      "#include \"yb/util/metrics.h\"\n"
      "#include \"yb/util/net/sockaddr.h\"\n"
      "\n"
  );

  GenerateMetricDefines(printer, file, outbound_metrics);

  printer(
      "$open_namespace$\n\n"
      "namespace {\n\n"
  );

  for (int service_idx = 0; service_idx < file->service_count(); ++service_idx) {
    const auto* service = file->service(service_idx);
    ScopedSubstituter service_subs(printer, service);
    printer("const std::string kFull$service_name$Name = \"$original_full_service_name$\";\n\n");

    printer(
        "::yb::rpc::ProxyMetricsPtr Create$service_name$Metrics("
            "const scoped_refptr<MetricEntity>& entity) {\n"
        "  auto result = std::make_shared<"
            "::yb::rpc::ProxyMetricsImpl<$service_method_count$>>();\n"
    );

    GenerateMethodAssignments(
        printer, service,
        "result->value[std::to_underlying($service_method_enum$::$metric_enum_key$)]",
        false, outbound_metrics);

    printer(
        "  return result;\n}\n\n"
    );
  }

  printer(
      "\n} // namespace\n\n"
  );

  for (int service_idx = 0; service_idx < file->service_count(); ++service_idx) {
    const auto* service = file->service(service_idx);
    ScopedSubstituter service_subs(printer, service);

    printer(
        "$service_name$Proxy::$service_name$Proxy(\n"
        "    ::yb::rpc::ProxyCache* cache, const ::yb::HostPort& remote,\n"
        "    const ::yb::rpc::Protocol* protocol,\n"
        "    const ::yb::MonoDelta& resolve_cache_timeout)\n"
        "    : ProxyBase(kFull$service_name$Name, &Create$service_name$Metrics,\n"
        "                cache, remote, protocol, resolve_cache_timeout) {}\n\n"
    );

    for (int method_idx = 0; method_idx < service->method_count(); ++method_idx) {
      const auto* method = service->method(method_idx);
      ScopedSubstituter method_subs(printer, method, rpc::RpcSides::PROXY);

      // The pb_ drain calls a TracingAttributes() free function from the .messages.h, which only
      // exists when this file generates messages; without it the pb_ path stays untraced.
      const bool trace = MessageHasTracingAttributes(method->input_type());
      DefineMethod(printer, "pb_", need_messages_ && trace ? kPbTraceAttrs : "");
      if (IsLightweightMethod(method, rpc::RpcSides::PROXY)) {
        DefineMethod(printer, "lw_", trace ? kTraceAttrs : "");
      }
    }
  }

  printer("$close_namespace$");
}

} // namespace gen_yrpc
} // namespace yb
