version: '2'

services:
  yugaware:
    image: quay.io/yugabyte/yugaware:latest 
    volumes:
      - $HOME/.yugabyte:/root/.yugabyte
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/bin/docker:/usr/bin/docker
      - /etc/yugaware
      - /opt/yugabyte
    expose:
      - 9000
    ports:
      - 9000:9000
    environment:
      - JVM_OPTS=-XX:PermSize=1024m -XX:MaxPermSize=1024m
    depends_on:
      - postgres
    links:
      - postgres
    network_mode: bridge

  yugaware-ui:
    image: quay.io/yugabyte/yugaware-ui:latest
    expose:
      - 4000
    ports:
      - 4000:4000
    network_mode: bridge
  
  yugabyte-docs:
    image: quay.io/yugabyte/docs:latest
    expose: 
      - 1313
    ports:
      - 1313:1313
    network_mode: bridge

  yugabyte-base:
    image: quay.io/yugabyte/base-image:latest

  postgres:
    image: postgres:latest
    expose:
      - 5432
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=yugaware
      - POSTGRES_PASSWORD=yugaware
      - POSTGRES_DB=yugaware
    volumes:
      - /var/lib/postgresql/data
    network_mode: bridge

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
    links:
      - yugaware
      - yugaware-ui
      - yugabyte-docs
    ports:
      - "80:80"
    expose:
      - 80
    network_mode: bridge

  prometheus:
    image: prom/prometheus:v1.5.2
    volumes_from:
      - yugaware
    command:
      - '-config.file=/etc/yugaware/prometheus/prometheus.yml'
      - '-storage.local.path=/opt/yugabyte/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    depends_on:
      - yugaware
    network_mode: bridge

  node-exporter:
    image: prom/node-exporter:v0.13.0
    expose:
      - 9100
    ports:
      - 9100:9100
    network_mode: bridge

  alertmanager:
    image: prom/alertmanager:v0.5.1
    ports:
      - 9093:9093
    volumes_from:
      - yugaware
    depends_on:
      - yugaware
    command:
      - '-config.file=/etc/yugaware/alertmanager/alertmanager.yml'
      - '-storage.path=/opt/yugabyte/alertmanager'
    network_mode: bridge

