version: '2'

services:
  yugaware:
    image: yugaware:1.0-SNAPSHOT
    volumes:
      - $HOME/.yugabyte:/root/.yugabyte
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/bin/docker:/usr/bin/docker
    expose:
      - 9000
    ports:
      - 9000:9000
    environment:
      - JVM_OPTS=-XX:PermSize=1024m -XX:MaxPermSize=1024m
    depends_on:
      - postgres
    volumes_from:
      - prometheus
    links:
      - postgres
    network_mode: bridge

  yugaware-ui:
    image: yugaware-ui:latest
    expose:
      - 4000
    ports:
      - 4000:4000
    network_mode: bridge

  postgres:
    image: postgres:latest
    expose:
      - 5432
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=yugaware
      - POSTGRES_PASSWORD=yugaware
      - POSTGRES_DB=yugaware
    volumes:
      - /var/lib/postgresql/data
    network_mode: bridge

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
    links:
      - yugaware
      - yugaware-ui
    ports:
      - "80:80"
    expose:
      - 80
    network_mode: bridge

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus/:/etc/prometheus
      - /etc/prometheus/tgroups
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=./docker/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    network_mode: bridge

  node-exporter:
    image: prom/node-exporter
    expose:
      - 9100
    ports:
      - 9100:9100
    network_mode: bridge

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./docker/alertmanager/:/etc/alertmanager/
    command:
      - '-config.file=/etc/alertmanager/alertmanager.yml'
      - '-storage.path=./docker/alertmanager'
    network_mode: bridge

