// Copyright (c) YugaByte, Inc.

= Yugaware Developer Documentation

== Building and running Yugaware locally

Pre-requisites - install sbt and postgres:
[source,bash]
----
# On a mac, run the following:
$ brew install sbt
# Note: do not set any password for postgres.
$ brew install postgres
# Make postgres a daemon (restart on machine restart).
$ ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
$ launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

# Create user and database
$ createuser root
$ createdb yugaware
----

# On Ubuntu, follow these steps. First install sbt:
Based on http://www.scala-sbt.org/release/docs/Installing-sbt-on-Linux.html
[source,bash]
----
$ echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
$ sudo apt-get update
$ sudo apt-get install sbt

# Create user and yugaware db in PostgreSQL:
# Follow all the steps on http://tecadmin.net/install-postgresql-server-on-ubuntu/
# Then do the following to ensure that we can connect to "yugaware" db as "root" user.
$ sudo -u postgres createuser -s root
$ sudo -u postgres createdb yugaware
$ sudo -u root psql -d yugaware
yugaware=> \conninfo
You are connected to database "yugaware" as user "root" via socket in "/var/run/postgresql" at port "5432".
-- Just press enter to skip setting an actual password (it will be an empty string).
yugaware=> \password
Enter new password: 
Enter it again: 
yugaware=> \q
----

Needs AWS auth credentials to run. Make sure no quotes around the keys!
[source,bash]
----
cat > ~/.sbt/.s3credentials
accessKey = <user's access key>
secretKey = <user's secret key>
----

To compile and run the code:
[source,bash]
----
$ sbt run
----
Test that everything is running by going to http://localhost:9000 in a browser (or curl).

To compile and not run:
[source,bash]
----
$ sbt compile
----

To run the unit tests:
[source,bash]
----
$ sbt test
----

If there are any unresolved symbols or compilation issues, try the following to create a clean slate and then retry running.
[source,bash]
----
$ sbt clean
----

== Developing Yugaware in Eclipse

Eclipse can be used as an IDE for Yugaware. To generate Eclipse project files, do:

[source,bash]
----
# Create the sbt plugins directory for your local machine.
$ mkdir ~/.sbt/0.13/plugins/

# Create a file ~/.sbt/0.13/plugins/build.sbt with the contents shown below.
$ cat > ~/.sbt/0.13/plugins/build.sbt
resolvers += Classpaths.typesafeResolver
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")

# Install the plugin
$ cd ~/.sbt/0.13/plugins
# Run the following to ensure that the sbt shell works.
$ sbt

# Go to the yugaware directory and create the eclipse project files.
$ cd yugaware
$ sbt eclipse

# Fix the classpath for eclipse.
bin/activator eclipse
----

Now there should be an Eclipse '.project' file generated. Go to Eclipse and import it using:
File -> Import -> General -> Existing Projects into Workspace
Hit next, and browse to the Yugaware source directory for the project to get imported.
