#!/bin/bash
# Copyright (c) YugaByte, Inc.

YW_REPO="$( dirname "${BASH_SOURCE[0]}" )"
. "$YW_REPO"/common_itest
echo "Done installing cassandra-driver, running integration test now..."
"$YW_REPO"/src/itest/itest.py "$@"
