#!/bin/bash
# Copyright (c) YugaByte, Inc.
set -euo pipefail

export DEVOPS_HOME="${BASH_SOURCE%/*}"/devops

. "$DEVOPS_HOME/bin/"/common.sh

"$DEVOPS_HOME/bin/install_python_requirements.sh"

activate_virtualenv
"$( dirname "${BASH_SOURCE[0]}" )"/yb_release.py "$@"
