#!/bin/bash
# Copyright (c) YugaByte, Inc.
set -euo pipefail

export DEVOPS_HOME="${BASH_SOURCE%/*}"/devops
export YB_MANAGED_DEVOPS_USE_PYTHON3=1

. "$DEVOPS_HOME/bin/"/common.sh

# Use dynamic paths to shorten shebangs below 64 characters.
"$DEVOPS_HOME/bin/install_python_requirements.sh" --use_dynamic_paths

activate_virtualenv
"$( dirname "${BASH_SOURCE[0]}" )"/yb_release.py "$@"
