name: postgresql-11-ppg-package
on: [push]

jobs:
  build:
    name: pg-11-ppg-package-test
    runs-on: ubuntu-20.04
    steps:
      - name: Clone pg_stat_monitor repository
        uses: actions/checkout@v2
        with:
          path: 'src/pg_stat_monitor'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt purge postgresql-client-common postgresql-common \
            postgresql postgresql*
          sudo apt-get install -y libreadline6-dev systemtap-sdt-dev \
            zlib1g-dev libssl-dev libpam0g-dev python3-dev bison flex \
            libipc-run-perl wget
          sudo rm -rf /var/lib/postgresql /var/log/postgresql /etc/postgresql \
            /usr/lib/postgresql /usr/include/postgresql /usr/share/postgresql \
            /etc/postgresql
          sudo rm -f /usr/bin/pg_config

      - name: Install percona-release script
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get install -y wget gnupg2 curl lsb-release
          sudo wget \
            https://repo.percona.com/apt/percona-release_latest.generic_all.deb
          sudo dpkg -i percona-release_latest.generic_all.deb

      - name: Install Percona Distribution Postgresql 11
        run: |
          sudo percona-release setup ppg-11
          sudo apt-get update -y
          sudo apt-get install -y percona-postgresql-11 \
            percona-postgresql-contrib percona-postgresql-server-dev-all

      - name: Change src owner to postgres
        run: |
          sudo chown -R postgres:postgres src

      - name: Build pg_stat_monitor
        run: |
          sudo -u postgres bash -c 'make USE_PGXS=1'
          sudo make USE_PGXS=1 install
        working-directory: src/pg_stat_monitor

      - name: Start pg_stat_monitor_tests
        run: |
          sudo service postgresql stop
          echo "shared_preload_libraries = 'pg_stat_monitor'" | 
            sudo tee -a /etc/postgresql/11/main/postgresql.conf
          sudo service postgresql start
          sudo psql -V
          export PG_TEST_PORT_DIR=/home/postgres
          sudo -u postgres bash -c 'make installcheck USE_PGXS=1'
        working-directory: src/pg_stat_monitor

      - name: Report on test fail
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: Regressions diff and postgresql log
          path: |
            src/pg_stat_monitor/regression.diffs
            src/pg_stat_monitor/logfile
          retention-days: 3
