name: postgresql-11-pgdg-package
on: [pull_request]

jobs:
  build:
    name: pg-11-pgdg-package-test
    runs-on: ubuntu-20.04
    steps:
      - name: Clone pg_stat_monitor repository
        uses: actions/checkout@v2
        with:
          path: 'src/pg_stat_monitor'

      - name: Delete old postgresql files
        run: |
          sudo apt-get update
          sudo apt purge postgresql-client-common postgresql-common \
            postgresql postgresql*
          sudo rm -rf /var/lib/postgresql /var/log/postgresql /etc/postgresql \
            /usr/lib/postgresql /usr/include/postgresql /usr/share/postgresql \
            /etc/postgresql
          sudo rm -f /usr/bin/pg_config

      - name: Install PG Distribution Postgresql 11
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt \
            $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo wget --quiet -O - \
            https://www.postgresql.org/media/keys/ACCC4CF8.asc |
            sudo apt-key add -
          sudo apt-get -y update
          sudo apt-get -y install postgresql-11 postgresql-server-dev-11

      - name: Change src owner to postgres
        run: |
          sudo chown -R postgres:postgres src

      - name: Build pg_stat_monitor
        run: |
          sudo -u postgres bash -c 'make USE_PGXS=1'
          sudo make USE_PGXS=1 install
        working-directory: src/pg_stat_monitor

      - name: Start pg_stat_monitor_tests
        run: |
          sudo service postgresql stop
          echo "shared_preload_libraries = 'pg_stat_monitor'" |
            sudo tee -a /etc/postgresql/11/main/postgresql.conf
          sudo service postgresql start
          sudo psql -V
          export PG_TEST_PORT_DIR=/home/postgres
          sudo -u postgres bash -c 'make installcheck USE_PGXS=1'
        working-directory: src/pg_stat_monitor

      - name: Report on test fail
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: Regressions diff and postgresql log
          path: |
            src/pg_stat_monitor/regression.diffs
            src/pg_stat_monitor/logfile
          retention-days: 3
