# Copyright 2019 YugabyteDB, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- block:
  - assert:
      that:
        - cloud_type is defined
        - device_names is defined
        - mount_points is defined
        - lun_indexes is defined

  - name: Install the script for discovering, updating fstab for & mounting ephemeral drives.
    become: yes
    become_method: sudo
    vars:
      # Ansible variable rules are weird..
      device_paths: "{{ device_names | list | join(' ') }}"
      mount_paths: "{{ mount_points.split(',') | join(' ') }}"
      disk_lun_indexes: "{{ lun_indexes.split(',') | join(' ') }}"
    template:
      src: mount_ephemeral_drives.sh.j2
      dest: /usr/local/bin/mount_ephemeral_drives.sh
      owner: root
      mode: 0755
  when: ansible_os_family != "Darwin"
