package models
// TaskTypeEnum : The type of task
type TaskTypeEnum string

// List of TaskTypeEnum
const (
	TASKTYPEENUM_CREATE_CLUSTER TaskTypeEnum = "CREATE_CLUSTER"
	TASKTYPEENUM_EDIT_CLUSTER TaskTypeEnum = "EDIT_CLUSTER"
	TASKTYPEENUM_DELETE_CLUSTER TaskTypeEnum = "DELETE_CLUSTER"
	TASKTYPEENUM_EDIT_ALLOW_LIST TaskTypeEnum = "EDIT_ALLOW_LIST"
	TASKTYPEENUM_CREATE_BACKUP TaskTypeEnum = "CREATE_BACKUP"
	TASKTYPEENUM_RESTORE_BACKUP TaskTypeEnum = "RESTORE_BACKUP"
	TASKTYPEENUM_MIGRATE_CLUSTER TaskTypeEnum = "MIGRATE_CLUSTER"
	TASKTYPEENUM_DELETE_PROJECT TaskTypeEnum = "DELETE_PROJECT"
	TASKTYPEENUM_UPGRADE_CLUSTER TaskTypeEnum = "UPGRADE_CLUSTER"
	TASKTYPEENUM_PAUSE_CLUSTER TaskTypeEnum = "PAUSE_CLUSTER"
	TASKTYPEENUM_RESUME_CLUSTER TaskTypeEnum = "RESUME_CLUSTER"
	TASKTYPEENUM_SETUP_XCLUSTER_REPLICATION TaskTypeEnum = "SETUP_XCLUSTER_REPLICATION"
)
