package models
// EventTypeEnum : The type of an event
type EventTypeEnum string

// List of EventTypeEnum
const (
	EVENTTYPEENUM_CREATE EventTypeEnum = "CREATE"
	EVENTTYPEENUM_EDIT EventTypeEnum = "EDIT"
	EVENTTYPEENUM_PAUSE EventTypeEnum = "PAUSE"
	EVENTTYPEENUM_RESUME EventTypeEnum = "RESUME"
	EVENTTYPEENUM_DELETE EventTypeEnum = "DELETE"
	EVENTTYPEENUM_ADD EventTypeEnum = "ADD"
	EVENTTYPEENUM_REMOVE EventTypeEnum = "REMOVE"
	EVENTTYPEENUM_RESTORE EventTypeEnum = "RESTORE"
	EVENTTYPEENUM_ACTIVATE EventTypeEnum = "ACTIVATE"
	EVENTTYPEENUM_CANCEL EventTypeEnum = "CANCEL"
	EVENTTYPEENUM_SCHEDULE EventTypeEnum = "SCHEDULE"
	EVENTTYPEENUM_TRIGGER EventTypeEnum = "TRIGGER"
	EVENTTYPEENUM_DELAY EventTypeEnum = "DELAY"
	EVENTTYPEENUM_UPGRADE EventTypeEnum = "UPGRADE"
)
