package models
// ResourceTypeEnum : The type of resource
type ResourceTypeEnum string

// List of ResourceTypeEnum
const (
	RESOURCETYPEENUM_CLUSTER ResourceTypeEnum = "CLUSTER"
	RESOURCETYPEENUM_ALLOW_LIST ResourceTypeEnum = "ALLOW_LIST"
	RESOURCETYPEENUM_BACKUP ResourceTypeEnum = "BACKUP"
	RESOURCETYPEENUM_BACKUP_SCHEDULE ResourceTypeEnum = "BACKUP_SCHEDULE"
	RESOURCETYPEENUM_ACCOUNT ResourceTypeEnum = "ACCOUNT"
	RESOURCETYPEENUM_USER ResourceTypeEnum = "USER"
	RESOURCETYPEENUM_PROJECT ResourceTypeEnum = "PROJECT"
	RESOURCETYPEENUM_BILLING ResourceTypeEnum = "BILLING"
	RESOURCETYPEENUM_PAYMENT ResourceTypeEnum = "PAYMENT"
	RESOURCETYPEENUM_TRACK ResourceTypeEnum = "TRACK"
	RESOURCETYPEENUM_MAINTENANCE_EVENT ResourceTypeEnum = "MAINTENANCE_EVENT"
	RESOURCETYPEENUM_VPC ResourceTypeEnum = "VPC"
	RESOURCETYPEENUM_VPC_PEERING ResourceTypeEnum = "VPC_PEERING"
	RESOURCETYPEENUM_MAINTENANCE_WINDOW ResourceTypeEnum = "MAINTENANCE_WINDOW"
	RESOURCETYPEENUM_MAINTENANCE_EXCLUSION ResourceTypeEnum = "MAINTENANCE_EXCLUSION"
)
