// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { useQuery, useInfiniteQuery, useMutation, UseQueryOptions, UseInfiniteQueryOptions, UseMutationOptions } from 'react-query';
import Axios from '../runtime';
import type { AxiosInstance } from 'axios';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import type {
  ApiError,
  UpdateGflagMaintenanceSpec,
} from '../models';

export interface UpdateGflagMaintenanceForQuery {
  accountId: string;
  projectId: string;
  clusterId: string;
  UpdateGflagMaintenanceSpec?: UpdateGflagMaintenanceSpec;
}

/**
 * API to set use_custom_gflags flag for a cluster\'s maintenance schedule
 * API to set use_custom_gflags flag for a cluster\'s maintenance schedule
 */


export const updateGflagMaintenanceMutate = (
  body: UpdateGflagMaintenanceForQuery,
  customAxiosInstance?: AxiosInstance
) => {
  const url = '/private/accounts/{accountId}/projects/{projectId}/clusters/{clusterId}/maintenance/schedule/gflags'.replace(`{${'accountId'}}`, encodeURIComponent(String(body.accountId))).replace(`{${'projectId'}}`, encodeURIComponent(String(body.projectId))).replace(`{${'clusterId'}}`, encodeURIComponent(String(body.clusterId)));
  // eslint-disable-next-line
  // @ts-ignore
  delete body.accountId;
  // eslint-disable-next-line
  // @ts-ignore
  delete body.projectId;
  // eslint-disable-next-line
  // @ts-ignore
  delete body.clusterId;
  return Axios<UpdateGflagMaintenanceSpec>(
    {
      url,
      method: 'POST',
      data: body.UpdateGflagMaintenanceSpec
    },
    customAxiosInstance
  );
};

export const useUpdateGflagMaintenanceMutation = <Error = ApiError>(
  options?: {
    mutation?:UseMutationOptions<UpdateGflagMaintenanceSpec, Error>,
    customAxiosInstance?: AxiosInstance;
  }
) => {
  const {mutation: mutationOptions, customAxiosInstance} = options ?? {};
  // eslint-disable-next-line
  // @ts-ignore
  return useMutation<UpdateGflagMaintenanceSpec, Error, UpdateGflagMaintenanceForQuery, unknown>((props) => {
    return  updateGflagMaintenanceMutate(props, customAxiosInstance);
  }, mutationOptions);
};





