// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { useQuery, useInfiniteQuery, useMutation, UseQueryOptions, UseInfiniteQueryOptions, UseMutationOptions } from 'react-query';
import Axios from '../runtime';
import type { AxiosInstance } from 'axios';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import type {
  ApiError,
  VersionInfo,
} from '../models';


/**
 * Get application version
 * Get application version
 */

export const getVersionAxiosRequest = (
  customAxiosInstance?: AxiosInstance
) => {
  return Axios<VersionInfo>(
    {
      url: '/private/version',
      method: 'GET',
      params: {
      }
    },
    customAxiosInstance
  );
};

export const getVersionQueryKey = (
  pageParam = -1,
  version = 1,
) => [
  `/v${version}/private/version`,
  pageParam,
];


export const useGetVersionInfiniteQuery = <T = VersionInfo, Error = ApiError>(
  options?: {
    query?: UseInfiniteQueryOptions<VersionInfo, Error, T>;
    customAxiosInstance?: AxiosInstance;
  },
  pageParam = -1,
  version = 1,
) => {
  const queryKey = getVersionQueryKey(pageParam, version);
  const { query: queryOptions, customAxiosInstance } = options ?? {};

  const query = useInfiniteQuery<VersionInfo, Error, T>(
    queryKey,
    () => getVersionAxiosRequest(customAxiosInstance),
    queryOptions
  );

  return {
    queryKey,
    ...query
  };
};

export const useGetVersionQuery = <T = VersionInfo, Error = ApiError>(
  options?: {
    query?: UseQueryOptions<VersionInfo, Error, T>;
    customAxiosInstance?: AxiosInstance;
  },
  version = 1,
) => {
  const queryKey = getVersionQueryKey(version);
  const { query: queryOptions, customAxiosInstance } = options ?? {};

  const query = useQuery<VersionInfo, Error, T>(
    queryKey,
    () => getVersionAxiosRequest(customAxiosInstance),
    queryOptions
  );

  return {
    queryKey,
    ...query
  };
};






