# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    parameters:
      flavor:
        type: string

    macos:
      xcode: 11.7.0

    steps:
      - checkout

      - run:
          name: Build YugabyteDB
          command: |
            #brew install pkg-config
            echo "Building in directory: $PWD"
            set -x
            sudo mkdir -p -m 0777 /opt/yb-build
            ./yb_build.sh << parameters.flavor >>

workflows:
  version: 2

  mac-build:
    jobs:
      - build:
          name: mac-debug
          flavor: "debug"
          filters:
            branches:
              only: /pull\/.*/

