# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  pullreq:
    description: Pull-request number approved by YB to trigger build
    type: string
    default: "000"

jobs:
  no-build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "Not running builds at this time."

  build:
    parameters:
      flavor:
        type: string

    macos:
      xcode: 11.5.0

    steps:
      - checkout

      - run:
          name: Prep Mac Build & Test Environment
          command: |
            brew install bash cmake maven pstree
            set -x
            sudo mkdir -p -m 0777 /opt/yb-build
            sudo launchctl limit maxfiles 1048576 1048576
            for i in {0..3}; do
              for j in {2..254}; do
                sudo /sbin/ifconfig lo0 alias 127.0.$i.$j
              done
            done
            # Enable host address lookup
            echo $(ipconfig getifaddr en0) $(hostname) | sudo tee -a /etc/hosts

      - run:
          name: Build YugabyteDB
          command: |
            echo "Building in directory: $PWD"
            ulimit -n 1048576
            set -x
            export BUILD_TYPE=<< parameters.flavor >>
            export YB_USE_NINJA=0
            export YB_SKIP_CREATING_RELEASE_PACKAGE=1
            ./build-support/jenkins/build-and-test.sh

      - run:
          name: Gather Test Results
          command: |
            mkdir -p ~/test-results/java
            find java -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/java/ \;
            tar -cvzf test_logs.tar.gz build/*/yb-test-logs build/*/test-logs

      - store_test_results:
          path: ~/test-results/java

      - store_artifacts:
          path: test_logs.tar.gz

# If no workflow is created, then error is generated for the PR/commit.
# If worflow is created, but no jobs run, then it is ignored.
workflows:
  version: 2

  mac-build:
    jobs:
      - build:
          name: mac-debug
          flavor: "debug"
          filters:
            branches:
              only: "pull/<< pipeline.parameters.pullreq >>"
