# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  pullreq:
    description: Pull-request number approved by YB to trigger build
    type: string
    default: "000"

jobs:
  no-build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "Not running builds at this time."

  build:
    parameters:
      flavor:
        type: string

    macos:
      xcode: 11.5.0

    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - run:
          name: Prep Mac Build & Test Environment
          command: |
            set -x
            sudo mkdir -p -m 0777 /opt/yb-build
            sudo launchctl limit maxfiles 1048576 1048576
            # Enable host address lookup
            echo $(ipconfig getifaddr en0) $(hostname) | sudo tee -a /etc/hosts
            # Provide plenty of local test addresses
            for i in {0..1}; do
              for j in {2..64}; do
                sudo /sbin/ifconfig lo0 alias 127.0.$i.$j
              done
            done
            brew install bash cmake maven pstree

      - checkout

      - restore_cache:
          name: Retrieve Thirdparty cache
          key: v1-3p-mac-{{ checksum "build-support/thirdparty_url_mac.txt" }}

      - run:
          name: Build YugabyteDB
          no_output_timeout: "30m"
          command: |
            echo "Building in directory: $PWD"
            set -x
            ulimit -n 1048576
            export BUILD_TYPE=<< parameters.flavor >>
            export YB_USE_NINJA=0
            export YB_SKIP_CREATING_RELEASE_PACKAGE=1
            export EXTRA_TEST_FLAGS="-I 1,25" # only run 25 ctests for testing automation
            ./build-support/jenkins/build-and-test.sh

      - save_cache:
          name: Store Thirdparty cache
          key: v1-3p-mac-{{ checksum "build-support/thirdparty_url_mac.txt" }}
          paths:
            - /opt/yb-build/thirdparty
          when: always

      - run:
          name: Gather Test Results
          when: always
          command: |
            mkdir -p ~/test-results/java
            find java -type f -regex ".*/target/surefire-reports.*/.*xml" -exec cp {} ~/test-results/java/ \;
            tar -cvzf test_logs.tar.gz build/*/yb-test-logs java/*/target/surefire*

      - store_test_results:
          path: ~/test-results/java

      - store_artifacts:
          path: test_logs.tar.gz

# If no workflow is created, then error is generated for the PR/commit.
# If worflow is created, but no jobs run, then it is ignored.
workflows:
  version: 2

  mac-build:
    jobs:
      - build:
          name: mac-debug
          flavor: "debug"
          filters:
            branches:
              only: "pull/<< pipeline.parameters.pullreq >>"
