# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  pullreq:
    description: Pull-request number approved by YB to trigger build
    type: string
    default: "000"

jobs:
  no-build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "Not running builds at this time."

  build:
    parameters:
      flavor:
        type: string

    macos:
      xcode: 11.5.0

    steps:
      - checkout

      - run:
          name: Build YugabyteDB
          command: |
            brew install cmake maven
            echo "Building in directory: $PWD"
            set -x
            sudo mkdir -p -m 0777 /opt/yb-build
            export BUILD_TYPE=<< parameters.flavor >>
            export YB_NUM_TESTS_TO_RUN=25
            ./build-support/jenkins/build-and-test.sh

# If no workflows run, then error is generated.
# If worflow runs, but no jobs, then success is logged.
workflows:
  version: 2

  mac-build:
    jobs:
      - build:
          name: mac-debug
          flavor: "debug"
          filters:
            branches:
              only: "pull/<< pipeline.parameters.pullreq >>"
