version: 2
jobs:
  ubuntu1804:
    docker:
      - image: yugabytedb/yb_build_infra_ubuntu1804:v2019-04-30T20_16_36_mikhail
    steps:
      - checkout
      - run: |
          export MAVEN_OPTS="--add-opens=java.base/java.nio=ALL-UNNAMED"
          export YB_SKIP_INITIAL_SYS_CATALOG_SNAPSHOT=1
          java -version && ./yb_build.sh --ninja -j 1
  ubuntu1904_gcc7:
    docker:
      - image: yugabytedb/yb_build_infra_ubuntu1904_gcc7:v2019-07-11T23_55_23_mbautin
    steps:
      - checkout
      - run: |
          sed -i '/^psutil.*/d' ./python_requirements_frozen.txt  # Temporary workaround.
          export MAVEN_OPTS="--add-opens=java.base/java.nio=ALL-UNNAMED"
          export YB_SKIP_INITIAL_SYS_CATALOG_SNAPSHOT=1
          java -version && ./yb_build.sh --ninja -j 1
workflows:
  # See https://circleci.com/docs/2.0/workflows/
  version: 2
  build_yugabyte_db:
    jobs:
      - ubuntu1804
      - ubuntu1904_gcc7
