# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  pullreq:
    description: Pull-request number approved by YB to trigger build
    type: string
    default: "000"

jobs:
  no-build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "Not running builds at this time."

  build:
    parameters:
      flavor:
        type: string

    macos:
      xcode: 11.5.0

    steps:
      - checkout

      - run:
          name: Build YugabyteDB
          command: |
            brew install bash cmake maven
            echo "Building in directory: $PWD"
            set -x
            sudo mkdir -p -m 0777 /opt/yb-build
            launchctl limit maxfiles
            sudo launchctl limit maxfiles 65536 1048576
            ulimit -n 65536
            ulimit -a
            export BUILD_TYPE=<< parameters.flavor >>
            export YB_USE_NINJA=0
            export YB_SKIP_CREATING_RELEASE_PACKAGE=1
            ./build-support/jenkins/build-and-test.sh

      - run:
          name: Gather Test Results
          command: |
            mkdir -p ~/test-results/java
            find java -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/java/ \;
            tar -cvzf test_logs.tar.gz build/*/yb-test-logs build/*/test-logs

      - store_test_results:
          path: ~/test-results/java

      - store_artifacts:
          path: test_logs.tar.gz

# If no workflows run, then error is generated.
# If worflow runs, but no jobs, then success is logged.
workflows:
  version: 2

  mac-build:
    jobs:
      - build:
          name: mac-debug
          flavor: "debug"
          filters:
            branches:
              only: "pull/<< pipeline.parameters.pullreq >>"
