# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  pullreq:
    description: Pull-request number approved by YB to trigger build
    type: string
    default: "000"

jobs:

  build:
    parameters:
      flavor:
        type: string

    macos:
      xcode: 11.5.0

    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - run:
          name: Prep Mac Build Environment
          command: |
            set -x
            sudo mkdir -p -m 0777 /opt/yb-build
            brew install bash cmake maven pstree ninja

      - checkout

      - restore_cache:
          name: Retrieve Thirdparty cache
          key: v1-3p-mac-{{ checksum "build-support/thirdparty_url_mac.txt" }}

      - restore_cache:
          name: Retrieve Python venv cache
          key: v1-venv-{{ checksum "requirements_frozen.txt" }}

      - run:
          name: Build YugabyteDB
          no_output_timeout: "30m"
          command: |
            echo "Building in directory: $PWD"
            set -x
            export BUILD_TYPE=<< parameters.flavor >>
            export YB_SKIP_CREATING_RELEASE_PACKAGE=1
            ./build-support/jenkins/build-and-test.sh "build"

      - save_cache:
          name: Store Thirdparty cache
          key: v1-3p-mac-{{ checksum "build-support/thirdparty_url_mac.txt" }}
          paths:
            - /opt/yb-build/thirdparty
          when: always

      - save_cache:
          name: Store Python venv cache
          key: v1-venv-{{ checksum "requirements_frozen.txt" }}
          paths:
            - build/venv
          when: always

      - persist_to_workspace:
          name: Save Build Space
          root: .
          paths:
            - ./*

  test:
    parallelism: 5

    parameters:
      flavor:
        type: string
      test_type:
        type: string

    macos:
      xcode: 11.5.0

    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - run:
          name: Prep Mac Test Environment
          command: |
            set -x
            sudo mkdir -p -m 0777 /opt/yb-build
            sudo launchctl limit maxfiles 1048576 1048576
            # Enable host address lookup
            echo $(ipconfig getifaddr en0) $(hostname) | sudo tee -a /etc/hosts
            # Provide plenty of local test addresses
            for i in {0..1}; do
              for j in {2..64}; do
                sudo /sbin/ifconfig lo0 alias 127.0.$i.$j
              done
            done
            brew install bash cmake maven pstree ninja

      - attach_workspace:
          at: .

      # Caches cannot be shared between different jobs, so this is test version of same data.
      - restore_cache:
          name: Retrieve Thirdparty cache
          key: v1-test-3p-mac-{{ checksum "build-support/thirdparty_url_mac.txt" }}

      - run:
          name: Run Tests
          no_output_timeout: "30m"
          command: |
            export BUILD_TYPE=<< parameters.flavor >>
            test_type=<< parameters.test_type >>
            if [[ $test_type == "java_test" ]]; then
              testlist="build/${BUILD_TYPE}-clang-dynamic-ninja/java_test_list.txt"
              mv ${testlist} ${testlist}.full
              circleci tests split ${testlist}.full > ${testlist}
            fi
            ulimit -n 1048576
            export YB_SKIP_CREATING_RELEASE_PACKAGE=1
            ./build-support/jenkins/build-and-test.sh "<< parameters.test_type >>"

      - run:
          name: Archive Reults
          when: always
          command: |
            mkdir -p job_results
            tar czvf job_results/logs${CIRCLE_NODE_INDEX}.tgz test_*.json java/*/target/surefire*/** build/*/yb-test-logs/**

      - store_artifacts:
          path: job_results

      - save_cache:
          name: Store Thirdparty cache
          key: v1-test-3p-mac-{{ checksum "build-support/thirdparty_url_mac.txt" }}
          paths:
            - /opt/yb-build/thirdparty
          when: always


# If no workflow is created, then error is generated for the PR/commit.
# If worflow is created, but no jobs run, then it is ignored.
workflows:
  version: 2

  mac-build:
    jobs:
      - build:
          name: mac-debug-build
          flavor: "debug"
          filters:
            branches:
              only: "pull/<< pipeline.parameters.pullreq >>"
      - test:
          name: mac-debug-cpp-test
          flavor: "debug"
          test_type: "cpp_test"
          requires:
            - mac-debug-build
          filters:
            branches:
              only: "pull/<< pipeline.parameters.pullreq >>"
      - test:
          name: mac-debug-java-test
          flavor: "debug"
          test_type: "java_test"
          requires:
            - mac-debug-build
          filters:
            branches:
              only: "pull/<< pipeline.parameters.pullreq >>"
