services:
  - name: postgresService
    fileName: "{{ .SystemdFileLocation }}"
    contents: |
      [Unit]
      Description=Postgres
      Wants=network-online.target
      After=network-online.target

      [Service]
      {{ if eq (yamlPath "as_root") "true" }}
      User={{ yamlPath "service_username" }}
      Group={{ yamlPath "service_username" }}
      {{ end }}
      Type=forking
      TimeoutSec=300

      ExecStart={{ .PgBin }}/pg_ctl -D {{ .ConfFileLocation }} \
      -w -o "-k {{ .MountPath }}" start

      ExecStop={{ .PgBin }}/pg_ctl -D {{ .ConfFileLocation }} \
      -w -o "-k {{ .MountPath }}" stop

      Restart=always
      RestartSec={{ yamlPath "postgres.install.restartSeconds"}}

      [Install]
      WantedBy=multi-user.target
