FROM mcr.microsoft.com/cosmosdb/ubuntu/documentdb-oss:base

WORKDIR /home/documentdb/code  

COPY . /home/documentdb/code  

RUN git config --global --add safe.directory /home/DocumentDB/code
RUN make  && sudo make install
  
# Set the entry point to run the new script at container startup  
CMD ["bash", "-c", "/home/documentdb/code/scripts/start_oss_server.sh & tail -f /dev/null"]