-- Copyright (c) YugaByte, Inc.
-- This file is empty because this migration is already taken care of by V57.
-- We would not need this if we had the feature where missing migrations
-- could be ignored.
