- assert:
    that:
      - user_name is defined
      - mount_points is defined

- name: Install OpenTelemetry collector
  import_tasks: install-otel-col.yml
  become_user: "{{ user_name }}"
  when: install_otel_collector is defined and install_otel_collector|bool

- name: Create OpenTelemetry collector service
  import_tasks: otel-col-service.yml
  when: install_otel_collector is defined and install_otel_collector|bool

- name: Control OpenTelemetry collector service
  import_tasks: otel-col-control.yml
  become_user: "{{ user_name }}"
