baseurl = 'https://docs.yugabyte.com'
languageCode = 'en-us'
title = 'YugabyteDB Docs'
# Highlighting config (Pygments)
pygmentsCodefences = true
pygmentsStyle = 'pygments'
resourceDir = 'docs/resources'

[languages]
  [languages.en]
    contentDir = "content"
    languageName = "English"
    weight = 1

enableGitInfo = true

[frontmatter]
  date = [ "lastmod", ":default" ]
# lastmod = [ ":git", ":default" ]

[params]
  regenerateDiagrams = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.145.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false
  [[module.imports]]
    path = "github.com/trunkcode/hugo-seo"
    disable = false

[markup.goldmark.parser.attribute]
    block = true

[security]
  [security.funcs]
    getenv = [
      'RUDDERSTACK_API_KEY'
    ]
