title: PitrConfigPagedQuerySpec
description: |
  Paged list of PITR configs for a universe.
  Rows are ordered by config name (case-insensitive), then UUID. The order is ascending by default.
type: object
allOf:
  - $ref: "./PaginationSpec.yaml"
properties:
  filter:
    $ref: "./PitrConfigApiFilter.yaml"
