title: PrometheusMetricsType
description: Prometheus export to include in a support bundle metrics dump.
type: string
enum:
  - MASTER_EXPORT
  - NODE_EXPORT
  - PLATFORM
  - PROMETHEUS
  - TSERVER_EXPORT
  - CQL_EXPORT
  - YSQL_EXPORT
x-enum-varnames:
  - PROMETHEUS_METRICS_MASTER_EXPORT
  - PROMETHEUS_METRICS_NODE_EXPORT
  - PROMETHEUS_METRICS_PLATFORM
  - PROMETHEUS_METRICS_PROMETHEUS
  - PROMETHEUS_METRICS_TSERVER_EXPORT
  - PROMETHEUS_METRICS_CQL_EXPORT
  - PROMETHEUS_METRICS_YSQL_EXPORT
