title: QueryLogConfig
description: Query Log Configuration Specification for the Universe. Part of Clusterspec.
required:
  - universe_logs_exporter_config
type: object
properties:
  export_active:
    description: Universe logs export active
    type: boolean
  universe_logs_exporter_config:
    description: Universe logs exporter config
    type: array
    items:
      $ref: "./UniverseQueryLogsExporterConfig.yaml"
  ysql_query_log_config:
    description: YSQL query log config
    $ref: "./YSQLQueryLogConfig.yaml"
