title: UniverseQueryLogsExporterConfig
type: object
description: |
  UniverseQueryLogsExporterConfig

  Universe Logs Exporter Config. Part of QueryLogConfig.
allOf:
  - $ref: "./UniverseExporterConfig.yaml"
  - type: object
    properties:
      send_batch_max_size:
        description: Send batch max size
        type: integer
        format: int32
        default: 1000
      send_batch_size:
        description: Send batch max size
        type: integer
        format: int32
        default: 100
      send_batch_timeout_seconds:
        description: Send batch timeout in seconds
        type: integer
        format: int32
        default: 10
      memory_limit_mib:
        description: Memory limit in MiB for the OpenTelemetry Collector process in the config file.
        type: integer
        example: 2048
        default: 2048
      memory_limit_check_interval_seconds:
        description: Check interval in seconds for the MemoryLimiterProcessor.
        type: integer
        example: 10
        default: 10
