title: UniverseExporterConfig
type: object
description: |
  UniverseExporterConfig
  Universe Exporter Config. Base configuration for exporters in the Universe. Used for AuditLogConfig, QueryLogConfig
required:
  - additional_tags
  - exporter_uuid
properties:
  additional_tags:
    description: Additional tags
    type: object
    additionalProperties:
      type: string
  exporter_uuid:
    description: Exporter uuid
    type: string
    format: uuid
