# Copyright 2019 YugabyteDB, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- name: Editing authorized_keys file
  hosts: "{{ yb_ansible_host }}"
  gather_facts: no
  tasks:
    - name: Edit Authorized Keys | Append public key to authorized_keys
      authorized_key:
        user: "{{ ssh_user }}"
        key: "{{ public_key_content }}"
        state: "present"
        validate_certs: False
        manage_dir: False
        comment: "Added by Yugabyte"
      when: command == "add-authorized-key"
    - name: Edit Authorized Keys | Remove public key from authorized_keys
      authorized_key:
        user: "{{ ssh_user }}"
        key: "{{ public_key_content }}"
        state: "absent"
        validate_certs: False
        manage_dir: False
      when: command == "remove-authorized-key"
