# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- name: "Use custom SSH port"
  module_defaults:
    yum:
      lock_timeout: 600
  hosts: "{{ yb_ansible_host }}"
  become: yes
  become_method: sudo
  roles:
    - ansible-sshd
  vars:
    sshd:
      Port: "{{ custom_ssh_port }}"
      # Disable empty password and root login.
      # https://github.com/yugabyte/yugabyte-db/issues/7415
      PermitRootLogin: no
      PermitEmptyPasswords: no
      # Disable all authentication methods except `publickey`.
      PasswordAuthentication: no
      ChallengeResponseAuthentication: no
      KbdInteractiveAuthentication: no
      AuthenticationMethods: 'publickey'
  tags: yb-prebuilt-ami
