#!/bin/bash
#
# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

set -e

. "${BASH_SOURCE%/*}"/bin/common.sh

activate_virtualenv
bin/install_python_requirements.sh --create_package
bin/install_ansible_requirements.sh --force
"$yb_devops_home"/yb_release.py "$@"
# Remove virtual env package after creating tar.gz to least impact developers because
# bin/install_python_requirements.sh will always prioritize the package over local changes.
rm -rf $virtualenv_package
