#!/bin/bash
#
# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

set -e

# Create python2 packages.
export YB_MANAGED_DEVOPS_USE_PYTHON3=0
bin/install_python_requirements.sh --create_package --use_dynamic_paths

# Use python3 to create the actual release.
export YB_MANAGED_DEVOPS_USE_PYTHON3=1
. "${BASH_SOURCE%/*}"/bin/common.sh
bin/install_python_requirements.sh
activate_virtualenv
bin/install_ansible_requirements.sh --force
"$yb_devops_home"/yb_release.py "$@"
rm -rf "$YB_PYTHON_MODULES_PACKAGE"
