#!/bin/bash
#
# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

set -e

export YB_MANAGED_DEVOPS_USE_PYTHON3=1

. "${BASH_SOURCE%/*}"/bin/common.sh

# Use dynamic paths to shorten shebangs below 64 characters.
bin/install_python_requirements.sh --use_dynamic_paths
activate_virtualenv
bin/install_ansible_requirements.sh --force

# Python modules build for yugabundle.
# cd "$yb_devops_home"
# docker build -t "$DOCKER_VENV_IMAGE_NAME" .
# docker run -v "$yb_devops_home:/devops" -u "$UID:$(id -g $UID)" "$DOCKER_VENV_IMAGE_NAME"

# PEX virtual env build for other deployments.
cd "$yb_devops_home/pex"
docker build -t "$DOCKER_PEX_IMAGE_NAME" .
# Execute the build_pex.sh script inside the built docker image
# to generate the repaired PEX.
docker run -v "$yb_devops_home:/code" -u "$UID:$(id -g $UID)" \
"$DOCKER_PEX_IMAGE_NAME" -c "-r" "/code/python3_requirements_frozen.txt"

"$yb_devops_home"/yb_release.py "$@"
rm -rf "$YB_PYTHON_MODULES_PACKAGE"
