#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/ybcam
#
# IDENTIFICATION
#    src/backend/access/ybc/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/ybc
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = ybcam.o ybcin.o

include $(top_srcdir)/src/backend/common.mk
