/*-------------------------------------------------------------------------
 * Copyright (c) Microsoft Corporation.  All rights reserved.
 *
 * include/utils/helio_errors.h
 *
 * Utilities for converting Helio error to mongo error.
 * This file is generated - please modify the source (mongoerrors.csv)
 *
 *-------------------------------------------------------------------------
 */

#include <postgres.h>
#include <utils/helio_errors.h>

int32_t
GetMongoErrorCodeFromHelioError(int32_t sqlStateError)
{
	switch (sqlStateError)
	{
		case ERRCODE_HELIO_INTERNALERROR:
		{
			return MONGO_CODE_INTERNALERROR;
		}

		case ERRCODE_HELIO_BADVALUE:
		{
			return MONGO_CODE_BADVALUE;
		}

		case ERRCODE_HELIO_GRAPHCONTAINSCYCLE:
		{
			return MONGO_CODE_GRAPHCONTAINSCYCLE;
		}

		case ERRCODE_HELIO_FAILEDTOPARSE:
		{
			return MONGO_CODE_FAILEDTOPARSE;
		}

		case ERRCODE_HELIO_TYPEMISMATCH:
		{
			return MONGO_CODE_TYPEMISMATCH;
		}

		case ERRCODE_HELIO_OVERFLOW:
		{
			return MONGO_CODE_OVERFLOW;
		}

		case ERRCODE_HELIO_ILLEGALOPERATION:
		{
			return MONGO_CODE_ILLEGALOPERATION;
		}

		case ERRCODE_HELIO_ALREADYINITIALIZED:
		{
			return MONGO_CODE_ALREADYINITIALIZED;
		}

		case ERRCODE_HELIO_NAMESPACENOTFOUND:
		{
			return MONGO_CODE_NAMESPACENOTFOUND;
		}

		case ERRCODE_HELIO_INDEXNOTFOUND:
		{
			return MONGO_CODE_INDEXNOTFOUND;
		}

		case ERRCODE_HELIO_PATHNOTVIABLE:
		{
			return MONGO_CODE_PATHNOTVIABLE;
		}

		case ERRCODE_HELIO_ROLENOTFOUND:
		{
			return MONGO_CODE_ROLENOTFOUND;
		}

		case ERRCODE_HELIO_CANNOTBACKFILLARRAY:
		{
			return MONGO_CODE_CANNOTBACKFILLARRAY;
		}

		case ERRCODE_HELIO_CONFLICTINGUPDATEOPERATORS:
		{
			return MONGO_CODE_CONFLICTINGUPDATEOPERATORS;
		}

		case ERRCODE_HELIO_CURSORNOTFOUND:
		{
			return MONGO_CODE_CURSORNOTFOUND;
		}

		case ERRCODE_HELIO_NAMESPACEEXISTS:
		{
			return MONGO_CODE_NAMESPACEEXISTS;
		}

		case ERRCODE_HELIO_DOLLARPREFIXEDFIELDNAME:
		{
			return MONGO_CODE_DOLLARPREFIXEDFIELDNAME;
		}

		case ERRCODE_HELIO_CANNOTBETYPEARRAY:
		{
			return MONGO_CODE_CANNOTBETYPEARRAY;
		}

		case ERRCODE_HELIO_NOTSINGLEVALUEFIELD:
		{
			return MONGO_CODE_NOTSINGLEVALUEFIELD;
		}

		case ERRCODE_HELIO_EMPTYFIELDNAME:
		{
			return MONGO_CODE_EMPTYFIELDNAME;
		}

		case ERRCODE_HELIO_DOTTEDFIELDNAME:
		{
			return MONGO_CODE_DOTTEDFIELDNAME;
		}

		case ERRCODE_HELIO_SHARDKEYNOTFOUND:
		{
			return MONGO_CODE_SHARDKEYNOTFOUND;
		}

		case ERRCODE_HELIO_IMMUTABLEFIELD:
		{
			return MONGO_CODE_IMMUTABLEFIELD;
		}

		case ERRCODE_HELIO_CANNOTCREATEINDEX:
		{
			return MONGO_CODE_CANNOTCREATEINDEX;
		}

		case ERRCODE_HELIO_INDEXALREADYEXISTS:
		{
			return MONGO_CODE_INDEXALREADYEXISTS;
		}

		case ERRCODE_HELIO_INVALIDOPTIONS:
		{
			return MONGO_CODE_INVALIDOPTIONS;
		}

		case ERRCODE_HELIO_INVALIDNAMESPACE:
		{
			return MONGO_CODE_INVALIDNAMESPACE;
		}

		case ERRCODE_HELIO_INDEXOPTIONSCONFLICT:
		{
			return MONGO_CODE_INDEXOPTIONSCONFLICT;
		}

		case ERRCODE_HELIO_INDEXKEYSPECSCONFLICT:
		{
			return MONGO_CODE_INDEXKEYSPECSCONFLICT;
		}

		case ERRCODE_HELIO_NOTEXACTVALUEFIELD:
		{
			return MONGO_CODE_NOTEXACTVALUEFIELD;
		}

		case ERRCODE_HELIO_COMMANDNOTSUPPORTED:
		{
			return MONGO_CODE_COMMANDNOTSUPPORTED;
		}

		case ERRCODE_HELIO_NAMESPACENOTSHARDED:
		{
			return MONGO_CODE_NAMESPACENOTSHARDED;
		}

		case ERRCODE_HELIO_EXCEEDEDMEMORYLIMIT:
		{
			return MONGO_CODE_EXCEEDEDMEMORYLIMIT;
		}

		case ERRCODE_HELIO_DURATIONOVERFLOW:
		{
			return MONGO_CODE_DURATIONOVERFLOW;
		}

		case ERRCODE_HELIO_VIEWDEPTHLIMITEXCEEDED:
		{
			return MONGO_CODE_VIEWDEPTHLIMITEXCEEDED;
		}

		case ERRCODE_HELIO_COMMANDNOTSUPPORTEDONVIEW:
		{
			return MONGO_CODE_COMMANDNOTSUPPORTEDONVIEW;
		}

		case ERRCODE_HELIO_OPTIONNOTSUPPORTEDONVIEW:
		{
			return MONGO_CODE_OPTIONNOTSUPPORTEDONVIEW;
		}

		case ERRCODE_HELIO_AMBIGUOUSINDEXKEYPATTERN:
		{
			return MONGO_CODE_AMBIGUOUSINDEXKEYPATTERN;
		}

		case ERRCODE_HELIO_INVALIDINDEXSPECIFICATIONOPTION:
		{
			return MONGO_CODE_INVALIDINDEXSPECIFICATIONOPTION;
		}

		case ERRCODE_HELIO_QUERYFEATURENOTALLOWED:
		{
			return MONGO_CODE_QUERYFEATURENOTALLOWED;
		}

		case ERRCODE_HELIO_MAXSUBPIPELINEDEPTHEXCEEDED:
		{
			return MONGO_CODE_MAXSUBPIPELINEDEPTHEXCEEDED;
		}

		case ERRCODE_HELIO_CONVERSIONFAILURE:
		{
			return MONGO_CODE_CONVERSIONFAILURE;
		}

		case ERRCODE_HELIO_OPERATIONNOTSUPPORTEDINTRANSACTION:
		{
			return MONGO_CODE_OPERATIONNOTSUPPORTEDINTRANSACTION;
		}

		case ERRCODE_HELIO_INDEXBUILDABORTED:
		{
			return MONGO_CODE_INDEXBUILDABORTED;
		}

		case ERRCODE_HELIO_UNABLETOFINDINDEX:
		{
			return MONGO_CODE_UNABLETOFINDINDEX;
		}

		case ERRCODE_HELIO_COLLECTIONUUIDMISMATCH:
		{
			return MONGO_CODE_COLLECTIONUUIDMISMATCH;
		}

		case ERRCODE_HELIO_LOCATION10065:
		{
			return MONGO_CODE_LOCATION10065;
		}

		case ERRCODE_HELIO_BSONOBJECTTOOLARGE:
		{
			return MONGO_CODE_BSONOBJECTTOOLARGE;
		}

		case ERRCODE_HELIO_DUPLICATEKEY:
		{
			return MONGO_CODE_DUPLICATEKEY;
		}

		case ERRCODE_HELIO_BACKGROUNDOPERATIONINPROGRESSFORNAMESPACE:
		{
			return MONGO_CODE_BACKGROUNDOPERATIONINPROGRESSFORNAMESPACE;
		}

		case ERRCODE_HELIO_LOCATION13026:
		{
			return MONGO_CODE_LOCATION13026;
		}

		case ERRCODE_HELIO_LOCATION13027:
		{
			return MONGO_CODE_LOCATION13027;
		}

		case ERRCODE_HELIO_LOCATION13068:
		{
			return MONGO_CODE_LOCATION13068;
		}

		case ERRCODE_HELIO_MERGESTAGENOMATCHINGDOCUMENT:
		{
			return MONGO_CODE_MERGESTAGENOMATCHINGDOCUMENT;
		}

		case ERRCODE_HELIO_DBALREADYEXISTS:
		{
			return MONGO_CODE_DBALREADYEXISTS;
		}

		case ERRCODE_HELIO_LOCATION13548:
		{
			return MONGO_CODE_LOCATION13548;
		}

		case ERRCODE_HELIO_LOCATION15947:
		{
			return MONGO_CODE_LOCATION15947;
		}

		case ERRCODE_HELIO_LOCATION15952:
		{
			return MONGO_CODE_LOCATION15952;
		}

		case ERRCODE_HELIO_LOCATION15955:
		{
			return MONGO_CODE_LOCATION15955;
		}

		case ERRCODE_HELIO_LOCATION15957:
		{
			return MONGO_CODE_LOCATION15957;
		}

		case ERRCODE_HELIO_LOCATION15958:
		{
			return MONGO_CODE_LOCATION15958;
		}

		case ERRCODE_HELIO_LOCATION15959:
		{
			return MONGO_CODE_LOCATION15959;
		}

		case ERRCODE_HELIO_LOCATION15972:
		{
			return MONGO_CODE_LOCATION15972;
		}

		case ERRCODE_HELIO_LOCATION15976:
		{
			return MONGO_CODE_LOCATION15976;
		}

		case ERRCODE_HELIO_LOCATION15981:
		{
			return MONGO_CODE_LOCATION15981;
		}

		case ERRCODE_HELIO_LOCATION16004:
		{
			return MONGO_CODE_LOCATION16004;
		}

		case ERRCODE_HELIO_LOCATION16006:
		{
			return MONGO_CODE_LOCATION16006;
		}

		case ERRCODE_HELIO_LOCATION16007:
		{
			return MONGO_CODE_LOCATION16007;
		}

		case ERRCODE_HELIO_LOCATION16020:
		{
			return MONGO_CODE_LOCATION16020;
		}

		case ERRCODE_HELIO_LOCATION6045000:
		{
			return MONGO_CODE_LOCATION6045000;
		}

		case ERRCODE_HELIO_LOCATION16034:
		{
			return MONGO_CODE_LOCATION16034;
		}

		case ERRCODE_HELIO_LOCATION16035:
		{
			return MONGO_CODE_LOCATION16035;
		}

		case ERRCODE_HELIO_LOCATION16410:
		{
			return MONGO_CODE_LOCATION16410;
		}

		case ERRCODE_HELIO_LOCATION16411:
		{
			return MONGO_CODE_LOCATION16411;
		}

		case ERRCODE_HELIO_LOCATION16433:
		{
			return MONGO_CODE_LOCATION16433;
		}

		case ERRCODE_HELIO_DOLLARADDNUMERICORDATETYPES:
		{
			return MONGO_CODE_DOLLARADDNUMERICORDATETYPES;
		}

		case ERRCODE_HELIO_DOLLARMODBYZEROPROHIBITED:
		{
			return MONGO_CODE_DOLLARMODBYZEROPROHIBITED;
		}

		case ERRCODE_HELIO_DOLLARMODONLYNUMERIC:
		{
			return MONGO_CODE_DOLLARMODONLYNUMERIC;
		}

		case ERRCODE_HELIO_DOLLARADDONLYONEDATE:
		{
			return MONGO_CODE_DOLLARADDONLYONEDATE;
		}

		case ERRCODE_HELIO_LOCATION16702:
		{
			return MONGO_CODE_LOCATION16702;
		}

		case ERRCODE_HELIO_LOCATION16747:
		{
			return MONGO_CODE_LOCATION16747;
		}

		case ERRCODE_HELIO_LOCATION16748:
		{
			return MONGO_CODE_LOCATION16748;
		}

		case ERRCODE_HELIO_LOCATION16749:
		{
			return MONGO_CODE_LOCATION16749;
		}

		case ERRCODE_HELIO_LOCATION16755:
		{
			return MONGO_CODE_LOCATION16755;
		}

		case ERRCODE_HELIO_LOCATION16764:
		{
			return MONGO_CODE_LOCATION16764;
		}

		case ERRCODE_HELIO_HASHEDINDEXDONOTSUPPORTARRAYVALUES:
		{
			return MONGO_CODE_HASHEDINDEXDONOTSUPPORTARRAYVALUES;
		}

		case ERRCODE_HELIO_LOCATION16800:
		{
			return MONGO_CODE_LOCATION16800;
		}

		case ERRCODE_HELIO_LOCATION16801:
		{
			return MONGO_CODE_LOCATION16801;
		}

		case ERRCODE_HELIO_LOCATION16804:
		{
			return MONGO_CODE_LOCATION16804;
		}

		case ERRCODE_HELIO_LOCATION16874:
		{
			return MONGO_CODE_LOCATION16874;
		}

		case ERRCODE_HELIO_LOCATION16875:
		{
			return MONGO_CODE_LOCATION16875;
		}

		case ERRCODE_HELIO_LOCATION16876:
		{
			return MONGO_CODE_LOCATION16876;
		}

		case ERRCODE_HELIO_LOCATION16878:
		{
			return MONGO_CODE_LOCATION16878;
		}

		case ERRCODE_HELIO_LOCATION16879:
		{
			return MONGO_CODE_LOCATION16879;
		}

		case ERRCODE_HELIO_LOCATION16880:
		{
			return MONGO_CODE_LOCATION16880;
		}

		case ERRCODE_HELIO_LOCATION16882:
		{
			return MONGO_CODE_LOCATION16882;
		}

		case ERRCODE_HELIO_LOCATION16883:
		{
			return MONGO_CODE_LOCATION16883;
		}

		case ERRCODE_HELIO_LOCATION16994:
		{
			return MONGO_CODE_LOCATION16994;
		}

		case ERRCODE_HELIO_LOCATION17040:
		{
			return MONGO_CODE_LOCATION17040;
		}

		case ERRCODE_HELIO_LOCATION17041:
		{
			return MONGO_CODE_LOCATION17041;
		}

		case ERRCODE_HELIO_LOCATION17042:
		{
			return MONGO_CODE_LOCATION17042;
		}

		case ERRCODE_HELIO_LOCATION17043:
		{
			return MONGO_CODE_LOCATION17043;
		}

		case ERRCODE_HELIO_LOCATION17044:
		{
			return MONGO_CODE_LOCATION17044;
		}

		case ERRCODE_HELIO_LOCATION17045:
		{
			return MONGO_CODE_LOCATION17045;
		}

		case ERRCODE_HELIO_LOCATION17046:
		{
			return MONGO_CODE_LOCATION17046;
		}

		case ERRCODE_HELIO_LOCATION17047:
		{
			return MONGO_CODE_LOCATION17047;
		}

		case ERRCODE_HELIO_LOCATION17048:
		{
			return MONGO_CODE_LOCATION17048;
		}

		case ERRCODE_HELIO_LOCATION17049:
		{
			return MONGO_CODE_LOCATION17049;
		}

		case ERRCODE_HELIO_DOLLARCONDMISSINGIFPARAMETER:
		{
			return MONGO_CODE_DOLLARCONDMISSINGIFPARAMETER;
		}

		case ERRCODE_HELIO_DOLLARCONDMISSINGTHENPARAMETER:
		{
			return MONGO_CODE_DOLLARCONDMISSINGTHENPARAMETER;
		}

		case ERRCODE_HELIO_DOLLARCONDMISSINGELSEPARAMETER:
		{
			return MONGO_CODE_DOLLARCONDMISSINGELSEPARAMETER;
		}

		case ERRCODE_HELIO_DOLLARCONDBADPARAMETER:
		{
			return MONGO_CODE_DOLLARCONDBADPARAMETER;
		}

		case ERRCODE_HELIO_DOLLARSIZEREQUIRESARRAY:
		{
			return MONGO_CODE_DOLLARSIZEREQUIRESARRAY;
		}

		case ERRCODE_HELIO_EXACTLYONETEXTINDEX:
		{
			return MONGO_CODE_EXACTLYONETEXTINDEX;
		}

		case ERRCODE_HELIO_LOCATION17261:
		{
			return MONGO_CODE_LOCATION17261;
		}

		case ERRCODE_HELIO_LOCATION17276:
		{
			return MONGO_CODE_LOCATION17276;
		}

		case ERRCODE_HELIO_LOCATION17308:
		{
			return MONGO_CODE_LOCATION17308;
		}

		case ERRCODE_HELIO_LOCATION17310:
		{
			return MONGO_CODE_LOCATION17310;
		}

		case ERRCODE_HELIO_DOCUMENTAFTERUPDATELARGERTHANMAXSIZE:
		{
			return MONGO_CODE_DOCUMENTAFTERUPDATELARGERTHANMAXSIZE;
		}

		case ERRCODE_HELIO_DOCUMENTTOUPSERTLARGERTHANMAXSIZE:
		{
			return MONGO_CODE_DOCUMENTTOUPSERTLARGERTHANMAXSIZE;
		}

		case ERRCODE_HELIO_LOCATION18628:
		{
			return MONGO_CODE_LOCATION18628;
		}

		case ERRCODE_HELIO_LOCATION18629:
		{
			return MONGO_CODE_LOCATION18629;
		}

		case ERRCODE_HELIO_LOCATION18533:
		{
			return MONGO_CODE_LOCATION18533;
		}

		case ERRCODE_HELIO_LOCATION18534:
		{
			return MONGO_CODE_LOCATION18534;
		}

		case ERRCODE_HELIO_LOCATION18535:
		{
			return MONGO_CODE_LOCATION18535;
		}

		case ERRCODE_HELIO_LOCATION18536:
		{
			return MONGO_CODE_LOCATION18536;
		}

		case ERRCODE_HELIO_LOCATION18537:
		{
			return MONGO_CODE_LOCATION18537;
		}

		case ERRCODE_HELIO_LOCATION28625:
		{
			return MONGO_CODE_LOCATION28625;
		}

		case ERRCODE_HELIO_LOCATION28646:
		{
			return MONGO_CODE_LOCATION28646;
		}

		case ERRCODE_HELIO_LOCATION28647:
		{
			return MONGO_CODE_LOCATION28647;
		}

		case ERRCODE_HELIO_LOCATION28648:
		{
			return MONGO_CODE_LOCATION28648;
		}

		case ERRCODE_HELIO_LOCATION28650:
		{
			return MONGO_CODE_LOCATION28650;
		}

		case ERRCODE_HELIO_LOCATION28651:
		{
			return MONGO_CODE_LOCATION28651;
		}

		case ERRCODE_HELIO_LOCATION28656:
		{
			return MONGO_CODE_LOCATION28656;
		}

		case ERRCODE_HELIO_LOCATION28657:
		{
			return MONGO_CODE_LOCATION28657;
		}

		case ERRCODE_HELIO_LOCATION28664:
		{
			return MONGO_CODE_LOCATION28664;
		}

		case ERRCODE_HELIO_LOCATION51044:
		{
			return MONGO_CODE_LOCATION51044;
		}

		case ERRCODE_HELIO_LOCATION51045:
		{
			return MONGO_CODE_LOCATION51045;
		}

		case ERRCODE_HELIO_LOCATION50989:
		{
			return MONGO_CODE_LOCATION50989;
		}

		case ERRCODE_HELIO_RANGEARGUMENTEXPRESSIONARGSOUTOFRANGE:
		{
			return MONGO_CODE_RANGEARGUMENTEXPRESSIONARGSOUTOFRANGE;
		}

		case ERRCODE_HELIO_DOLLARABSCANTTAKELONGMINVALUE:
		{
			return MONGO_CODE_DOLLARABSCANTTAKELONGMINVALUE;
		}

		case ERRCODE_HELIO_ARRAYOPERATORELEMATFIRSTARGMUSTBEARRAY:
		{
			return MONGO_CODE_ARRAYOPERATORELEMATFIRSTARGMUSTBEARRAY;
		}

		case ERRCODE_HELIO_DOLLARARRAYELEMATSECONDARGARGMUSTBENUMERIC:
		{
			return MONGO_CODE_DOLLARARRAYELEMATSECONDARGARGMUSTBENUMERIC;
		}

		case ERRCODE_HELIO_DOLLARARRAYELEMATSECONDARGARGMUSTBE32BIT:
		{
			return MONGO_CODE_DOLLARARRAYELEMATSECONDARGARGMUSTBE32BIT;
		}

		case ERRCODE_HELIO_DOLLARSQRTGREATEROREQUALTOZERO:
		{
			return MONGO_CODE_DOLLARSQRTGREATEROREQUALTOZERO;
		}

		case ERRCODE_HELIO_DOLLARSLICEINVALIDINPUT:
		{
			return MONGO_CODE_DOLLARSLICEINVALIDINPUT;
		}

		case ERRCODE_HELIO_DOLLARSLICEINVALIDTYPESECONDARG:
		{
			return MONGO_CODE_DOLLARSLICEINVALIDTYPESECONDARG;
		}

		case ERRCODE_HELIO_DOLLARSLICEINVALIDVALUESECONDARG:
		{
			return MONGO_CODE_DOLLARSLICEINVALIDVALUESECONDARG;
		}

		case ERRCODE_HELIO_DOLLARSLICEINVALIDTYPETHIRDARG:
		{
			return MONGO_CODE_DOLLARSLICEINVALIDTYPETHIRDARG;
		}

		case ERRCODE_HELIO_DOLLARSLICEINVALIDVALUETHIRDARG:
		{
			return MONGO_CODE_DOLLARSLICEINVALIDVALUETHIRDARG;
		}

		case ERRCODE_HELIO_DOLLARSLICEINVALIDSIGNTHIRDARG:
		{
			return MONGO_CODE_DOLLARSLICEINVALIDSIGNTHIRDARG;
		}

		case ERRCODE_HELIO_LOCATION28745:
		{
			return MONGO_CODE_LOCATION28745;
		}

		case ERRCODE_HELIO_LOCATION28746:
		{
			return MONGO_CODE_LOCATION28746;
		}

		case ERRCODE_HELIO_LOCATION28747:
		{
			return MONGO_CODE_LOCATION28747;
		}

		case ERRCODE_HELIO_LOCATION28748:
		{
			return MONGO_CODE_LOCATION28748;
		}

		case ERRCODE_HELIO_LOCATION28749:
		{
			return MONGO_CODE_LOCATION28749;
		}

		case ERRCODE_HELIO_DOLLARLOGARGUMENTMUSTBENUMERIC:
		{
			return MONGO_CODE_DOLLARLOGARGUMENTMUSTBENUMERIC;
		}

		case ERRCODE_HELIO_DOLLARLOGBASEMUSTBENUMERIC:
		{
			return MONGO_CODE_DOLLARLOGBASEMUSTBENUMERIC;
		}

		case ERRCODE_HELIO_DOLLARLOGNUMBERMUSTBEPOSITIVE:
		{
			return MONGO_CODE_DOLLARLOGNUMBERMUSTBEPOSITIVE;
		}

		case ERRCODE_HELIO_DOLLARLOGBASEMUSTBEGREATERTHANONE:
		{
			return MONGO_CODE_DOLLARLOGBASEMUSTBEGREATERTHANONE;
		}

		case ERRCODE_HELIO_DOLLARLOG10MUSTBEPOSITIVENUMBER:
		{
			return MONGO_CODE_DOLLARLOG10MUSTBEPOSITIVENUMBER;
		}

		case ERRCODE_HELIO_DOLLARPOWBASEMUSTBENUMERIC:
		{
			return MONGO_CODE_DOLLARPOWBASEMUSTBENUMERIC;
		}

		case ERRCODE_HELIO_DOLLARPOWEXPONENTMUSTBENUMERIC:
		{
			return MONGO_CODE_DOLLARPOWEXPONENTMUSTBENUMERIC;
		}

		case ERRCODE_HELIO_DOLLARPOWEXPONENTINVALIDFORZEROBASE:
		{
			return MONGO_CODE_DOLLARPOWEXPONENTINVALIDFORZEROBASE;
		}

		case ERRCODE_HELIO_LOCATION28765:
		{
			return MONGO_CODE_LOCATION28765;
		}

		case ERRCODE_HELIO_DOLLARLNMUSTBEPOSITIVENUMBER:
		{
			return MONGO_CODE_DOLLARLNMUSTBEPOSITIVENUMBER;
		}

		case ERRCODE_HELIO_LOCATION28769:
		{
			return MONGO_CODE_LOCATION28769;
		}

		case ERRCODE_HELIO_LOCATION28803:
		{
			return MONGO_CODE_LOCATION28803;
		}

		case ERRCODE_HELIO_LOCATION28808:
		{
			return MONGO_CODE_LOCATION28808;
		}

		case ERRCODE_HELIO_LOCATION28809:
		{
			return MONGO_CODE_LOCATION28809;
		}

		case ERRCODE_HELIO_LOCATION28810:
		{
			return MONGO_CODE_LOCATION28810;
		}

		case ERRCODE_HELIO_LOCATION28811:
		{
			return MONGO_CODE_LOCATION28811;
		}

		case ERRCODE_HELIO_LOCATION28812:
		{
			return MONGO_CODE_LOCATION28812;
		}

		case ERRCODE_HELIO_LOCATION28818:
		{
			return MONGO_CODE_LOCATION28818;
		}

		case ERRCODE_HELIO_LOCATION28822:
		{
			return MONGO_CODE_LOCATION28822;
		}

		case ERRCODE_HELIO_KEYCANNOTCONTAINNULLBYTE:
		{
			return MONGO_CODE_KEYCANNOTCONTAINNULLBYTE;
		}

		case ERRCODE_HELIO_LOCATION31002:
		{
			return MONGO_CODE_LOCATION31002;
		}

		case ERRCODE_HELIO_LOCATION31022:
		{
			return MONGO_CODE_LOCATION31022;
		}

		case ERRCODE_HELIO_LOCATION31023:
		{
			return MONGO_CODE_LOCATION31023;
		}

		case ERRCODE_HELIO_LOCATION31024:
		{
			return MONGO_CODE_LOCATION31024;
		}

		case ERRCODE_HELIO_LOCATION31034:
		{
			return MONGO_CODE_LOCATION31034;
		}

		case ERRCODE_HELIO_LOCATION31095:
		{
			return MONGO_CODE_LOCATION31095;
		}

		case ERRCODE_HELIO_LOCATION31109:
		{
			return MONGO_CODE_LOCATION31109;
		}

		case ERRCODE_HELIO_LOCATION31119:
		{
			return MONGO_CODE_LOCATION31119;
		}

		case ERRCODE_HELIO_LOCATION31120:
		{
			return MONGO_CODE_LOCATION31120;
		}

		case ERRCODE_HELIO_LOCATION31138:
		{
			return MONGO_CODE_LOCATION31138;
		}

		case ERRCODE_HELIO_LOCATION31249:
		{
			return MONGO_CODE_LOCATION31249;
		}

		case ERRCODE_HELIO_LOCATION31250:
		{
			return MONGO_CODE_LOCATION31250;
		}

		case ERRCODE_HELIO_LOCATION31253:
		{
			return MONGO_CODE_LOCATION31253;
		}

		case ERRCODE_HELIO_LOCATION31254:
		{
			return MONGO_CODE_LOCATION31254;
		}

		case ERRCODE_HELIO_LOCATION31256:
		{
			return MONGO_CODE_LOCATION31256;
		}

		case ERRCODE_HELIO_LOCATION31271:
		{
			return MONGO_CODE_LOCATION31271;
		}

		case ERRCODE_HELIO_LOCATION31276:
		{
			return MONGO_CODE_LOCATION31276;
		}

		case ERRCODE_HELIO_LOCATION31308:
		{
			return MONGO_CODE_LOCATION31308;
		}

		case ERRCODE_HELIO_LOCATION31325:
		{
			return MONGO_CODE_LOCATION31325;
		}

		case ERRCODE_HELIO_LOCATION31393:
		{
			return MONGO_CODE_LOCATION31393;
		}

		case ERRCODE_HELIO_LOCATION31395:
		{
			return MONGO_CODE_LOCATION31395;
		}

		case ERRCODE_HELIO_LOCATION34435:
		{
			return MONGO_CODE_LOCATION34435;
		}

		case ERRCODE_HELIO_LOCATION31441:
		{
			return MONGO_CODE_LOCATION31441;
		}

		case ERRCODE_HELIO_LOCATION34443:
		{
			return MONGO_CODE_LOCATION34443;
		}

		case ERRCODE_HELIO_LOCATION34444:
		{
			return MONGO_CODE_LOCATION34444;
		}

		case ERRCODE_HELIO_LOCATION34445:
		{
			return MONGO_CODE_LOCATION34445;
		}

		case ERRCODE_HELIO_LOCATION34446:
		{
			return MONGO_CODE_LOCATION34446;
		}

		case ERRCODE_HELIO_LOCATION34447:
		{
			return MONGO_CODE_LOCATION34447;
		}

		case ERRCODE_HELIO_LOCATION34448:
		{
			return MONGO_CODE_LOCATION34448;
		}

		case ERRCODE_HELIO_LOCATION34449:
		{
			return MONGO_CODE_LOCATION34449;
		}

		case ERRCODE_HELIO_LOCATION34450:
		{
			return MONGO_CODE_LOCATION34450;
		}

		case ERRCODE_HELIO_LOCATION34451:
		{
			return MONGO_CODE_LOCATION34451;
		}

		case ERRCODE_HELIO_LOCATION34452:
		{
			return MONGO_CODE_LOCATION34452;
		}

		case ERRCODE_HELIO_LOCATION34453:
		{
			return MONGO_CODE_LOCATION34453;
		}

		case ERRCODE_HELIO_LOCATION34454:
		{
			return MONGO_CODE_LOCATION34454;
		}

		case ERRCODE_HELIO_LOCATION34455:
		{
			return MONGO_CODE_LOCATION34455;
		}

		case ERRCODE_HELIO_LOCATION34460:
		{
			return MONGO_CODE_LOCATION34460;
		}

		case ERRCODE_HELIO_LOCATION34461:
		{
			return MONGO_CODE_LOCATION34461;
		}

		case ERRCODE_HELIO_LOCATION34462:
		{
			return MONGO_CODE_LOCATION34462;
		}

		case ERRCODE_HELIO_LOCATION34463:
		{
			return MONGO_CODE_LOCATION34463;
		}

		case ERRCODE_HELIO_LOCATION34464:
		{
			return MONGO_CODE_LOCATION34464;
		}

		case ERRCODE_HELIO_LOCATION34465:
		{
			return MONGO_CODE_LOCATION34465;
		}

		case ERRCODE_HELIO_LOCATION34466:
		{
			return MONGO_CODE_LOCATION34466;
		}

		case ERRCODE_HELIO_LOCATION34467:
		{
			return MONGO_CODE_LOCATION34467;
		}

		case ERRCODE_HELIO_LOCATION34468:
		{
			return MONGO_CODE_LOCATION34468;
		}

		case ERRCODE_HELIO_LOCATION34471:
		{
			return MONGO_CODE_LOCATION34471;
		}

		case ERRCODE_HELIO_LOCATION34473:
		{
			return MONGO_CODE_LOCATION34473;
		}

		case ERRCODE_HELIO_DOLLARSWITCHREQUIRESOBJECT:
		{
			return MONGO_CODE_DOLLARSWITCHREQUIRESOBJECT;
		}

		case ERRCODE_HELIO_DOLLARSWITCHREQUIRESARRAYFORBRANCHES:
		{
			return MONGO_CODE_DOLLARSWITCHREQUIRESARRAYFORBRANCHES;
		}

		case ERRCODE_HELIO_DOLLARSWITCHREQUIRESOBJECTFOREACHBRANCH:
		{
			return MONGO_CODE_DOLLARSWITCHREQUIRESOBJECTFOREACHBRANCH;
		}

		case ERRCODE_HELIO_DOLLARSWITCHUNKNOWNARGUMENTFORBRANCH:
		{
			return MONGO_CODE_DOLLARSWITCHUNKNOWNARGUMENTFORBRANCH;
		}

		case ERRCODE_HELIO_DOLLARSWITCHREQUIRESCASEEXPRESSIONFORBRANCH:
		{
			return MONGO_CODE_DOLLARSWITCHREQUIRESCASEEXPRESSIONFORBRANCH;
		}

		case ERRCODE_HELIO_DOLLARSWITCHREQUIRESTHENEXPRESSIONFORBRANCH:
		{
			return MONGO_CODE_DOLLARSWITCHREQUIRESTHENEXPRESSIONFORBRANCH;
		}

		case ERRCODE_HELIO_DOLLARSWITCHNOMATCHINGBRANCHANDNODEFAULT:
		{
			return MONGO_CODE_DOLLARSWITCHNOMATCHINGBRANCHANDNODEFAULT;
		}

		case ERRCODE_HELIO_DOLLARSWITCHBADARGUMENT:
		{
			return MONGO_CODE_DOLLARSWITCHBADARGUMENT;
		}

		case ERRCODE_HELIO_DOLLARSWITCHREQUIRESATLEASTONEBRANCH:
		{
			return MONGO_CODE_DOLLARSWITCHREQUIRESATLEASTONEBRANCH;
		}

		case ERRCODE_HELIO_LOCATION40075:
		{
			return MONGO_CODE_LOCATION40075;
		}

		case ERRCODE_HELIO_LOCATION40076:
		{
			return MONGO_CODE_LOCATION40076;
		}

		case ERRCODE_HELIO_LOCATION40077:
		{
			return MONGO_CODE_LOCATION40077;
		}

		case ERRCODE_HELIO_LOCATION40078:
		{
			return MONGO_CODE_LOCATION40078;
		}

		case ERRCODE_HELIO_LOCATION40079:
		{
			return MONGO_CODE_LOCATION40079;
		}

		case ERRCODE_HELIO_LOCATION40080:
		{
			return MONGO_CODE_LOCATION40080;
		}

		case ERRCODE_HELIO_DOLLARINREQUIRESARRAY:
		{
			return MONGO_CODE_DOLLARINREQUIRESARRAY;
		}

		case ERRCODE_HELIO_LOCATION40085:
		{
			return MONGO_CODE_LOCATION40085;
		}

		case ERRCODE_HELIO_LOCATION40086:
		{
			return MONGO_CODE_LOCATION40086;
		}

		case ERRCODE_HELIO_LOCATION40087:
		{
			return MONGO_CODE_LOCATION40087;
		}

		case ERRCODE_HELIO_LOCATION40090:
		{
			return MONGO_CODE_LOCATION40090;
		}

		case ERRCODE_HELIO_LOCATION40091:
		{
			return MONGO_CODE_LOCATION40091;
		}

		case ERRCODE_HELIO_LOCATION40092:
		{
			return MONGO_CODE_LOCATION40092;
		}

		case ERRCODE_HELIO_LOCATION40093:
		{
			return MONGO_CODE_LOCATION40093;
		}

		case ERRCODE_HELIO_LOCATION40094:
		{
			return MONGO_CODE_LOCATION40094;
		}

		case ERRCODE_HELIO_LOCATION40096:
		{
			return MONGO_CODE_LOCATION40096;
		}

		case ERRCODE_HELIO_LOCATION40097:
		{
			return MONGO_CODE_LOCATION40097;
		}

		case ERRCODE_HELIO_LOCATION40100:
		{
			return MONGO_CODE_LOCATION40100;
		}

		case ERRCODE_HELIO_LOCATION40101:
		{
			return MONGO_CODE_LOCATION40101;
		}

		case ERRCODE_HELIO_LOCATION40102:
		{
			return MONGO_CODE_LOCATION40102;
		}

		case ERRCODE_HELIO_LOCATION40103:
		{
			return MONGO_CODE_LOCATION40103;
		}

		case ERRCODE_HELIO_LOCATION40104:
		{
			return MONGO_CODE_LOCATION40104;
		}

		case ERRCODE_HELIO_LOCATION40105:
		{
			return MONGO_CODE_LOCATION40105;
		}

		case ERRCODE_HELIO_LOCATION40147:
		{
			return MONGO_CODE_LOCATION40147;
		}

		case ERRCODE_HELIO_LOCATION40156:
		{
			return MONGO_CODE_LOCATION40156;
		}

		case ERRCODE_HELIO_LOCATION40158:
		{
			return MONGO_CODE_LOCATION40158;
		}

		case ERRCODE_HELIO_LOCATION40160:
		{
			return MONGO_CODE_LOCATION40160;
		}

		case ERRCODE_HELIO_LOCATION40169:
		{
			return MONGO_CODE_LOCATION40169;
		}

		case ERRCODE_HELIO_LOCATION40177:
		{
			return MONGO_CODE_LOCATION40177;
		}

		case ERRCODE_HELIO_LOCATION40185:
		{
			return MONGO_CODE_LOCATION40185;
		}

		case ERRCODE_HELIO_LOCATION40191:
		{
			return MONGO_CODE_LOCATION40191;
		}

		case ERRCODE_HELIO_LOCATION40192:
		{
			return MONGO_CODE_LOCATION40192;
		}

		case ERRCODE_HELIO_LOCATION40193:
		{
			return MONGO_CODE_LOCATION40193;
		}

		case ERRCODE_HELIO_LOCATION40194:
		{
			return MONGO_CODE_LOCATION40194;
		}

		case ERRCODE_HELIO_LOCATION40195:
		{
			return MONGO_CODE_LOCATION40195;
		}

		case ERRCODE_HELIO_LOCATION40196:
		{
			return MONGO_CODE_LOCATION40196;
		}

		case ERRCODE_HELIO_LOCATION40197:
		{
			return MONGO_CODE_LOCATION40197;
		}

		case ERRCODE_HELIO_LOCATION40198:
		{
			return MONGO_CODE_LOCATION40198;
		}

		case ERRCODE_HELIO_LOCATION40199:
		{
			return MONGO_CODE_LOCATION40199;
		}

		case ERRCODE_HELIO_LOCATION40200:
		{
			return MONGO_CODE_LOCATION40200;
		}

		case ERRCODE_HELIO_LOCATION40201:
		{
			return MONGO_CODE_LOCATION40201;
		}

		case ERRCODE_HELIO_LOCATION40202:
		{
			return MONGO_CODE_LOCATION40202;
		}

		case ERRCODE_HELIO_LOCATION40218:
		{
			return MONGO_CODE_LOCATION40218;
		}

		case ERRCODE_HELIO_LOCATION40228:
		{
			return MONGO_CODE_LOCATION40228;
		}

		case ERRCODE_HELIO_LOCATION40234:
		{
			return MONGO_CODE_LOCATION40234;
		}

		case ERRCODE_HELIO_LOCATION40238:
		{
			return MONGO_CODE_LOCATION40238;
		}

		case ERRCODE_HELIO_LOCATION40272:
		{
			return MONGO_CODE_LOCATION40272;
		}

		case ERRCODE_HELIO_LOCATION40319:
		{
			return MONGO_CODE_LOCATION40319;
		}

		case ERRCODE_HELIO_LOCATION40321:
		{
			return MONGO_CODE_LOCATION40321;
		}

		case ERRCODE_HELIO_LOCATION40323:
		{
			return MONGO_CODE_LOCATION40323;
		}

		case ERRCODE_HELIO_UNRECOGNIZEDCOMMAND:
		{
			return MONGO_CODE_UNRECOGNIZEDCOMMAND;
		}

		case ERRCODE_HELIO_LOCATION40352:
		{
			return MONGO_CODE_LOCATION40352;
		}

		case ERRCODE_HELIO_DOLLARARRAYTOOBJECTREQUIRESARRAY:
		{
			return MONGO_CODE_DOLLARARRAYTOOBJECTREQUIRESARRAY;
		}

		case ERRCODE_HELIO_DOLLAROBJECTTOARRAYREQUIRESOBJECT:
		{
			return MONGO_CODE_DOLLAROBJECTTOARRAYREQUIRESOBJECT;
		}

		case ERRCODE_HELIO_DOLLARARRAYTOOBJECTALLMUSTBEOBJECTS:
		{
			return MONGO_CODE_DOLLARARRAYTOOBJECTALLMUSTBEOBJECTS;
		}

		case ERRCODE_HELIO_DOLLARARRAYTOOBJECTINCORRECTNUMBEROFKEYS:
		{
			return MONGO_CODE_DOLLARARRAYTOOBJECTINCORRECTNUMBEROFKEYS;
		}

		case ERRCODE_HELIO_DOLLARARRAYTOOBJECTREQUIRESOBJECTWITHKANDV:
		{
			return MONGO_CODE_DOLLARARRAYTOOBJECTREQUIRESOBJECTWITHKANDV;
		}

		case ERRCODE_HELIO_DOLLARARRAYTOOBJECTOBJECTKEYMUSTBESTRING:
		{
			return MONGO_CODE_DOLLARARRAYTOOBJECTOBJECTKEYMUSTBESTRING;
		}

		case ERRCODE_HELIO_DOLLARARRAYTOOBJECTARRAYKEYMUSTBESTRING:
		{
			return MONGO_CODE_DOLLARARRAYTOOBJECTARRAYKEYMUSTBESTRING;
		}

		case ERRCODE_HELIO_DOLLARARRAYTOOBJECTALLMUSTBEARRAYS:
		{
			return MONGO_CODE_DOLLARARRAYTOOBJECTALLMUSTBEARRAYS;
		}

		case ERRCODE_HELIO_DOLLARARRAYTOOBJECTINCORRECTARRAYLENGTH:
		{
			return MONGO_CODE_DOLLARARRAYTOOBJECTINCORRECTARRAYLENGTH;
		}

		case ERRCODE_HELIO_DOLLARARRAYTOOBJECTBADINPUTTYPEFORMAT:
		{
			return MONGO_CODE_DOLLARARRAYTOOBJECTBADINPUTTYPEFORMAT;
		}

		case ERRCODE_HELIO_DOLLARMERGEOBJECTSINVALIDTYPE:
		{
			return MONGO_CODE_DOLLARMERGEOBJECTSINVALIDTYPE;
		}

		case ERRCODE_HELIO_LOCATION40414:
		{
			return MONGO_CODE_LOCATION40414;
		}

		case ERRCODE_HELIO_UNKNOWNBSONFIELD:
		{
			return MONGO_CODE_UNKNOWNBSONFIELD;
		}

		case ERRCODE_HELIO_LOCATION40485:
		{
			return MONGO_CODE_LOCATION40485;
		}

		case ERRCODE_HELIO_LOCATION40489:
		{
			return MONGO_CODE_LOCATION40489;
		}

		case ERRCODE_HELIO_LOCATION40515:
		{
			return MONGO_CODE_LOCATION40515;
		}

		case ERRCODE_HELIO_LOCATION40516:
		{
			return MONGO_CODE_LOCATION40516;
		}

		case ERRCODE_HELIO_LOCATION40517:
		{
			return MONGO_CODE_LOCATION40517;
		}

		case ERRCODE_HELIO_LOCATION40518:
		{
			return MONGO_CODE_LOCATION40518;
		}

		case ERRCODE_HELIO_LOCATION40519:
		{
			return MONGO_CODE_LOCATION40519;
		}

		case ERRCODE_HELIO_LOCATION40520:
		{
			return MONGO_CODE_LOCATION40520;
		}

		case ERRCODE_HELIO_LOCATION40521:
		{
			return MONGO_CODE_LOCATION40521;
		}

		case ERRCODE_HELIO_LOCATION40522:
		{
			return MONGO_CODE_LOCATION40522;
		}

		case ERRCODE_HELIO_LOCATION40523:
		{
			return MONGO_CODE_LOCATION40523;
		}

		case ERRCODE_HELIO_LOCATION40524:
		{
			return MONGO_CODE_LOCATION40524;
		}

		case ERRCODE_HELIO_LOCATION40525:
		{
			return MONGO_CODE_LOCATION40525;
		}

		case ERRCODE_HELIO_LOCATION40533:
		{
			return MONGO_CODE_LOCATION40533;
		}

		case ERRCODE_HELIO_LOCATION40535:
		{
			return MONGO_CODE_LOCATION40535;
		}

		case ERRCODE_HELIO_LOCATION40536:
		{
			return MONGO_CODE_LOCATION40536;
		}

		case ERRCODE_HELIO_LOCATION40539:
		{
			return MONGO_CODE_LOCATION40539;
		}

		case ERRCODE_HELIO_LOCATION40540:
		{
			return MONGO_CODE_LOCATION40540;
		}

		case ERRCODE_HELIO_LOCATION40541:
		{
			return MONGO_CODE_LOCATION40541;
		}

		case ERRCODE_HELIO_LOCATION40542:
		{
			return MONGO_CODE_LOCATION40542;
		}

		case ERRCODE_HELIO_LOCATION40600:
		{
			return MONGO_CODE_LOCATION40600;
		}

		case ERRCODE_HELIO_LOCATION40601:
		{
			return MONGO_CODE_LOCATION40601;
		}

		case ERRCODE_HELIO_LOCATION40602:
		{
			return MONGO_CODE_LOCATION40602;
		}

		case ERRCODE_HELIO_LOCATION40603:
		{
			return MONGO_CODE_LOCATION40603;
		}

		case ERRCODE_HELIO_LOCATION40235:
		{
			return MONGO_CODE_LOCATION40235;
		}

		case ERRCODE_HELIO_LOCATION40237:
		{
			return MONGO_CODE_LOCATION40237;
		}

		case ERRCODE_HELIO_CHANGESTREAMBADRESUMETOKEN:
		{
			return MONGO_CODE_CHANGESTREAMBADRESUMETOKEN;
		}

		case ERRCODE_HELIO_LOCATION40684:
		{
			return MONGO_CODE_LOCATION40684;
		}

		case ERRCODE_HELIO_LOCATION50694:
		{
			return MONGO_CODE_LOCATION50694;
		}

		case ERRCODE_HELIO_LOCATION50695:
		{
			return MONGO_CODE_LOCATION50695;
		}

		case ERRCODE_HELIO_LOCATION50696:
		{
			return MONGO_CODE_LOCATION50696;
		}

		case ERRCODE_HELIO_LOCATION50699:
		{
			return MONGO_CODE_LOCATION50699;
		}

		case ERRCODE_HELIO_LOCATION50700:
		{
			return MONGO_CODE_LOCATION50700;
		}

		case ERRCODE_HELIO_LOCATION50723:
		{
			return MONGO_CODE_LOCATION50723;
		}

		case ERRCODE_HELIO_LOCATION50752:
		{
			return MONGO_CODE_LOCATION50752;
		}

		case ERRCODE_HELIO_LOCATION50759:
		{
			return MONGO_CODE_LOCATION50759;
		}

		case ERRCODE_HELIO_LOCATION51024:
		{
			return MONGO_CODE_LOCATION51024;
		}

		case ERRCODE_HELIO_LOCATION51047:
		{
			return MONGO_CODE_LOCATION51047;
		}

		case ERRCODE_HELIO_LOCATION51074:
		{
			return MONGO_CODE_LOCATION51074;
		}

		case ERRCODE_HELIO_LOCATION51075:
		{
			return MONGO_CODE_LOCATION51075;
		}

		case ERRCODE_HELIO_DOLLARROUNDOVERFLOWINT64:
		{
			return MONGO_CODE_DOLLARROUNDOVERFLOWINT64;
		}

		case ERRCODE_HELIO_DOLLARROUNDFIRSTARGMUSTBENUMERIC:
		{
			return MONGO_CODE_DOLLARROUNDFIRSTARGMUSTBENUMERIC;
		}

		case ERRCODE_HELIO_DOLLARROUNDPRECISIONMUSTBEINTEGRAL:
		{
			return MONGO_CODE_DOLLARROUNDPRECISIONMUSTBEINTEGRAL;
		}

		case ERRCODE_HELIO_DOLLARROUNDPRECISIONOUTOFRANGE:
		{
			return MONGO_CODE_DOLLARROUNDPRECISIONOUTOFRANGE;
		}

		case ERRCODE_HELIO_LOCATION51091:
		{
			return MONGO_CODE_LOCATION51091;
		}

		case ERRCODE_HELIO_LOCATION51103:
		{
			return MONGO_CODE_LOCATION51103;
		}

		case ERRCODE_HELIO_LOCATION51104:
		{
			return MONGO_CODE_LOCATION51104;
		}

		case ERRCODE_HELIO_LOCATION51105:
		{
			return MONGO_CODE_LOCATION51105;
		}

		case ERRCODE_HELIO_LOCATION51106:
		{
			return MONGO_CODE_LOCATION51106;
		}

		case ERRCODE_HELIO_LOCATION51107:
		{
			return MONGO_CODE_LOCATION51107;
		}

		case ERRCODE_HELIO_LOCATION51108:
		{
			return MONGO_CODE_LOCATION51108;
		}

		case ERRCODE_HELIO_LOCATION51109:
		{
			return MONGO_CODE_LOCATION51109;
		}

		case ERRCODE_HELIO_LOCATION51110:
		{
			return MONGO_CODE_LOCATION51110;
		}

		case ERRCODE_HELIO_LOCATION51111:
		{
			return MONGO_CODE_LOCATION51111;
		}

		case ERRCODE_HELIO_LOCATION51132:
		{
			return MONGO_CODE_LOCATION51132;
		}

		case ERRCODE_HELIO_LOCATION51134:
		{
			return MONGO_CODE_LOCATION51134;
		}

		case ERRCODE_HELIO_LOCATION51151:
		{
			return MONGO_CODE_LOCATION51151;
		}

		case ERRCODE_HELIO_LOCATION51156:
		{
			return MONGO_CODE_LOCATION51156;
		}

		case ERRCODE_HELIO_LOCATION51178:
		{
			return MONGO_CODE_LOCATION51178;
		}

		case ERRCODE_HELIO_LOCATION51183:
		{
			return MONGO_CODE_LOCATION51183;
		}

		case ERRCODE_HELIO_LOCATION51185:
		{
			return MONGO_CODE_LOCATION51185;
		}

		case ERRCODE_HELIO_LOCATION51186:
		{
			return MONGO_CODE_LOCATION51186;
		}

		case ERRCODE_HELIO_LOCATION51187:
		{
			return MONGO_CODE_LOCATION51187;
		}

		case ERRCODE_HELIO_LOCATION51191:
		{
			return MONGO_CODE_LOCATION51191;
		}

		case ERRCODE_HELIO_LOCATION51246:
		{
			return MONGO_CODE_LOCATION51246;
		}

		case ERRCODE_HELIO_LOCATION51276:
		{
			return MONGO_CODE_LOCATION51276;
		}

		case ERRCODE_HELIO_LOCATION51247:
		{
			return MONGO_CODE_LOCATION51247;
		}

		case ERRCODE_HELIO_LOCATION51743:
		{
			return MONGO_CODE_LOCATION51743;
		}

		case ERRCODE_HELIO_LOCATION51744:
		{
			return MONGO_CODE_LOCATION51744;
		}

		case ERRCODE_HELIO_LOCATION51745:
		{
			return MONGO_CODE_LOCATION51745;
		}

		case ERRCODE_HELIO_LOCATION51746:
		{
			return MONGO_CODE_LOCATION51746;
		}

		case ERRCODE_HELIO_LOCATION51747:
		{
			return MONGO_CODE_LOCATION51747;
		}

		case ERRCODE_HELIO_LOCATION51748:
		{
			return MONGO_CODE_LOCATION51748;
		}

		case ERRCODE_HELIO_LOCATION51749:
		{
			return MONGO_CODE_LOCATION51749;
		}

		case ERRCODE_HELIO_LOCATION51750:
		{
			return MONGO_CODE_LOCATION51750;
		}

		case ERRCODE_HELIO_LOCATION51751:
		{
			return MONGO_CODE_LOCATION51751;
		}

		case ERRCODE_HELIO_LOCATION327391:
		{
			return MONGO_CODE_LOCATION327391;
		}

		case ERRCODE_HELIO_LOCATION327392:
		{
			return MONGO_CODE_LOCATION327392;
		}

		case ERRCODE_HELIO_DOLLARIFNULLREQUIRESATLEASTTWOARGS:
		{
			return MONGO_CODE_DOLLARIFNULLREQUIRESATLEASTTWOARGS;
		}

		case ERRCODE_HELIO_DOLLARRANDNONEMPTYARGUMENT:
		{
			return MONGO_CODE_DOLLARRANDNONEMPTYARGUMENT;
		}

		case ERRCODE_HELIO_INTERMEDIATERESULTTOOLARGE:
		{
			return MONGO_CODE_INTERMEDIATERESULTTOOLARGE;
		}

		case ERRCODE_HELIO_DOLLARSETFIELDREQUIRESOBJECT:
		{
			return MONGO_CODE_DOLLARSETFIELDREQUIRESOBJECT;
		}

		case ERRCODE_HELIO_DOLLARSETFIELDUNKNOWNARGUMENT:
		{
			return MONGO_CODE_DOLLARSETFIELDUNKNOWNARGUMENT;
		}

		case ERRCODE_HELIO_LOCATION2942500:
		{
			return MONGO_CODE_LOCATION2942500;
		}

		case ERRCODE_HELIO_LOCATION2942501:
		{
			return MONGO_CODE_LOCATION2942501;
		}

		case ERRCODE_HELIO_LOCATION2942502:
		{
			return MONGO_CODE_LOCATION2942502;
		}

		case ERRCODE_HELIO_LOCATION2942503:
		{
			return MONGO_CODE_LOCATION2942503;
		}

		case ERRCODE_HELIO_LOCATION2942504:
		{
			return MONGO_CODE_LOCATION2942504;
		}

		case ERRCODE_HELIO_LOCATION2942505:
		{
			return MONGO_CODE_LOCATION2942505;
		}

		case ERRCODE_HELIO_LOCATION2942506:
		{
			return MONGO_CODE_LOCATION2942506;
		}

		case ERRCODE_HELIO_LOCATION3041701:
		{
			return MONGO_CODE_LOCATION3041701;
		}

		case ERRCODE_HELIO_LOCATION3041702:
		{
			return MONGO_CODE_LOCATION3041702;
		}

		case ERRCODE_HELIO_LOCATION3041703:
		{
			return MONGO_CODE_LOCATION3041703;
		}

		case ERRCODE_HELIO_LOCATION4161102:
		{
			return MONGO_CODE_LOCATION4161102;
		}

		case ERRCODE_HELIO_LOCATION4161103:
		{
			return MONGO_CODE_LOCATION4161103;
		}

		case ERRCODE_HELIO_LOCATION4161104:
		{
			return MONGO_CODE_LOCATION4161104;
		}

		case ERRCODE_HELIO_LOCATION4161105:
		{
			return MONGO_CODE_LOCATION4161105;
		}

		case ERRCODE_HELIO_LOCATION4161106:
		{
			return MONGO_CODE_LOCATION4161106;
		}

		case ERRCODE_HELIO_LOCATION4161107:
		{
			return MONGO_CODE_LOCATION4161107;
		}

		case ERRCODE_HELIO_LOCATION4161108:
		{
			return MONGO_CODE_LOCATION4161108;
		}

		case ERRCODE_HELIO_LOCATION4161109:
		{
			return MONGO_CODE_LOCATION4161109;
		}

		case ERRCODE_HELIO_LOCATION4890500:
		{
			return MONGO_CODE_LOCATION4890500;
		}

		case ERRCODE_HELIO_LOCATION4940400:
		{
			return MONGO_CODE_LOCATION4940400;
		}

		case ERRCODE_HELIO_LOCATION4940401:
		{
			return MONGO_CODE_LOCATION4940401;
		}

		case ERRCODE_HELIO_LOCATION5166400:
		{
			return MONGO_CODE_LOCATION5166400;
		}

		case ERRCODE_HELIO_LOCATION5166401:
		{
			return MONGO_CODE_LOCATION5166401;
		}

		case ERRCODE_HELIO_LOCATION5166402:
		{
			return MONGO_CODE_LOCATION5166402;
		}

		case ERRCODE_HELIO_LOCATION5166403:
		{
			return MONGO_CODE_LOCATION5166403;
		}

		case ERRCODE_HELIO_LOCATION5166404:
		{
			return MONGO_CODE_LOCATION5166404;
		}

		case ERRCODE_HELIO_LOCATION5166405:
		{
			return MONGO_CODE_LOCATION5166405;
		}

		case ERRCODE_HELIO_LOCATION5166406:
		{
			return MONGO_CODE_LOCATION5166406;
		}

		case ERRCODE_HELIO_LOCATION5107200:
		{
			return MONGO_CODE_LOCATION5107200;
		}

		case ERRCODE_HELIO_LOCATION5107201:
		{
			return MONGO_CODE_LOCATION5107201;
		}

		case ERRCODE_HELIO_LOCATION5166301:
		{
			return MONGO_CODE_LOCATION5166301;
		}

		case ERRCODE_HELIO_LOCATION5166302:
		{
			return MONGO_CODE_LOCATION5166302;
		}

		case ERRCODE_HELIO_LOCATION5166303:
		{
			return MONGO_CODE_LOCATION5166303;
		}

		case ERRCODE_HELIO_LOCATION5166304:
		{
			return MONGO_CODE_LOCATION5166304;
		}

		case ERRCODE_HELIO_LOCATION5166305:
		{
			return MONGO_CODE_LOCATION5166305;
		}

		case ERRCODE_HELIO_LOCATION5166307:
		{
			return MONGO_CODE_LOCATION5166307;
		}

		case ERRCODE_HELIO_LOCATION5339900:
		{
			return MONGO_CODE_LOCATION5339900;
		}

		case ERRCODE_HELIO_LOCATION5339901:
		{
			return MONGO_CODE_LOCATION5339901;
		}

		case ERRCODE_HELIO_LOCATION5339902:
		{
			return MONGO_CODE_LOCATION5339902;
		}

		case ERRCODE_HELIO_LOCATION5429413:
		{
			return MONGO_CODE_LOCATION5429413;
		}

		case ERRCODE_HELIO_LOCATION5429414:
		{
			return MONGO_CODE_LOCATION5429414;
		}

		case ERRCODE_HELIO_LOCATION5429513:
		{
			return MONGO_CODE_LOCATION5429513;
		}

		case ERRCODE_HELIO_LOCATION5439007:
		{
			return MONGO_CODE_LOCATION5439007;
		}

		case ERRCODE_HELIO_LOCATION5439008:
		{
			return MONGO_CODE_LOCATION5439008;
		}

		case ERRCODE_HELIO_LOCATION5439009:
		{
			return MONGO_CODE_LOCATION5439009;
		}

		case ERRCODE_HELIO_LOCATION5439010:
		{
			return MONGO_CODE_LOCATION5439010;
		}

		case ERRCODE_HELIO_LOCATION5439012:
		{
			return MONGO_CODE_LOCATION5439012;
		}

		case ERRCODE_HELIO_LOCATION5439013:
		{
			return MONGO_CODE_LOCATION5439013;
		}

		case ERRCODE_HELIO_LOCATION5439014:
		{
			return MONGO_CODE_LOCATION5439014;
		}

		case ERRCODE_HELIO_LOCATION5439015:
		{
			return MONGO_CODE_LOCATION5439015;
		}

		case ERRCODE_HELIO_LOCATION5439016:
		{
			return MONGO_CODE_LOCATION5439016;
		}

		case ERRCODE_HELIO_LOCATION5439017:
		{
			return MONGO_CODE_LOCATION5439017;
		}

		case ERRCODE_HELIO_LOCATION5439018:
		{
			return MONGO_CODE_LOCATION5439018;
		}

		case ERRCODE_HELIO_LOCATION5626500:
		{
			return MONGO_CODE_LOCATION5626500;
		}

		case ERRCODE_HELIO_LOCATION5654600:
		{
			return MONGO_CODE_LOCATION5654600;
		}

		case ERRCODE_HELIO_LOCATION5654601:
		{
			return MONGO_CODE_LOCATION5654601;
		}

		case ERRCODE_HELIO_LOCATION5654602:
		{
			return MONGO_CODE_LOCATION5654602;
		}

		case ERRCODE_HELIO_LOCATION5687301:
		{
			return MONGO_CODE_LOCATION5687301;
		}

		case ERRCODE_HELIO_LOCATION5687302:
		{
			return MONGO_CODE_LOCATION5687302;
		}

		case ERRCODE_HELIO_LOCATION5687400:
		{
			return MONGO_CODE_LOCATION5687400;
		}

		case ERRCODE_HELIO_LOCATION5687401:
		{
			return MONGO_CODE_LOCATION5687401;
		}

		case ERRCODE_HELIO_LOCATION5746102:
		{
			return MONGO_CODE_LOCATION5746102;
		}

		case ERRCODE_HELIO_LOCATION5787801:
		{
			return MONGO_CODE_LOCATION5787801;
		}

		case ERRCODE_HELIO_LOCATION5787900:
		{
			return MONGO_CODE_LOCATION5787900;
		}

		case ERRCODE_HELIO_LOCATION5787901:
		{
			return MONGO_CODE_LOCATION5787901;
		}

		case ERRCODE_HELIO_LOCATION5787902:
		{
			return MONGO_CODE_LOCATION5787902;
		}

		case ERRCODE_HELIO_LOCATION5787903:
		{
			return MONGO_CODE_LOCATION5787903;
		}

		case ERRCODE_HELIO_LOCATION5787906:
		{
			return MONGO_CODE_LOCATION5787906;
		}

		case ERRCODE_HELIO_LOCATION5787907:
		{
			return MONGO_CODE_LOCATION5787907;
		}

		case ERRCODE_HELIO_LOCATION5787908:
		{
			return MONGO_CODE_LOCATION5787908;
		}

		case ERRCODE_HELIO_LOCATION5788200:
		{
			return MONGO_CODE_LOCATION5788200;
		}

		case ERRCODE_HELIO_LOCATION5858203:
		{
			return MONGO_CODE_LOCATION5858203;
		}

		case ERRCODE_HELIO_LOCATION5976500:
		{
			return MONGO_CODE_LOCATION5976500;
		}

		case ERRCODE_HELIO_LOCATION5371601:
		{
			return MONGO_CODE_LOCATION5371601;
		}

		case ERRCODE_HELIO_LOCATION5371602:
		{
			return MONGO_CODE_LOCATION5371602;
		}

		case ERRCODE_HELIO_LOCATION5371603:
		{
			return MONGO_CODE_LOCATION5371603;
		}

		case ERRCODE_HELIO_DOCUMENTFAILEDVALIDATION:
		{
			return MONGO_CODE_DOCUMENTFAILEDVALIDATION;
		}

		case ERRCODE_HELIO_LOCATION605001:
		{
			return MONGO_CODE_LOCATION605001;
		}

		case ERRCODE_HELIO_LOCATION6050106:
		{
			return MONGO_CODE_LOCATION6050106;
		}

		case ERRCODE_HELIO_LOCATION16990:
		{
			return MONGO_CODE_LOCATION16990;
		}

		case ERRCODE_HELIO_LOCATION13111:
		{
			return MONGO_CODE_LOCATION13111;
		}

		case ERRCODE_HELIO_LOCATION5788001:
		{
			return MONGO_CODE_LOCATION5788001;
		}

		case ERRCODE_HELIO_LOCATION5788002:
		{
			return MONGO_CODE_LOCATION5788002;
		}

		case ERRCODE_HELIO_LOCATION5788003:
		{
			return MONGO_CODE_LOCATION5788003;
		}

		case ERRCODE_HELIO_LOCATION5788004:
		{
			return MONGO_CODE_LOCATION5788004;
		}

		case ERRCODE_HELIO_LOCATION5788005:
		{
			return MONGO_CODE_LOCATION5788005;
		}

		case ERRCODE_HELIO_LOCATION5733201:
		{
			return MONGO_CODE_LOCATION5733201;
		}

		case ERRCODE_HELIO_LOCATION5733401:
		{
			return MONGO_CODE_LOCATION5733401;
		}

		case ERRCODE_HELIO_LOCATION5733402:
		{
			return MONGO_CODE_LOCATION5733402;
		}

		case ERRCODE_HELIO_LOCATION5733403:
		{
			return MONGO_CODE_LOCATION5733403;
		}

		case ERRCODE_HELIO_LOCATION5733406:
		{
			return MONGO_CODE_LOCATION5733406;
		}

		case ERRCODE_HELIO_LOCATION5733408:
		{
			return MONGO_CODE_LOCATION5733408;
		}

		case ERRCODE_HELIO_LOCATION5733409:
		{
			return MONGO_CODE_LOCATION5733409;
		}

		case ERRCODE_HELIO_LOCATION5876900:
		{
			return MONGO_CODE_LOCATION5876900;
		}

		case ERRCODE_HELIO_LOCATION5897900:
		{
			return MONGO_CODE_LOCATION5897900;
		}

		case ERRCODE_HELIO_LOCATION5946802:
		{
			return MONGO_CODE_LOCATION5946802;
		}

		case ERRCODE_HELIO_LOCATION6007200:
		{
			return MONGO_CODE_LOCATION6007200;
		}

		case ERRCODE_HELIO_LOCATION6053600:
		{
			return MONGO_CODE_LOCATION6053600;
		}

		case ERRCODE_HELIO_LOCATION6586400:
		{
			return MONGO_CODE_LOCATION6586400;
		}

		case ERRCODE_HELIO_LOCATION8993000:
		{
			return MONGO_CODE_LOCATION8993000;
		}

		case ERRCODE_HELIO_LOCATION5423900:
		{
			return MONGO_CODE_LOCATION5423900;
		}

		case ERRCODE_HELIO_LOCATION5423901:
		{
			return MONGO_CODE_LOCATION5423901;
		}

		case ERRCODE_HELIO_LOCATION5423902:
		{
			return MONGO_CODE_LOCATION5423902;
		}

		case ERRCODE_HELIO_LOCATION5490710:
		{
			return MONGO_CODE_LOCATION5490710;
		}

		case ERRCODE_HELIO_LOCATION5624900:
		{
			return MONGO_CODE_LOCATION5624900;
		}

		case ERRCODE_HELIO_LOCATION5624901:
		{
			return MONGO_CODE_LOCATION5624901;
		}

		case ERRCODE_HELIO_LOCATION6050202:
		{
			return MONGO_CODE_LOCATION6050202;
		}

		case ERRCODE_HELIO_LOCATION6050204:
		{
			return MONGO_CODE_LOCATION6050204;
		}

		case ERRCODE_HELIO_LOCATION5788604:
		{
			return MONGO_CODE_LOCATION5788604;
		}

		case ERRCODE_HELIO_LOCATION31170:
		{
			return MONGO_CODE_LOCATION31170;
		}

		default:
		{
			ereport(ERROR, (errcode(ERRCODE_HELIO_INTERNALERROR),
							errmsg("Unknown error code %d", sqlStateError)));
		}
	}
}
