[alias]
b = "build --features"
c = "check --features"
t = "test --features"
r = "run --features"

[target.'cfg(target_os="macos")']
# Postgres symbols won't be available until runtime
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup"]
