#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for ybgate
#
# IDENTIFICATION
#    src/backend/ybgate/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/ybgate
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = ybgate_api.o

include $(top_srcdir)/src/backend/common.mk
