apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backups.operator.yugabyte.io
spec:
  group: operator.yugabyte.io
  scope: Namespaced
  names:
    plural: backups
    singular: backup
    kind: Backup
  versions:
    - name: v1alpha1
      subresources:
        status: {}
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                message:
                  type: string
                backupUUID:
                  type: string
                taskUUID:
                  type: string

            spec:
              type: object
              properties:
                backupType:
                  type: string
                  enum:
                    - YQL_TABLE_TYPE
                    - PGSQL_TABLE_TYPE
                sse:
                  type: boolean
                storageConfig:
                  type: string
                universe:
                  type: string
                tableByTableBackup:
                  type: boolean
                keyspaceTableList:
                  type: array
                  items:
                    type: string
                timeBeforeDelete:
                  type: integer
                  minimum: 0
