apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backups.operator.yugabyte.io
spec:
  group: operator.yugabyte.io
  scope: Namespaced
  names:
    plural: backups
    singular: backup
    kind: Backup
    categories:
      - all
      - yugabyte
  versions:
    - name: v1alpha1
      subresources:
        status: {}
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Custom resource definition for YugabyteDB backups.
          type: object
          properties:
            status:
              type: object
              description: Backup status for the backup custom resource.
              properties:
                message:
                  description: String log message from backup controller
                  type: string
                resourceUUID:
                  description: Internal UUID of the backup resource.
                  type: string
                taskUUID:
                  description: Internal UUID of the task associated with the backup resource.
                  type: string

            spec:
              type: object
              properties:
                backupType:
                  description: >
                    Type of backup to be taken.
                    Allowed values are -
                    YQL_TABLE_TYPE REDIS_TABLE_TYPE PGSQL_TABLE_TYPE TRANSACTION_STATUS_TABLE_TYPE
                  type: string
                  enum:
                    - YQL_TABLE_TYPE
                    - PGSQL_TABLE_TYPE
                sse:
                  description: Server side encryption for the backup.
                  type: boolean
                storageConfig:
                  description: >
                    Storage configuration for the backup,
                    should contain name of storage config object
                  type: string
                universe:
                  description: >
                    Name of the universe for which backup is to be taken,
                    refers to a ybuniverse CR name.
                  type: string
                tableByTableBackup:
                  description: Boolean indicating if backup is to be taken table by table.
                  type: boolean
                keyspace:
                  description: Name of keyspace to be backed up.
                  type: string
                timeBeforeDelete:
                  description: Time before backup is deleted from storage in milliseconds.
                  type: integer
                  minimum: 0
                incrementalBackupBase:
                  description: >
                    Base backup Custom Resource name. Operator will add an incremental backup
                    to the existing chain of backups at the last.
                  type: string
              required:
              - keyspace
              - backupType
              - storageConfig
              - universe
