#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for catalog/yb_catalog
#
# IDENTIFICATION
#    src/backend/catalog/yb_catalog/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/catalog/yb_catalog
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = yb_type.o yb_catalog_version.o

include $(top_srcdir)/src/backend/common.mk
