/*
 * Copyright (c) YugabyteDB, Inc.
 */

package byocproxy

import (
	"bytes"
	"fmt"
	"strings"
	"testing"

	"github.com/spf13/viper"
	"sigs.k8s.io/yaml"
)

func lookupString(cfg map[string]interface{}, path ...string) string {
	var current interface{} = cfg
	for _, key := range path {
		m, ok := current.(map[string]interface{})
		if !ok {
			return ""
		}
		current, ok = m[key]
		if !ok {
			return ""
		}
	}
	return strings.TrimSpace(fmt.Sprint(current))
}

func TestMergeMaps(t *testing.T) {
	defaults := map[string]interface{}{
		"yba": map[string]interface{}{
			"base_url": "https://10.0.0.1:443/api",
		},
	}
	override := map[string]interface{}{
		"yba": map[string]interface{}{
			"uuid": "e55a0e4c-3987-4e1b-89f2-28839e32c5b7",
		},
		"proxied_app": map[string]interface{}{
			"base_url": "https://api.example.com/api",
		},
	}

	merged := MergeMaps(defaults, override)

	if got := lookupString(merged, "yba", "base_url"); got != "https://10.0.0.1:443/api" {
		t.Errorf("default not preserved, got %q", got)
	}
	if got := lookupString(merged, "yba", "uuid"); got != "e55a0e4c-3987-4e1b-89f2-28839e32c5b7" {
		t.Errorf("override not merged, got %q", got)
	}
	if got := lookupString(merged, "proxied_app", "base_url"); got != "https://api.example.com/api" {
		t.Errorf("override-only key missing, got %q", got)
	}
	// Overriding base_url replaces the default.
	merged2 := MergeMaps(defaults, map[string]interface{}{
		"yba": map[string]interface{}{"base_url": "https://custom:8443/api"},
	})
	if got := lookupString(merged2, "yba", "base_url"); got != "https://custom:8443/api" {
		t.Errorf("override should win, got %q", got)
	}
	// Inputs are not mutated.
	if got := lookupString(defaults, "yba", "uuid"); got != "" {
		t.Errorf("defaults map was mutated, got uuid %q", got)
	}
}

func TestMergeMapsScalarReplacesMap(t *testing.T) {
	base := map[string]interface{}{"key": map[string]interface{}{"nested": 1}}
	override := map[string]interface{}{"key": "scalar"}
	if got := MergeMaps(base, override)["key"]; got != "scalar" {
		t.Errorf("scalar override should replace map, got %v", got)
	}
}

func TestRenderAppConfig(t *testing.T) {
	defaults := map[string]interface{}{
		"yba": map[string]interface{}{"base_url": "https://10.0.0.1:443/api"},
	}
	appConfig := map[string]interface{}{
		"yba": map[string]interface{}{"uuid": "e55a0e4c-3987-4e1b-89f2-28839e32c5b7"},
		"proxied_app": map[string]interface{}{
			"poll_batch_size": 20,
			"auth": map[string]interface{}{
				"type":    "api_key",
				"api_key": "secret",
			},
		},
	}
	out, err := RenderAppConfig(defaults, appConfig)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.HasPrefix(string(out), "# Generated by yba-ctl") {
		t.Error("missing generated header")
	}
	var parsed map[string]interface{}
	if err := yaml.Unmarshal(out, &parsed); err != nil {
		t.Fatalf("rendered config is not valid yaml: %v", err)
	}
	if got := lookupString(parsed, "yba", "uuid"); got != "e55a0e4c-3987-4e1b-89f2-28839e32c5b7" {
		t.Errorf("unexpected uuid %q", got)
	}
	if got := lookupString(parsed, "yba", "base_url"); got != "https://10.0.0.1:443/api" {
		t.Errorf("unexpected base_url %q", got)
	}
	if got := lookupString(parsed, "proxied_app", "poll_batch_size"); got != "20" {
		t.Errorf("unexpected poll_batch_size %q", got)
	}
	if got := lookupString(parsed, "proxied_app", "auth", "api_key"); got != "secret" {
		t.Errorf("unexpected api_key %q", got)
	}
}

// TestRenderAppConfigFromViper exercises the real input path: a byocApiProxy
// section read by viper (which lowercases keys and builds its own nested map
// types) rendered into application.yaml.
func TestRenderAppConfigFromViper(t *testing.T) {
	input := `
byocApiProxy:
   enabled: true
   appConfig:
      yba:
         uuid: "e55a0e4c-3987-4e1b-89f2-28839e32c5b7"
      proxied_app:
         base_url: "https://cloud.yugabyte.com/api"
         poll_batch_size: 20
         auth:
            type: api_key
            api_key: "secret"
`
	v := viper.New()
	v.SetConfigType("yaml")
	if err := v.ReadConfig(bytes.NewBufferString(input)); err != nil {
		t.Fatalf("failed to read config: %v", err)
	}

	defaults := map[string]interface{}{
		"yba": map[string]interface{}{"base_url": "https://10.0.0.1:443/api"},
	}
	out, err := RenderAppConfig(defaults, v.GetStringMap("byocApiProxy.appConfig"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	var parsed map[string]interface{}
	if err := yaml.Unmarshal(out, &parsed); err != nil {
		t.Fatalf("rendered config is not valid yaml: %v\n%s", err, out)
	}
	checks := map[string][]string{
		"e55a0e4c-3987-4e1b-89f2-28839e32c5b7": {"yba", "uuid"},
		"https://10.0.0.1:443/api":             {"yba", "base_url"},
		"https://cloud.yugabyte.com/api":       {"proxied_app", "base_url"},
		"20":                                   {"proxied_app", "poll_batch_size"},
		"api_key":                              {"proxied_app", "auth", "type"},
		"secret":                               {"proxied_app", "auth", "api_key"},
	}
	for want, path := range checks {
		if got := lookupString(parsed, path...); got != want {
			t.Errorf("%s = %q, want %q", strings.Join(path, "."), got, want)
		}
	}
}
