#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for optimizer/path
#
# IDENTIFICATION
#    src/backend/optimizer/path/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/optimizer/path
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	yb_uniqkeys.o \
	allpaths.o \
	clausesel.o \
	costsize.o \
	equivclass.o \
	indxpath.o \
	joinpath.o \
	joinrels.o \
	pathkeys.o \
	tidpath.o

include $(top_srcdir)/src/backend/common.mk
