#!/usr/bin/env bash
#
# Copyright (c) YugabyteDB, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#
# Wrapper around pgindent to supply all *typedefs.list and
# *exclude_file_patterns.

set -euo pipefail

PGINDENT=src/tools/pgindent/pgindent

# This script should be run from the base of the postgres code.
if ! [ -f "$PGINDENT" ]; then
  echo "Could not find pgindent: are you in the pg base directory?" >/dev/stderr
  exit 1
fi

"$PGINDENT" \
  --typedefs=<(find src -name '*typedefs.list' -print0 | xargs -0 cat) \
  --excludes=<(find src -name '*exclude_file_patterns' -print0 | xargs -0 cat) \
  "$@"
