---
baseurl: https://docs.yugabyte.com
languageCode: en-us
title: YugabyteDB Docs
metadataformat: yaml
canonifyurls: false
googleAnalytics: UA-104956980-3
pygmentsCodefences: true
pygmentsStyle: "pygments"
enableGitInfo: true


params:
  author: Team Yugabyte
  description: 'YugabyteDB, the transactional, high-performance database for building internet-scale, globally-distributed apps.'
  copyright: 'Yugabyte, Inc.'
  block_indexing: false
  version: Beta
  logo: /images/og-image.jpg
  favicon: /images/favicon.ico
  permalink: '#'
  custom_css: []
  custom_js: []
  highlight_css: css/highlight/hemisu.css
  palette:
    primary: orange
    accent: amber
  font:
    text: Inter
    code: Inconsolata
  algolia:
    index: yugabyte
    appID: 4LBMOWH4F9
    apiKey: 7b0692a045ac138067b8a12041ecb01a
  bigpicture:
    projectId: 1064
social: {}
menu:
  main:
    - name: Introduction
      identifier: intro
markup:
  goldmark:
    extensions:
      typographer: false
    parser:
      autoHeadingIDType: blackfriday
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 3
    ordered: false
---
