sed "s/GOOGLE_ANALYTICS_ID/$GOOGLE_ANALYTICS_ID/g; \
     s/ALGOLIA_INDEX_NAME/$ALGOLIA_INDEX_NAME/g; \
     s/ALGOLIA_APP_ID/$ALGOLIA_APP_ID/g;s/ALOGLIA_API_KEY/$ALOGLIA_API_KEY/g; \
     s/BIGPICTURE_PROJECT_ID/$BIGPICTURE_PROJECT_ID/g" config.yaml.example > config.yaml
