// Copyright (c) YugabyteDB, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied.  See the License for the specific language governing permissions and limitations
// under the License.

syntax = "proto2";

package yb.master;

option java_package = "org.yb.master";

import "yb/common/wire_protocol.proto";
import "yb/master/master_types.proto";
import "yb/rpc/service.proto";
import "yb/tserver/tserver.proto";

message RefreshYsqlLeaseRequestPB {
  optional NodeInstancePB instance = 1;
  // The current lease epoch of the tserver making this request.
  // Unset if the tserver doesn't think it has a live lease.
  optional uint64 current_lease_epoch = 2;
  optional uint64 local_request_send_time_ms = 3;
}

message RefreshYsqlLeaseInfoPB {
  optional bool new_lease = 1;
  optional uint64 lease_epoch = 2;
  // TODO: If this ends up being too big, consider adding a way to break this up
  // into multiple messages.
  optional tserver.DdlLockEntriesPB ddl_lock_entries = 3;
  optional uint64 lease_expiry_time_ms = 4;
}

message RefreshYsqlLeaseResponsePB {
  oneof refresh_ysql_lease_payload {
    MasterErrorPB error = 1;
    RefreshYsqlLeaseInfoPB info = 2;
  }
}

message RelinquishYsqlLeaseRequestPB {
  optional NodeInstancePB instance = 1;
}

message RelinquishYsqlLeaseResponsePB {
  optional MasterErrorPB error = 1;
}

service MasterYsqlLease {
  option (yb.rpc.custom_service_name) = "yb.master.MasterService";

  rpc RefreshYsqlLease(RefreshYsqlLeaseRequestPB)
      returns (RefreshYsqlLeaseResponsePB);
  rpc RelinquishYsqlLease(RelinquishYsqlLeaseRequestPB)
      returns (RelinquishYsqlLeaseResponsePB);
}
