source 'https://rubygems.org'

# We need to use versions that can run on CentOS 6, which ships Ruby 1.8.7.
gem 'thread_safe'
gem 'redcarpet', '~> 2.3.0'
gem 'jekyll', '~> 1.5.1'
gem 'therubyracer' # V8 runtime installer for Jekyll
gem 'ref', '~> 1.0'
gem 'json'
gem 'rdoc'

gem 'asciidoctor'
gem 'tilt'
