// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { AccountInfo } from './AccountInfo';
// eslint-disable-next-line no-duplicate-imports
import type { AccountSpec } from './AccountSpec';


/**
 * Account Data
 * @export
 * @interface AccountData
 */
export interface AccountData  {
  /**
   * 
   * @type {AccountSpec}
   * @memberof AccountData
   */
  spec?: AccountSpec;
  /**
   * 
   * @type {AccountInfo}
   * @memberof AccountData
   */
  info?: AccountInfo;
}



