// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { SubnetData } from './SubnetData';
// eslint-disable-next-line no-duplicate-imports
import type { VpcData } from './VpcData';


/**
 * Payload to define a network
 * @export
 * @interface AddNetworkRequest
 */
export interface AddNetworkRequest  {
  /**
   * 
   * @type {VpcData}
   * @memberof AddNetworkRequest
   */
  vpc_data: VpcData;
  /**
   * 
   * @type {SubnetData[]}
   * @memberof AddNetworkRequest
   */
  subnets?: SubnetData[];
  /**
   * The platform with which this VPC is peered
   * @type {string}
   * @memberof AddNetworkRequest
   */
  platform_id?: string;
}



