// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { AdminTokenInfo } from './AdminTokenInfo';


/**
 * 
 * @export
 * @interface AdminApiTokenResponseData
 */
export interface AdminApiTokenResponseData  {
  /**
   * The auth Jwt issued to the admin
   * @type {string}
   * @memberof AdminApiTokenResponseData
   */
  adminJwt?: string;
  /**
   * 
   * @type {AdminTokenInfo}
   * @memberof AdminApiTokenResponseData
   */
  info?: AdminTokenInfo;
}



