// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * An object containing config path and value
 * @export
 * @interface AppConfigResponseDataItem
 */
export interface AppConfigResponseDataItem  {
  /**
   * Configuration path
   * @type {string}
   * @memberof AppConfigResponseDataItem
   */
  path: string;
  /**
   * Value corresponding to the path
   * @type {string}
   * @memberof AppConfigResponseDataItem
   */
  value: string;
}



