// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Assesment complexity details
 * @export
 * @interface AssesmentComplexityInfo
 */
export interface AssesmentComplexityInfo  {
  /**
   * 
   * @type {string}
   * @memberof AssesmentComplexityInfo
   */
  schema?: string;
  /**
   * 
   * @type {number}
   * @memberof AssesmentComplexityInfo
   */
  sql_objects_count?: number;
  /**
   * 
   * @type {number}
   * @memberof AssesmentComplexityInfo
   */
  table_count?: number;
  /**
   * 
   * @type {string}
   * @memberof AssesmentComplexityInfo
   */
  complexity?: string;
}



