// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { SqlObjectCount } from './SqlObjectCount';
// eslint-disable-next-line no-duplicate-imports
import type { SqlObjectMetadata } from './SqlObjectMetadata';


/**
 * Details about Source DB\'s SQL Objects
 * @export
 * @interface AssessmentSourceDbObject
 */
export interface AssessmentSourceDbObject  {
  /**
   * 
   * @type {SqlObjectCount[]}
   * @memberof AssessmentSourceDbObject
   */
  sql_objects_count?: SqlObjectCount[];
  /**
   * 
   * @type {SqlObjectMetadata[]}
   * @memberof AssessmentSourceDbObject
   */
  sql_objects_metadata?: SqlObjectMetadata[];
}



