// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Audit event data
 * @export
 * @interface AuditEventData
 */
export interface AuditEventData  {
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  entity_name: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  audit_event_id: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  account_id: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  account_name?: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  project_id?: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  project_name?: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  cluster_id?: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  cluster_name?: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  user_id?: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  user_email?: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  impersonating_user_email?: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  task_id?: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  message: string;
  /**
   * 
   * @type {boolean}
   * @memberof AuditEventData
   */
  is_successful: boolean;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  resource_type: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  event_type: string;
  /**
   * 
   * @type {string}
   * @memberof AuditEventData
   */
  created_on: string;
}



