// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { BackupSpec } from './BackupSpec';
// eslint-disable-next-line no-duplicate-imports
import type { ScheduleSpec } from './ScheduleSpec';


/**
 * Backup schedule spec
 * @export
 * @interface BackupScheduleSpec
 */
export interface BackupScheduleSpec  {
  /**
   * 
   * @type {BackupSpec}
   * @memberof BackupScheduleSpec
   */
  backup_spec: BackupSpec;
  /**
   * 
   * @type {ScheduleSpec}
   * @memberof BackupScheduleSpec
   */
  schedule_spec: ScheduleSpec;
}



