// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { SubscriptionCapacity } from './SubscriptionCapacity';


/**
 * 
 * @export
 * @interface BillingTypeSpec
 */
export interface BillingTypeSpec  {
  /**
   * 
   * @type {number}
   * @memberof BillingTypeSpec
   */
  type: number;
  /**
   * 
   * @type {Date}
   * @memberof BillingTypeSpec
   */
  start_date?: Date;
  /**
   * 
   * @type {Date}
   * @memberof BillingTypeSpec
   */
  end_date?: Date;
  /**
   * 
   * @type {SubscriptionCapacity}
   * @memberof BillingTypeSpec
   */
  subscribed_capacity_summary?: SubscriptionCapacity;
  /**
   * 
   * @type {number}
   * @memberof BillingTypeSpec
   */
  threshold?: number;
}



