// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { InvoicePaymentEnum } from './InvoicePaymentEnum';


/**
 * Billing invoice summary data
 * @export
 * @interface BillingInvoiceSummaryData
 */
export interface BillingInvoiceSummaryData  {
  /**
   * Invoice status
   * @type {string}
   * @memberof BillingInvoiceSummaryData
   */
  status: string;
  /**
   * Invoice unique id
   * @type {string}
   * @memberof BillingInvoiceSummaryData
   */
  invoice_id: string;
  /**
   * Invoice serial number
   * @type {string}
   * @memberof BillingInvoiceSummaryData
   */
  invoice_serial_no?: string;
  /**
   * Invoice PDF downloadble link
   * @type {string}
   * @memberof BillingInvoiceSummaryData
   */
  invoice_pdf_link?: string;
  /**
   * Total invoice amount
   * @type {number}
   * @memberof BillingInvoiceSummaryData
   */
  total_amount: number;
  /**
   * Billing option i.e PayG or Subscription
   * @type {string}
   * @memberof BillingInvoiceSummaryData
   */
  billing_option: string;
  /**
   * Billing cycle period
   * @type {string}
   * @memberof BillingInvoiceSummaryData
   */
  billing_period: string;
  /**
   * Previous invoiced amount
   * @type {number}
   * @memberof BillingInvoiceSummaryData
   */
  previous_invoice_amount?: number;
  /**
   * Previous invoice generated date
   * @type {string}
   * @memberof BillingInvoiceSummaryData
   */
  last_billed_on?: string;
  /**
   * 
   * @type {InvoicePaymentEnum}
   * @memberof BillingInvoiceSummaryData
   */
  payment_status?: InvoicePaymentEnum;
  /**
   * 
   * @type {string}
   * @memberof BillingInvoiceSummaryData
   */
  payment_date?: string;
  /**
   * 
   * @type {string}
   * @memberof BillingInvoiceSummaryData
   */
  payment_method_detail?: string;
  /**
   * 
   * @type {string}
   * @memberof BillingInvoiceSummaryData
   */
  payment_method_brand?: string;
  /**
   * 
   * @type {number}
   * @memberof BillingInvoiceSummaryData
   */
  this_time_last_month_amount?: number;
  /**
   * 
   * @type {number}
   * @memberof BillingInvoiceSummaryData
   */
  amount_percentage_change_from_last_month?: number;
}



