// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Change password request payload
 * @export
 * @interface ChangePasswordRequest
 */
export interface ChangePasswordRequest  {
  /**
   * Current password associated with the user
   * @type {string}
   * @memberof ChangePasswordRequest
   */
  current_password?: string;
  /**
   * New password to associate with the user
   * @type {string}
   * @memberof ChangePasswordRequest
   */
  new_password?: string;
}



