// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * 
 * @export
 * @interface CidrListResponse
 */
export interface CidrListResponse  {
  /**
   * A list of cidrs
   * @type {string[]}
   * @memberof CidrListResponse
   */
  data?: string[];
}



