// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Node level information
 * @export
 * @interface ClusterNodeInfo
 */
export interface ClusterNodeInfo  {
  /**
   * The number of cores for each node
   * @type {number}
   * @memberof ClusterNodeInfo
   */
  num_cores: number;
  /**
   * The amount of RAM (MB) for each node
   * @type {number}
   * @memberof ClusterNodeInfo
   */
  memory_mb: number;
  /**
   * The size of disk (GB) of each node
   * @type {number}
   * @memberof ClusterNodeInfo
   */
  disk_size_gb: number;
}



