// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Upgrade Spec for Cluster Based Upgrade
 * @export
 * @interface ClusterBasedUpgradeRequestSpec
 */
export interface ClusterBasedUpgradeRequestSpec  {
  /**
   * Release ID to upgrade to (will default to latest if omitted)
   * @type {string}
   * @memberof ClusterBasedUpgradeRequestSpec
   */
  release_id?: string;
}



