// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { EntityMetadata } from './EntityMetadata';


/**
 * 
 * @export
 * @interface ClusterDataInfo
 */
export interface ClusterDataInfo  {
  /**
   * The UUID of the cluster
   * @type {string}
   * @memberof ClusterDataInfo
   */
  id: string;
  /**
   * The current state of the cluster
   * @type {string}
   * @memberof ClusterDataInfo
   */
  state: string;
  /**
   * Endpoint to connect to the cluster
   * @type {string}
   * @memberof ClusterDataInfo
   */
  endpoint?: string;
  /**
   * Endpoints to connect to the cluster by region
   * @type {{ [key: string]: string; }}
   * @memberof ClusterDataInfo
   */
  endpoints?: { [key: string]: string; };
  /**
   * ID of the associated project
   * @type {string}
   * @memberof ClusterDataInfo
   */
  project_id: string;
  /**
   * The current version of YugabyteDB installed on the cluster
   * @type {string}
   * @memberof ClusterDataInfo
   */
  software_version?: string;
  /**
   * 
   * @type {EntityMetadata}
   * @memberof ClusterDataInfo
   */
  metadata: EntityMetadata;
}



