// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Cluster instance metrics data
 * @export
 * @interface ClusterInstantMetricsData
 */
export interface ClusterInstantMetricsData  {
  /**
   * 
   * @type {number}
   * @memberof ClusterInstantMetricsData
   */
  read_ops_per_second?: number;
  /**
   * 
   * @type {number}
   * @memberof ClusterInstantMetricsData
   */
  write_ops_per_second?: number;
}



