// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Column Info
 * @export
 * @interface ColumnInfo
 */
export interface ColumnInfo  {
  /**
   * 
   * @type {string}
   * @memberof ColumnInfo
   */
  column?: string;
  /**
   * 
   * @type {string}
   * @memberof ColumnInfo
   */
  id?: string;
  /**
   * 
   * @type {string}
   * @memberof ColumnInfo
   */
  type?: string;
}



