// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { CreditData } from './CreditData';
// eslint-disable-next-line no-duplicate-imports
import type { PagingMetadata } from './PagingMetadata';


/**
 * 
 * @export
 * @interface CreditListResponse
 */
export interface CreditListResponse  {
  /**
   * 
   * @type {CreditData[]}
   * @memberof CreditListResponse
   */
  data: CreditData[];
  /**
   * 
   * @type {PagingMetadata}
   * @memberof CreditListResponse
   */
  _metadata: PagingMetadata;
}



