// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Custom Image specification
 * @export
 * @interface CustomImageSpec
 */
export interface CustomImageSpec  {
  /**
   * Name of the custom image in the cloud
   * @type {string}
   * @memberof CustomImageSpec
   */
  image_name: string;
  /**
   * Cloud region where the custom image is deployed
   * @type {string}
   * @memberof CustomImageSpec
   */
  region: string;
}



