// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { ArchitectureEnum } from './ArchitectureEnum';
// eslint-disable-next-line no-duplicate-imports
import type { CloudEnum } from './CloudEnum';
// eslint-disable-next-line no-duplicate-imports
import type { EntityMetadata } from './EntityMetadata';


/**
 * Custom Image Set List Item
 * @export
 * @interface CustomImageSetListItem
 */
export interface CustomImageSetListItem  {
  /**
   * 
   * @type {string}
   * @memberof CustomImageSetListItem
   */
  id: string;
  /**
   * 
   * @type {CloudEnum}
   * @memberof CustomImageSetListItem
   */
  cloud_type: CloudEnum;
  /**
   * Version of the DB present in the images of this custom image set
   * @type {string}
   * @memberof CustomImageSetListItem
   */
  db_version: string;
  /**
   * Base image name on which the images of this custom image set are based on
   * @type {string}
   * @memberof CustomImageSetListItem
   */
  base_image_name: string;
  /**
   * Build reference that generated images of this custom image set
   * @type {string}
   * @memberof CustomImageSetListItem
   */
  build_reference: string;
  /**
   * 
   * @type {ArchitectureEnum}
   * @memberof CustomImageSetListItem
   */
  architecture: ArchitectureEnum;
  /**
   * Denotes whether the images of this set are to be used for <cloud, db_version> combination or not
   * @type {boolean}
   * @memberof CustomImageSetListItem
   */
  is_default: boolean;
  /**
   * 
   * @type {EntityMetadata}
   * @memberof CustomImageSetListItem
   */
  metadata?: EntityMetadata;
}



