// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * DB Upgrade Event Info
 * @export
 * @interface DBUpgradeEventInfo
 */
export interface DBUpgradeEventInfo  {
  /**
   * Release ID
   * @type {string}
   * @memberof DBUpgradeEventInfo
   */
  release_id: string;
  /**
   * Track ID
   * @type {string}
   * @memberof DBUpgradeEventInfo
   */
  track_id: string;
  /**
   * Upgrade Version
   * @type {string}
   * @memberof DBUpgradeEventInfo
   */
  version: string;
  /**
   * Estimated time of completion in minutes
   * @type {number}
   * @memberof DBUpgradeEventInfo
   */
  estimated_time_mins: number;
}



