// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Request to upgrade DB version of a cluster
 * @export
 * @interface DbUpgradeRequest
 */
export interface DbUpgradeRequest  {
  /**
   * 
   * @type {string}
   * @memberof DbUpgradeRequest
   */
  release_id: string;
  /**
   * 
   * @type {boolean}
   * @memberof DbUpgradeRequest
   */
  downgrade_override?: boolean;
}



