// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Contains the entity ref and user id
 * @export
 * @interface FaultInjection
 */
export interface FaultInjection  {
  /**
   * 
   * @type {string}
   * @memberof FaultInjection
   */
  entity_ref: string;
  /**
   * 
   * @type {string}
   * @memberof FaultInjection
   */
  user_id?: string;
}



