// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * 
 * @export
 * @interface GflagsInfo
 */
export interface GflagsInfo  {
  /**
   * 
   * @type {object}
   * @memberof GflagsInfo
   */
  masterFlags: object;
  /**
   * 
   * @type {object}
   * @memberof GflagsInfo
   */
  tserverFlags: object;
}



