// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * The overage rate
 * @export
 * @interface GlobalRateCardMapOverageRate
 */
export interface GlobalRateCardMapOverageRate  {
  /**
   * Disk storage
   * @type {number}
   * @memberof GlobalRateCardMapOverageRate
   */
  disk_storage: number;
  /**
   * Backup storage
   * @type {number}
   * @memberof GlobalRateCardMapOverageRate
   */
  backup_storage: number;
}



