// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Peer two yugabyte VPC
 * @export
 * @interface InternalVpcPeeringSpec
 */
export interface InternalVpcPeeringSpec  {
  /**
   * 
   * @type {string}
   * @memberof InternalVpcPeeringSpec
   */
  vpcIdToPeer: string;
}



