// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { EntityMetadata } from './EntityMetadata';
// eslint-disable-next-line no-duplicate-imports
import type { RestoreStateEnum } from './RestoreStateEnum';


/**
 * Migration Restore Info
 * @export
 * @interface MigrationRestoreInfo
 */
export interface MigrationRestoreInfo  {
  /**
   * The UUID of the restore
   * @type {string}
   * @memberof MigrationRestoreInfo
   */
  id?: string;
  /**
   * The name of the cluster to which backup is being restored
   * @type {string}
   * @memberof MigrationRestoreInfo
   */
  cluster_name?: string;
  /**
   * Description of the restore operation
   * @type {string}
   * @memberof MigrationRestoreInfo
   */
  description?: string;
  /**
   * 
   * @type {RestoreStateEnum}
   * @memberof MigrationRestoreInfo
   */
  state?: RestoreStateEnum;
  /**
   * 
   * @type {EntityMetadata}
   * @memberof MigrationRestoreInfo
   */
  metadata?: EntityMetadata;
}



