// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Allow list for client connections to database
 * @export
 * @interface NetworkAllowListSpec
 */
export interface NetworkAllowListSpec  {
  /**
   * Name of the allow list group
   * @type {string}
   * @memberof NetworkAllowListSpec
   */
  name: string;
  /**
   * A short description of the allow list group
   * @type {string}
   * @memberof NetworkAllowListSpec
   */
  description: string;
  /**
   * The list of CIDRs
   * @type {string[]}
   * @memberof NetworkAllowListSpec
   */
  allow_list: string[];
}



