// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Node config spec
 * @export
 * @interface NodeConfigSpec
 */
export interface NodeConfigSpec  {
  /**
   * 
   * @type {number}
   * @memberof NodeConfigSpec
   */
  num_vcpus: number;
  /**
   * 
   * @type {number}
   * @memberof NodeConfigSpec
   */
  disk_storage_gb: number;
}



