// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Payment method response spec
 * @export
 * @interface PaymentMethodResponseSpec
 */
export interface PaymentMethodResponseSpec  {
  /**
   * 
   * @type {string}
   * @memberof PaymentMethodResponseSpec
   */
  payment_method_id: string;
  /**
   * 
   * @type {string}
   * @memberof PaymentMethodResponseSpec
   */
  brand: string;
  /**
   * 
   * @type {string}
   * @memberof PaymentMethodResponseSpec
   */
  last_4_digits: string;
  /**
   * 
   * @type {string}
   * @memberof PaymentMethodResponseSpec
   */
  name: string;
  /**
   * 
   * @type {string}
   * @memberof PaymentMethodResponseSpec
   */
  exp_year: string;
  /**
   * 
   * @type {string}
   * @memberof PaymentMethodResponseSpec
   */
  exp_month: string;
  /**
   * 
   * @type {boolean}
   * @memberof PaymentMethodResponseSpec
   */
  is_default: boolean;
}



