// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The current state of a VPC peering connection
 * @export
 * @enum {string}
 */
export enum PeeringStateEnum {
  Creating = 'CREATING',
  Failed = 'FAILED',
  Active = 'ACTIVE',
  Pending = 'PENDING',
  Expired = 'EXPIRED',
  Deleting = 'DELETING',
  Deleted = 'DELETED'
}


