// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Details of a Point-in-Time Recovery (PITR) schedule
 * @export
 * @interface PITRSchedule
 */
export interface PITRSchedule  {
  /**
   * 
   * @type {number}
   * @memberof PITRSchedule
   */
  id: number;
  /**
   * 
   * @type {string}
   * @memberof PITRSchedule
   */
  databaseKeyspace: string;
  /**
   * 
   * @type {string}
   * @memberof PITRSchedule
   */
  interval: string;
  /**
   * 
   * @type {string}
   * @memberof PITRSchedule
   */
  retention: string;
  /**
   * 
   * @type {string}
   * @memberof PITRSchedule
   */
  earliestRecoverableTime: string;
}



