// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Raft Config
 * @export
 * @interface RaftConfig
 */
export interface RaftConfig  {
  /**
   * 
   * @type {string}
   * @memberof RaftConfig
   */
  uuid?: string;
  /**
   * 
   * @type {string}
   * @memberof RaftConfig
   */
  role?: string;
  /**
   * 
   * @type {string}
   * @memberof RaftConfig
   */
  location?: string;
}



