// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { PagingMetadata } from './PagingMetadata';
// eslint-disable-next-line no-duplicate-imports
import type { ReadReplicaData } from './ReadReplicaData';


/**
 * 
 * @export
 * @interface ReadReplicaListResponse
 */
export interface ReadReplicaListResponse  {
  /**
   * 
   * @type {ReadReplicaData[]}
   * @memberof ReadReplicaListResponse
   */
  data: ReadReplicaData[];
  /**
   * 
   * @type {PagingMetadata}
   * @memberof ReadReplicaListResponse
   */
  _metadata: PagingMetadata;
}



