// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * count for automatic and manual refactoring
 * @export
 * @interface RefactoringCount
 */
export interface RefactoringCount  {
  /**
   * 
   * @type {string}
   * @memberof RefactoringCount
   */
  sql_object_type?: string;
  /**
   * 
   * @type {number}
   * @memberof RefactoringCount
   */
  manual?: number;
  /**
   * 
   * @type {number}
   * @memberof RefactoringCount
   */
  automatic?: number;
}



