// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { ZoneType } from './ZoneType';


/**
 * Region type
 * @export
 * @interface RegionType
 */
export interface RegionType  {
  /**
   * 
   * @type {ZoneType}
   * @memberof RegionType
   */
  same_region: ZoneType;
  /**
   * 
   * @type {number}
   * @memberof RegionType
   */
  cross_region: number;
  /**
   * 
   * @type {number}
   * @memberof RegionType
   */
  internet: number;
}



