// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { BackupKeyspaceInfo } from './BackupKeyspaceInfo';
// eslint-disable-next-line no-duplicate-imports
import type { EntityMetadata } from './EntityMetadata';
// eslint-disable-next-line no-duplicate-imports
import type { RestoreStateEnum } from './RestoreStateEnum';


/**
 * Restore Info
 * @export
 * @interface RestoreInfo
 */
export interface RestoreInfo  {
  /**
   * The UUID of the restore
   * @type {string}
   * @memberof RestoreInfo
   */
  id?: string;
  /**
   * The UUID of the project
   * @type {string}
   * @memberof RestoreInfo
   */
  project_id?: string;
  /**
   * The name of the cluster from which backup was taken
   * @type {string}
   * @memberof RestoreInfo
   */
  source_cluster_name?: string;
  /**
   * The name of the cluster to which backup is being restored
   * @type {string}
   * @memberof RestoreInfo
   */
  target_cluster_name?: string;
  /**
   * Description of the restore operation
   * @type {string}
   * @memberof RestoreInfo
   */
  description?: string;
  /**
   * 
   * @type {BackupKeyspaceInfo[]}
   * @memberof RestoreInfo
   */
  keyspace_info?: BackupKeyspaceInfo[];
  /**
   * 
   * @type {RestoreStateEnum}
   * @memberof RestoreInfo
   */
  state?: RestoreStateEnum;
  /**
   * 
   * @type {EntityMetadata}
   * @memberof RestoreInfo
   */
  metadata?: EntityMetadata;
  /**
   * 
   * @type {number}
   * @memberof RestoreInfo
   */
  size_in_bytes?: number;
}



