// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Backup spec
 * @export
 * @interface RestoreSpec
 */
export interface RestoreSpec  {
  /**
   * The UUID of the backup
   * @type {string}
   * @memberof RestoreSpec
   */
  backup_id?: string;
  /**
   * The UUID of the cluster
   * @type {string}
   * @memberof RestoreSpec
   */
  cluster_id?: string;
}



