// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * RBAC Role Data
 * @export
 * @interface RoleData
 */
export interface RoleData  {
  /**
   * The UUID of the RBAC role
   * @type {string}
   * @memberof RoleData
   */
  id: string;
  /**
   * Name of the RBAC role
   * @type {string}
   * @memberof RoleData
   */
  name: string;
  /**
   * Description of the RBAC role
   * @type {string}
   * @memberof RoleData
   */
  description: string;
}



