// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { PagingMetadata } from './PagingMetadata';
// eslint-disable-next-line no-duplicate-imports
import type { ScheduleData } from './ScheduleData';


/**
 * 
 * @export
 * @interface ScheduleListResponse
 */
export interface ScheduleListResponse  {
  /**
   * 
   * @type {ScheduleData[]}
   * @memberof ScheduleListResponse
   */
  data: ScheduleData[];
  /**
   * 
   * @type {PagingMetadata}
   * @memberof ScheduleListResponse
   */
  _metadata: PagingMetadata;
}



