// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { DBUpgradeEventInfo } from './DBUpgradeEventInfo';
// eslint-disable-next-line no-duplicate-imports
import type { MaintenanceWindowEventStateEnum } from './MaintenanceWindowEventStateEnum';
// eslint-disable-next-line no-duplicate-imports
import type { MaintenanceWindowEventTypeEnum } from './MaintenanceWindowEventTypeEnum';
// eslint-disable-next-line no-duplicate-imports
import type { MaintenanceWindowInfo } from './MaintenanceWindowInfo';


/**
 * Scheduled Maintenance Event Data
 * @export
 * @interface ScheduledMaintenanceEventData
 */
export interface ScheduledMaintenanceEventData  {
  /**
   * Scheduled Execution ID
   * @type {string}
   * @memberof ScheduledMaintenanceEventData
   */
  scheduled_execution_id: string;
  /**
   * indicates if this event can be delayed
   * @type {boolean}
   * @memberof ScheduledMaintenanceEventData
   */
  can_delay: boolean;
  /**
   * indicates if this event can be triggered immediately
   * @type {boolean}
   * @memberof ScheduledMaintenanceEventData
   */
  can_trigger: boolean;
  /**
   * 
   * @type {MaintenanceWindowEventTypeEnum}
   * @memberof ScheduledMaintenanceEventData
   */
  event_type: MaintenanceWindowEventTypeEnum;
  /**
   * 
   * @type {DBUpgradeEventInfo}
   * @memberof ScheduledMaintenanceEventData
   */
  event_info: DBUpgradeEventInfo;
  /**
   * 
   * @type {MaintenanceWindowEventStateEnum}
   * @memberof ScheduledMaintenanceEventData
   */
  state: MaintenanceWindowEventStateEnum;
  /**
   * 
   * @type {MaintenanceWindowInfo}
   * @memberof ScheduledMaintenanceEventData
   */
  maintenance_window: MaintenanceWindowInfo;
}



