// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { RefactoringCount } from './RefactoringCount';
// eslint-disable-next-line no-duplicate-imports
import type { SqlObjectsDetails } from './SqlObjectsDetails';


/**
 * Voyager data migration metrics details
 * @export
 * @interface SchemaAnalysisReport
 */
export interface SchemaAnalysisReport  {
  /**
   * 
   * @type {string}
   * @memberof SchemaAnalysisReport
   */
  voyager_version?: string;
  /**
   * 
   * @type {string}
   * @memberof SchemaAnalysisReport
   */
  target_db_version?: string;
  /**
   * 
   * @type {SqlObjectsDetails[]}
   * @memberof SchemaAnalysisReport
   */
  sql_objects?: SqlObjectsDetails[];
  /**
   * 
   * @type {RefactoringCount[]}
   * @memberof SchemaAnalysisReport
   */
  recommended_refactoring?: RefactoringCount[];
}



