// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { SingleTenantVpcDataResponseInfo } from './SingleTenantVpcDataResponseInfo';
// eslint-disable-next-line no-duplicate-imports
import type { SingleTenantVpcSpec } from './SingleTenantVpcSpec';


/**
 * 
 * @export
 * @interface SingleTenantVpcDataResponse
 */
export interface SingleTenantVpcDataResponse  {
  /**
   * 
   * @type {SingleTenantVpcSpec}
   * @memberof SingleTenantVpcDataResponse
   */
  spec: SingleTenantVpcSpec;
  /**
   * 
   * @type {SingleTenantVpcDataResponseInfo}
   * @memberof SingleTenantVpcDataResponse
   */
  info: SingleTenantVpcDataResponseInfo;
}



