// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { SoftwareReleaseInfo } from './SoftwareReleaseInfo';
// eslint-disable-next-line no-duplicate-imports
import type { SoftwareReleaseSpec } from './SoftwareReleaseSpec';


/**
 * Software release data
 * @export
 * @interface SoftwareReleaseData
 */
export interface SoftwareReleaseData  {
  /**
   * 
   * @type {SoftwareReleaseSpec}
   * @memberof SoftwareReleaseData
   */
  spec: SoftwareReleaseSpec;
  /**
   * 
   * @type {SoftwareReleaseInfo}
   * @memberof SoftwareReleaseData
   */
  info: SoftwareReleaseInfo;
}



