// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Software release track Info
 * @export
 * @interface SoftwareReleaseTrackInfo
 */
export interface SoftwareReleaseTrackInfo  {
  /**
   * The UUID of the release track
   * @type {string}
   * @memberof SoftwareReleaseTrackInfo
   */
  id: string;
  /**
   * 
   * @type {string}
   * @memberof SoftwareReleaseTrackInfo
   */
  default_release_id?: string;
}



