// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { SoftwareReleaseTrackInfo } from './SoftwareReleaseTrackInfo';
// eslint-disable-next-line no-duplicate-imports
import type { SoftwareReleaseTrackSpec } from './SoftwareReleaseTrackSpec';


/**
 * Software release track data
 * @export
 * @interface SoftwareReleaseTrackData
 */
export interface SoftwareReleaseTrackData  {
  /**
   * 
   * @type {SoftwareReleaseTrackSpec}
   * @memberof SoftwareReleaseTrackData
   */
  spec?: SoftwareReleaseTrackSpec;
  /**
   * 
   * @type {SoftwareReleaseTrackInfo}
   * @memberof SoftwareReleaseTrackData
   */
  info?: SoftwareReleaseTrackInfo;
}



