// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { PagingMetadata } from './PagingMetadata';
// eslint-disable-next-line no-duplicate-imports
import type { SoftwareReleaseData } from './SoftwareReleaseData';


/**
 * 
 * @export
 * @interface SoftwareReleaseListResponse
 */
export interface SoftwareReleaseListResponse  {
  /**
   * 
   * @type {SoftwareReleaseData[]}
   * @memberof SoftwareReleaseListResponse
   */
  data: SoftwareReleaseData[];
  /**
   * 
   * @type {PagingMetadata}
   * @memberof SoftwareReleaseListResponse
   */
  _metadata: PagingMetadata;
}



