// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Source Database details
 * @export
 * @interface SourceDatabaseInfo
 */
export interface SourceDatabaseInfo  {
  /**
   * 
   * @type {number}
   * @memberof SourceDatabaseInfo
   */
  table_size?: number;
  /**
   * 
   * @type {number}
   * @memberof SourceDatabaseInfo
   */
  table_row_count?: number;
  /**
   * 
   * @type {number}
   * @memberof SourceDatabaseInfo
   */
  total_table_size?: number;
  /**
   * 
   * @type {number}
   * @memberof SourceDatabaseInfo
   */
  total_index_size?: number;
}



