// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * 
 * @export
 * @interface SubscriptionCapacity
 */
export interface SubscriptionCapacity  {
  /**
   * 
   * @type {number}
   * @memberof SubscriptionCapacity
   */
  prod_vcpus: number;
  /**
   * 
   * @type {number}
   * @memberof SubscriptionCapacity
   */
  non_prod_vcpus: number;
}



