// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Target YugabyteDB cluster schema recommendations
 * @export
 * @interface TargetSchemaRecommendations
 */
export interface TargetSchemaRecommendations  {
  /**
   * 
   * @type {number}
   * @memberof TargetSchemaRecommendations
   */
  no_of_colocated_tables?: number;
  /**
   * 
   * @type {number}
   * @memberof TargetSchemaRecommendations
   */
  total_size_colocated_tables?: number;
  /**
   * 
   * @type {number}
   * @memberof TargetSchemaRecommendations
   */
  no_of_sharded_tables?: number;
  /**
   * 
   * @type {number}
   * @memberof TargetSchemaRecommendations
   */
  total_size_sharded_tables?: number;
}



