// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Unsupported SQL Info
 * @export
 * @interface UnsupportedSqlInfo
 */
export interface UnsupportedSqlInfo  {
  /**
   * 
   * @type {string}
   * @memberof UnsupportedSqlInfo
   */
  unsupported_type?: string;
  /**
   * 
   * @type {number}
   * @memberof UnsupportedSqlInfo
   */
  count?: number;
}



