// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Update credits for an account
 * @export
 * @interface UpdateCreditsSpec
 */
export interface UpdateCreditsSpec  {
  /**
   * 
   * @type {number}
   * @memberof UpdateCreditsSpec
   */
  total_credits: number;
}



