// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { CloudEnum } from './CloudEnum';
// eslint-disable-next-line no-duplicate-imports
import type { ClusterTier } from './ClusterTier';


/**
 * Filters to limit scheduled upgrade scope
 * @export
 * @interface UpgradeRequestFilters
 */
export interface UpgradeRequestFilters  {
  /**
   * 
   * @type {CloudEnum}
   * @memberof UpgradeRequestFilters
   */
  cloud_type?: CloudEnum;
  /**
   * 
   * @type {string}
   * @memberof UpgradeRequestFilters
   */
  region?: string;
  /**
   * 
   * @type {ClusterTier}
   * @memberof UpgradeRequestFilters
   */
  cluster_tier?: ClusterTier;
}



