// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * 
 * @export
 * @interface UserAccountRoleData
 */
export interface UserAccountRoleData  {
  /**
   * 
   * @type {string}
   * @memberof UserAccountRoleData
   */
  account_id: string;
  /**
   * Role Ids
   * @type {string[]}
   * @memberof UserAccountRoleData
   */
  role_ids: string[];
}



