// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Information regarding a specific voyager migration task
 * @export
 * @interface VoyagerMigrationDetails
 */
export interface VoyagerMigrationDetails  {
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrationDetails
   */
  migration_uuid?: string;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrationDetails
   */
  migration_name?: string;
  /**
   * 
   * @type {number}
   * @memberof VoyagerMigrationDetails
   */
  migration_phase?: number;
  /**
   * 
   * @type {number}
   * @memberof VoyagerMigrationDetails
   */
  invocation_sequence?: number;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrationDetails
   */
  source_db?: string;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrationDetails
   */
  complexity?: string;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrationDetails
   */
  database_name?: string;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrationDetails
   */
  schema_name?: string;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrationDetails
   */
  status?: string;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrationDetails
   */
  invocation_timestamp?: string;
}



