// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * 
 * @export
 * @interface VoyagerMigrationDetailsVoyager
 */
export interface VoyagerMigrationDetailsVoyager  {
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrationDetailsVoyager
   */
  machine_ip?: string;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrationDetailsVoyager
   */
  os?: string;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrationDetailsVoyager
   */
  avail_disk_bytes?: string;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrationDetailsVoyager
   */
  export_dir?: string;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrationDetailsVoyager
   */
  exported_schema_location?: string;
}



