// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Voyager data migration metrics details
 * @export
 * @interface VoyagerMigrateDataMetricsDetails
 */
export interface VoyagerMigrateDataMetricsDetails  {
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrateDataMetricsDetails
   */
  migration_uuid?: string;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrateDataMetricsDetails
   */
  table_name?: string;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrateDataMetricsDetails
   */
  schema_name?: string;
  /**
   * 
   * @type {number}
   * @memberof VoyagerMigrateDataMetricsDetails
   */
  migration_phase?: number;
  /**
   * 
   * @type {number}
   * @memberof VoyagerMigrateDataMetricsDetails
   */
  status?: number;
  /**
   * 
   * @type {number}
   * @memberof VoyagerMigrateDataMetricsDetails
   */
  count_live_rows?: number;
  /**
   * 
   * @type {number}
   * @memberof VoyagerMigrateDataMetricsDetails
   */
  count_total_rows?: number;
  /**
   * 
   * @type {string}
   * @memberof VoyagerMigrateDataMetricsDetails
   */
  invocation_timestamp?: string;
}



