// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// eslint-disable-next-line no-duplicate-imports
import type { TablesListWithLag } from './TablesListWithLag';


/**
 * Schema for xCluster replication group details.
 * @export
 * @interface XClusterOutboundGroupID
 */
export interface XClusterOutboundGroupID  {
  /**
   * Unique identifier for the replication group.
   * @type {string}
   * @memberof XClusterOutboundGroupID
   */
  replication_group_id: string;
  /**
   * The current status of the replication group (e.g., \'active\', \'inactive\').
   * @type {string}
   * @memberof XClusterOutboundGroupID
   */
  state: string;
  /**
   * The IP address of the cluster involved in the replication.
   * @type {string}
   * @memberof XClusterOutboundGroupID
   */
  current_cluster_ip_address: string;
  /**
   * Indicates whether the replication is outbound (true) or inbound (false).
   * @type {boolean}
   * @memberof XClusterOutboundGroupID
   */
  is_outbound: boolean;
  /**
   * Indicates whether the replication is inbound (true) or outbound (false).
   * @type {boolean}
   * @memberof XClusterOutboundGroupID
   */
  is_inbound: boolean;
  /**
   * UUID of the target universe for the replication group.
   * @type {string}
   * @memberof XClusterOutboundGroupID
   */
  target_universe_uuid: string;
  /**
   * List of namespaces from outbound and lag of each table
   * @type {TablesListWithLag[]}
   * @memberof XClusterOutboundGroupID
   */
  tables_list_with_lag?: TablesListWithLag[];
}



