// tslint:disable
/**
 * Yugabyte Cloud
 * YugabyteDB as a Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@yugabyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * Schema for xCluster replication group details.
 * @export
 * @interface XClusterInboundGroupID
 */
export interface XClusterInboundGroupID  {
  /**
   * Unique identifier for the replication group.
   * @type {string}
   * @memberof XClusterInboundGroupID
   */
  replication_group_id: string;
  /**
   * The current status of the replication group (e.g., \'active\', \'inactive\').
   * @type {string}
   * @memberof XClusterInboundGroupID
   */
  state: string;
  /**
   * The IP address of the cluster involved in the replication.
   * @type {string}
   * @memberof XClusterInboundGroupID
   */
  current_cluster_ip_address: string;
  /**
   * Indicates whether the replication is outbound (true) or inbound (false).
   * @type {boolean}
   * @memberof XClusterInboundGroupID
   */
  is_outbound: boolean;
  /**
   * Indicates whether the replication is inbound (true) or outbound (false).
   * @type {boolean}
   * @memberof XClusterInboundGroupID
   */
  is_inbound: boolean;
  /**
   * Host address for the source cluster\'s leader node.
   * @type {string}
   * @memberof XClusterInboundGroupID
   */
  source_leader_host: string;
}



