#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/yb_lsm
#
# IDENTIFICATION
#    src/backend/access/yb_lsm/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/yb_lsm
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	yb_lsm.o

include $(top_srcdir)/src/backend/common.mk
