--
-- SELECT
--

CREATE TABLE nr (i int, j int, PRIMARY KEY (j ASC));
CREATE INDEX ON nr (i ASC);
INSERT INTO nr VALUES (1, 2), (3, 4);
BEGIN;
INSERT INTO nr VALUES (null, 6);
SELECT i FROM nr ORDER BY i;
SELECT i FROM nr ORDER BY i NULLS FIRST;
SELECT i FROM nr ORDER BY i DESC;
SELECT i FROM nr ORDER BY i DESC NULLS LAST;
ROLLBACK;

CREATE TABLE nr2 (i int, j int, PRIMARY KEY (j ASC));
CREATE INDEX ON nr2 (i DESC);
INSERT INTO nr2 VALUES (1, 2), (3, 4);
BEGIN;
INSERT INTO nr2 VALUES (null, 6);
SELECT i FROM nr2 ORDER BY i;
SELECT i FROM nr2 ORDER BY i NULLS FIRST;
SELECT i FROM nr2 ORDER BY i DESC;
SELECT i FROM nr2 ORDER BY i DESC NULLS LAST;
ROLLBACK;
