CREATE DATABASE test_tablegroup_partitioned_tables;
\c test_tablegroup_partitioned_tables
CREATE TABLEGROUP tg1;
CREATE TABLE prt (id int PRIMARY KEY, v int) PARTITION BY RANGE (id) TABLEGROUP tg1;
CREATE TABLE prt_p1 PARTITION OF prt FOR VALUES FROM (1) TO (2);
CREATE TABLE IF NOT EXISTS prt_p2 PARTITION OF prt FOR VALUES FROM (2) TO (3);
\dgrt
CREATE TABLE prt_p3 PARTITION OF prt FOR VALUES FROM (3) TO (4) TABLEGROUP tg1;
CREATE TABLE IF NOT EXISTS prt_p4 PARTITION OF prt FOR VALUES FROM (4) TO (5) TABLEGROUP tg1;
