name: "bld-docs"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/**'
      - README.md

jobs:
  bld-docs:
    # Runs on jenkins, but very light-weight, so no approval required.
    # environment: jenkins
    runs-on: ybdbghr
    steps:
      - name: Build Trigger
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
        run: ybbld "$PR_NUMBER" "$PR_SHA" DOCS
