name: "Check PR Title"

on:
  pull_request:
    types: [opened, edited]
    paths-ignore:
      - README.md
      - 'docs/**'

jobs:
  gh-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        run: |
          TITLE_RE='^(\[(BACKPORT )?(\d+(\.\d+)+)\])?'
          TITLE_RE+='\[((#\d+(,#[0-9]+)*)|([A-Z]+-[0-9]+(,[A-Z]+-[0-9]+)*))\]'
          TITLE_RE+=' [a-zA-Z0-9_-]+(,[[a-zA-Z0-9_]-]+)*:'
          TITLE_RE+=' \S.{8,98}\S$'

          if [[ ! "${{ github.event.pull_request.title }}" =~ $TITLE_RE ]]; then
            echo "::error ::PR title must include issue ID, code area (no extra whitespace),"
            echo "::error :: and a short description."
            echo "::error ::Issue referenced must be a github issue or YB-internal Jira ID"
            echo "::error ::Short description must be less than 100 characters."
            echo "::error ::Backport branch should be used only for non-master release branches."
            echo "::error ::Examples:"
            echo "::error ::  [#12345,#12367] area: Cool feature xyz"
            echo "::error ::  [BACKPORT 2045.1][#12345] area1,area2: Must have fix"
            exit 1
          fi
